### ISSUE TITLE
Converting nonexistent column?

### ISSUE THREAD

**Issue by gnudiff** [laurenz/oracle_fdw#296] opened 2019-02-07 23:14 UTC
Just got a weird error on one of the imported foreign tables (actually they are Oracle views).

> STATEMENT:  SELECT * FROM v6.v_mytable
> ERROR:  invalid input syntax for integer: "IT40103297429"
> CONTEXT:  converting column "needxxx" for foreign table scan of "v_mytable", row 1
> 

(1) That column does not have non-integer values. In fact it is a smallint not null column and all entries in the table are 0.
(2) The value quoted might exist in another column of the table.

When I tried a SELECT without "needxxx" column, like "SELECT DISTINCT client from v6.v_mytable", it worked, but I received 2 entries only, whereas the query in question returnns >150 rows with distinct client IDs when executed directly in SQLPlus.

Since Oracle had been restarted in the weekend, I thought maybe some link to Oracle on the Postgres machine was stale, but restarting Postgres machine didn't help.

Had to reimport foreign schema for that table, which seemed to fix the issue, but decided to report it anyway, just in case.

Evnironment:

> Ubuntu 16.04.5 LTS  // Linux 4.4.0-142-generic SMP x86_64 
> postgresql     9.5+173ubuntu0.2 -- from distro package
> oracle-instantclient12.2-devel_12.2.0.1.0-2_amd64.deb
> oracle_fdw-2.0.0 compiled from source
> Oracle is:  Oracle Database 11g Release 11.2.0.4.0 - 64bit Production (Windows 2012SRV)

**Comment by laurenz** [comment] 2019-02-08 08:58
I strongly suspect that this is a duplicate of #201 and #1.

Like the README says:

> When you define a foreign table, the columns of the Oracle table are mapped     
> to the PostgreSQL columns in the order of their definition.

So I suspect that both the Oracle table and the foreign table did have a column named `needxxx`, but they were in a different position in both tables.

For example:

1. Oracle:

       CREATE TABLE mytable (needxxx NUMBER(5), other VARCHAR2(30));

2. PostgreSQL:

       CREATE FOREIGN TABLE v_mytable(other character varying(30), needxxx integer)
          SERVER oracle OPTIONS (table 'MYTABLE');

Here oracle_fdw would map the Oracle column `other` to `needxxx` in PostgreSQL, which would cause an error like the one you observed.

**Closed by laurenz** 2019-02-08 08:58 UTC

**Comment by gnudiff** [comment] 2019-02-09 09:44
Interesting. Do you think it should be the problem even when importing the table, rather than attempting to create it manually in Postgres?

Because I am only making the Postgres tables by:

``import foreign schema "oraschema" limit to (v_mytable) from server oracle into v6``

Of course, initially I did it without limit. I only reimport it with limit after the failure.

**Comment by laurenz** [comment] 2019-02-11 10:04
No, `IMPORT FOREIGN SCHEMA` should work fine.

Without the `LIMIT` you can get many more foreign tables, but the tables themselves should be no different. In other words, it should have worked without the `LIMIT` as well.

If you ever again encounter such a table, I'd need to know the `DESC tabname` output in Oracle and the `\d tabname` output in PostgreSQL.

**Comment by gnudiff** [comment] 2019-02-11 11:45
Sure, thanks.  Just a guess, would this error be something that would happen if you IMPORT oracle table in Postgres, then change the table structure in Oracle (eg. add more columns)? This might have happened, I am not sure yet (I am not in charge of the Oracle DB).

**Comment by laurenz** [comment] 2019-02-11 12:49
Yes, that could definitely cause that error.
