### ISSUE TITLE
error with installing oracle_fdw for postgresql9.6 and oracle11.2 on centos7

### ISSUE THREAD

**Issue by AP0908330** [laurenz/oracle_fdw#320] opened 2019-05-15 08:07 UTC
Hi,I'm trying to install oracle_fdw for postgresql9.6 and oracle11.2 on centos7
```
tar -zxvf oracle_fdw-ORACLE_FDW_2_1_0.tar.gz

yum localinstall oracle-instantclient11.2-basic-11.2.0.4.0-1.x86_64.rpm oracle-instantclient11.2-devel-11.2.0.4.0-1.x86_64.rpm

export PATH=/usr/local/pgsql/bin:$PATH
export ORACLE_HOME=/usr/lib/oracle/11.2/client64
export LD_LIBRARY_PATH=/usr/lib/oracle/11.2/client64/lib

```

when i make,get a error 
```
[root@localhost oracle_fdw]# make
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -O2 -fpic -I/usr/lib/oracle/11.2/client64/sdk/include -I/usr/lib/oracle/11.2/client64/oci/include -I/usr/lib/oracle/11.2/client64/rdbms/public -I/usr/include/oracle/12.2/client -I/usr/include/oracle/12.2/client64 -I/usr/include/oracle/12.1/client -I/usr/include/oracle/12.1/client64 -I/usr/include/oracle/11.2/client -I/usr/include/oracle/11.2/client64 -I/usr/include/oracle/11.1/client -I/usr/include/oracle/11.1/client64 -I/usr/include/oracle/10.2.0.5/client -I/usr/include/oracle/10.2.0.5/client64 -I/usr/include/oracle/10.2.0.4/client -I/usr/include/oracle/10.2.0.4/client64 -I/usr/include/oracle/10.2.0.3/client -I/usr/include/oracle/10.2.0.3/client64 -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_GNU_SOURCE   -c -o oracle_fdw.o oracle_fdw.c
oracle_fdw.c: In function ‘foreign_join_ok’:
oracle_fdw.c:2919: warning: passing argument 2 of ‘extract_actual_join_clauses’ from incompatible pointer type
/usr/local/pgsql/include/server/optimizer/restrictinfo.h:38: note: expected ‘struct List **’ but argument is of type ‘Relids’
oracle_fdw.c:2919: error: too many arguments to function ‘extract_actual_join_clauses’
make: *** [oracle_fdw.o] Error 1

```
Looking forward to your response. thx!

**Comment by laurenz** [comment] 2019-05-15 09:20
This seems to be a duplicate of #272.

Please upgrade to a later minor release of PostgreSQL 9.6; version 9.6.9 or later should work.

**Comment by AP0908330** [comment] 2019-05-15 10:59
Thx!

**Comment by AP0908330** [comment] 2019-05-20 10:51
Hi, I'm trying to install oracle_fdw 1.5.0 for postgresql9.6 and oracle11.2 on centos7. It's working.

but it's not working when postgresql change to 9.5.17.
when I make .get bellow error：
Makefile:23: /usr/pgsql-9.5/lib/pgxs/src/makefiles/pgxs.mk: No such file or directory
make: *** No rule to make target `/usr/pgsql-9.5/lib/pgxs/src/makefiles/pgxs.mk'.  Stop.

**Closed** 2019-05-20 20:05 UTC
Labels: duplicate, installation, problem
