### ISSUE TITLE
Oracle FDW conflicts with DB2 FDW

### ISSUE THREAD

**Issue by gferrette** [laurenz/oracle_fdw#281] opened 2018-11-05 10:29 UTC
Hello!

We've installed db2_fdw and oracle_fdw at the same postgres database, so we can connect to oracle tables and db2 tables. It seems that both of the fdw packages can not be used together, because when we start querying an db2 table it works fine, but when we try to query the oracle table, it gaves an error.
If we disconnect from the postgres database and connect again, we can query the oracle table succesfully, but then when query the db2 table, it gaves an error too.

Follow below the errors:

The table sseg.rssi11_tes is using the db2_fdw and the table faep.nfpx57_r is using oracle_fdw:

faepex_teste=# select * from sseg.rssi11_tes limit 2;
NOTICE: connection for foreign table "rssi11_tes" cannot be established
DETAIL: ORA-12154: TNS:could not resolve the connect identifier specified

faepex_teste=# select * from faep.nfpx57_r limit 2;
ERROR: error connecting to Oracle: OCIAttrSet failed to set module in session handle
DETAIL: CLI0124E Invalid argument value.

PS: If we disconnect and connect to postgres and query one of the tables, it works fine. But when we start to query , for example, db2 tables, oracle tables stops working. If we start querying oracle tables, db2 tables stops working.

Can you help me please?

Thanks!

Gabriel.

**Comment by laurenz** [comment] 2018-11-05 10:51
I would say that the problem is that IBM's DB2CI library uses the same API functions as Oracle's OCI, so you cannot link them with the same executable (PostgreSQL).

The respective shared library gets loaded when you first access a foreign table, and the first loaded library &ldquo;wins&rdquo; by shadowing API functions of the same name loaded by a later library.

So you can only use either oracle_fdw or db2_fdw in one database session, and there is no good workaround for that.

This issue is a duplicate of wolfgangbrandl/db2_fdw#9.

@wolfgangbrandl, do you agree with my analysis?

**Comment by gferrette** [comment] 2018-11-05 11:49
Hello Laurenz!

Thanks a lot for the quick replying.

We need to use both oracle and db2 foreign tables at the same postgresql database session. To make a workaround for that i was thinking of using jdbc_fdw or odbc_fdw. The problem with jdbc_fdw is that the performance of the queries is too slow.
Just a curious question, do you recomend jdbc_fdw or odbc_fdw in that case to access oracle tables?

Thanks again for the help!

Gabriel.

**Comment by laurenz** [comment] 2018-11-05 11:55
I don't have any recommendations for jdbc_fdw vs. odbc_fdw.

An ugly kludge you could also try is to use a second PostgreSQL connection inside the first one, so that you access e.g. oracle_fdw locally and db2_fdw via dblink or postgres_fdw.

**Comment by chrullrich** [comment] 2018-11-05 12:14
@laurenz, please forgive me for intruding into a topic I know little about, but might it be a viable workaround to use dlopen(RTLD_LOCAL|RTLD_DEEPBIND) to load OCI instead of linking to it? It might be necessary to ensure that db2_fdw is loaded first, but it could neither shadow Oracle symbols from oracle_fdw, nor let oracle_fdw or OCI shadow DB2 symbols.

**Comment by gferrette** [comment] 2018-11-05 13:42
Hello Laurenz,

I'd like to thank you for the tip of using a second PostgreSQL connection inside the first one. I've made a test using postgres_fdw, to create a foreign_table inside the same database mapping the foreign_table that is using db2_fdw and it worked like a charm!

Thanks a lot and congratulations for your work!

Gabriel.

**Closed** 2019-01-17 08:52 UTC
Labels: duplicate, problem
