### ISSUE TITLE
error connecting to Oracle: OCIEnvCreate failed to create environment handle

### ISSUE THREAD

**Issue by houzi1099857978** [laurenz/oracle_fdw#407] opened 2020-07-06 15:00 UTC
when I select a foreingtable in postgresSQL the flowing error occured :

postgres=# select * from ft_student;
ERROR:  error connecting to Oracle: OCIEnvCreate failed to create environment handle
DETAIL:

**Comment by houzi1099857978** [comment] 2020-07-06 15:04
020-07-07 07:03:13.727 CST [31778] LOCATION:  log_disconnections, postgres.c:4513
2020-07-07 07:03:19.797 CST [25557] ERROR:  HV00N: error connecting to Oracle: OCIEnvCreate failed to create environment handle
2020-07-07 07:03:19.797 CST [25557] DETAIL:  
2020-07-07 07:03:19.797 CST [25557] LOCATION:  oracleError_d, oracle_fdw.c:6567
2020-07-07 07:03:19.797 CST [25557] STATEMENT:  select * from ft_student;
2020-07-07 07:03:20.893 CST [31912] LOG:  00000: connection received: host=[local]
2020-07-07 07:03:20.893 CST [31912] LOCATION:  BackendInitialize, postmaster.c:4253
2020-07-07 07:03:20.894 CST [31912] LOG:  00000: connection authorized: user=postgres database=postgres
2020-07-07 07:03:20.894 CST [31912] LOCATION:  PerformAuthentication, postinit.c:272
2020-07-07 07:03:20.905 CST [31912] LOG:  00000: disconnection: session time: 0:00:00.012 user=postgres database=postgres host=[local]

**Comment by houzi1099857978** [comment] 2020-07-06 15:14
CREATE SERVER oracle_srv FOREIGN DATA WRAPPER oracle_fdw OPTIONS (dbserver 'primary_1');
alter server oracle_srv options ( set  dbserver 'testdb');
CREATE USER MAPPING FOR postgres SERVER oracle_srv  OPTIONS (user 'houzi', password 'Houzi123456');  
CREATE FOREIGN TABLE ft_student (id NUMERIC,  name varchar(100) ,ADDRESS varchar(255),PHONE varchar(20))
SERVER oracle_srv  OPTIONS (schema 'HOUZI', table 'STUDENT');

**Comment by houzi1099857978** [comment] 2020-07-06 15:18
I added to the .profle(for postgres user),On the Postgresql server, I've installed Oracle Client, and configured it to connect to the Oracle database. sqlplus name/password@ORCL is working on the command line.
export PGHOME=/home/postgres/app/pg103
export PGDATA=/home/postgres/pgdata/
export LD_LIBRARY_PATH=$PGHOME/lib:$LD_LIBRARY_PATH:
export PATH=$PATH:$PGHOME/bin

export ORACLE_HOME=/home/postgres/oracle/instantclient_11_2
export ORACLE_SID=orcl
export TNS_ADMIN=$ORACLE_HOME/network/admin
export LD_LIBRARY_PATH=$ORACLE_HOME:$LD_LIBRARY_PATH
#export NLS_LANG='simplified chinese_china'.ZHS16GBK
export NLS_LANG='AMERICAN_AMERICA.AL32UTF8'
export PATH=$PATH:$ORACLE_HOME

**Comment by laurenz** [comment] 2020-07-07 07:35
If sqlplus works, then there is probably a problem in the environment of your PostgreSQL server.

Look at #307 and the many issues linked from there.

What do you get for the postmaster's environment (see for example [#305](305#issuecomment-474340877))?

**Comment by houzi1099857978** [comment] 2020-07-07 12:38
I think I got the same problem like  #307 ,but how to set ORACLE_HOME in the environment of the Postgres server process,
I use pg_cli to start postgres,and the environment is suseLinux12 sp3,Actually the postgresSQL is started by corosync+pacemaker cluster.

postgres=# select oracle_diag();
                         oracle_diag                         
-------------------------------------------------------------
 oracle_fdw 2.2.0, PostgreSQL 10.5, Oracle client 11.2.0.4.0
(1 row)

**Comment by laurenz** [comment] 2020-07-07 12:42
I have never heard of `pg_cli`.
Each startup script offers ways to customize environment variables.
If you show me the startup script, perhaps I get a clue.

**Comment by houzi1099857978** [comment] 2020-07-07 12:48
I find if I install the oracle-instantclient11.2-basiclite-11.2.0.4.0-1.x86_64.rpm addtional can also solve the problem, but why it doesn't work if i use instantclient-basiclite-linux.x64-11.2.0.4.0.zip and set the environment variables in  .profile(postgres user).
while anyother problem occured if use both oracle-instantclient11.2-basiclite-11.2.0.4.0-1.x86_64.rpm and instantclient-basiclite-linux.x64-11.2.0.4.0.zip?

**Comment by houzi1099857978** [comment] 2020-07-07 12:50
sorry,is pg_ctl

**Comment by houzi1099857978** [comment] 2020-07-07 12:53
> I have never heard of `pg_cli`.
> Each startup script offers ways to customize environment variables.
> If you show me the startup s67391cript, perhaps I get a clue.

sorry, is pg_ctl

**Comment by laurenz** [comment] 2020-07-07 13:06
This has nothing to do with how you installed instant client, you just have to configure the PostgreSQL startup process.
You still didn't show me the script used to start PostgreSQL.

With `pg_ctl`, you could simple export the environment variable in its environment:

``` bash
export ORACLE_HOME=/home/postgres/oracle/instantclient_11_2
pg_ctl start ...
```

**Comment by houzi1099857978** [comment] 2020-07-07 13:10
the cluster can started by the following commend:
service corosync start;service pacemaker start
crm configure load update pgsql.crm`

the pgsql.crm like this:

[script.zip](https://github.com/laurenz/oracle_fdw/files/4885009/script.zip)

**Comment by laurenz** [comment] 2020-07-07 13:31
I would change the line

``` bash
ocf_run $quietrun $loglevel su $OCF_RESKEY_pgdba -c "cd $OCF_RESKEY_pgdata; $*"
```

to

``` bash
export ORACLE_HOME=/home/postgres/oracle/instantclient_11_2
export TNS_ADMIN=/home/postgres/oracle/instantclient_11_2/network/admin
export LD_LIBRARY_PATH=/home/postgres/oracle/instantclient_11_2
ocf_run $quietrun $loglevel su --whitelist-environment=ORACLE_HOME,TNS_ADMIN,LD_LIBRARY_PATH $OCF_RESKEY_pgdba -c "cd $OCF_RESKEY_pgdata; $*"
```

Add all the environment variables you need.

**Comment by houzi1099857978** [comment] 2020-07-07 13:45
ok I will try it,thank you very mach!

**Comment by houzi1099857978** [comment] 2020-07-07 14:28
> I would change the line
> 
> ```shell
> ocf_run $quietrun $loglevel su $OCF_RESKEY_pgdba -c "cd $OCF_RESKEY_pgdata; $*"
> ```
> 
> to
> 
> ```shell
> export ORACLE_HOME=/home/postgres/oracle/instantclient_11_2
> export TNS_ADMIN=/home/postgres/oracle/instantclient_11_2/network/admin
> export LD_LIBRARY_PATH=/home/postgres/oracle/instantclient_11_2
> ocf_run $quietrun $loglevel su --whitelist-environment=ORACLE_HOME,TNS_ADMIN,LD_LIBRARY_PATH $OCF_RESKEY_pgdba -c "cd $OCF_RESKEY_pgdata; $*"
> ```
> 
> Add all the environment variables you need.

I tried,it doesn't work and cluster stoped,maybe the start script is too complex to add the environment varibles and I must stop the cluster ,that has high risk in product environment,is there any esay way to solve the problem?
```
$vi /usr/lib/ocf/resource.d/heartbeat/pgsql
    export ORACLE_HOME=/home/postgres/oracle/instantclient_11_2
    ocf_run $quietrun $loglevel $SU --whitelist-environment=ORACLE_HOME $OCF_RESKEY_pgdba -c "cd $OCF_RESKEY_pgdata; $*"
```

```
> * pgsql_start_0 on node2 'insufficient privileges' (4): call=49, status=complete, exitreason='Directory /home/postgres/pgdata/ is not writable by postgres',
>     last-rc-change='Tue Jul  7 18:17:10 2020', queued=0ms, exec=77ms
> * pgsql_start_0 on node3 'insufficient privileges' (4): call=35, status=complete, exitreason='Directory /home/postgres/pgdata/ is not writable by postgres',
>     last-rc-change='Tue Jul  7 18:17:10 2020', queued=0ms, exec=75ms
> * pgsql_start_0 on node1 'insufficient privileges' (4): call=40, status=complete, exitreason='Directory /home/postgres/pgdata/ is not writable by postgres',
>     last-rc-change='Tue Jul  7 18:17:10 2020', queued=0ms, exec=152ms
```

**Comment by laurenz** [comment] 2020-07-07 14:35
That was just a blind attempt on my side to fix that startup script.

You know the cause of the problem, so try and find someone who understands these scripts and how to correctly configure them.
The goal is just to set some environment variables, that should be possible.

**Comment by houzi1099857978** [comment] 2020-07-07 14:44
why i install the oracle-instantclient11.2-basiclite-11.2.0.4.0-1.x86_64.rpm,it works,what the defference between instantclient-basiclite-linux.x64-11.2.0.4.0.zip?

**Comment by laurenz** [comment] 2020-07-08 06:56
I am not sure, it should have the same problem.

Does PostgreSQL have the correct environment variables set when you use the RPM?

I assume you are on Linux, but what distribution?

**Comment by laurenz** [comment] 2020-08-10 12:55
Can I close the issue or is there anything left where I can help?

**Comment by houzi1099857978** [comment] 2020-08-10 13:04
yes，it worked by  oracle-instantclient11.2-basiclite-11.2.0.4.0-1.x86_64.rpm,install thank you very much!

**Closed** 2020-08-10 13:40 UTC
Labels: duplicate, installation, problem
