### ISSUE TITLE
oracle_fdw "Dropping" Rows

### ISSUE THREAD

**Issue by bsislow** [laurenz/oracle_fdw#235] opened 2018-02-06 21:36 UTC
All of a sudden - a few days ago - oracle_fdw started "dropping" rows - meaning rows being INSERTed into Oracle were missing from the Oracle side.

This process we've been using has been working for several months.

No application changes or data changes have occurred as far as we know.

We are executing an INSERT over FT every minute such as:

INSERT INTO FT WHERE ID > X and ID <= Y

If 100 rows exist on the source PG database, sometimes a few get dropped on the Oracle side and we might end up with 97 for the same ID range in Oracle - for example.

There are no jobs on the Oracle side that remove rows - unless they are over a day old. This would not affect any current runs where the rows are missing.

Can we turn some kind of debugging on with oracle_fdw to see what is going on?

What else do you need to know from us?

**Comment by bsislow** [comment] 2018-02-07 15:49
Current version information:

modelpgp=# select oracle_diag();
                         oracle_diag
--------------------------------------------------------------
 oracle_fdw 1.5.0, PostgreSQL 9.6.2, Oracle client 11.2.0.3.0
(1 row)

**Comment by laurenz** [comment] 2018-02-07 22:56
There is no `WHERE` clause to the `INSERT` statement.

Can you tell me the exact sequence of SQL statements that the application runs?

About debugging: You could set `log_min_error_statement = error` to see errors in SQL statements, and you can set it to `debug2` to get a lot of messages what oracle_fdw is doing.

It is hard to guess what is going on, but the most likely explanation for inserts &ldquo;getting lost&rdquo; is that the insert takes place in a transaction that is later rolled back.

**Comment by bsislow** [comment] 2018-02-08 16:36
I am not following your reply - the INSERT has two predicates - simply an ID range:
INSERT INTO FT WHERE ID > X and ID <= Y

The "replication" method from PG to Oracle simply maintains a checkpoint table...
bid = beginning ID
eid = end ID
1. obtain begin and end id from last run - should be the same
2. obtain the max(id) from the pg table being "replicated"
3. insert bid to max(id) into oracle
4. update checkpoint table to make end=max(id) and bid=previous eid

we can probably try setting debug2 as the error level.

is there anything else we can check?

we realize this is difficult to debug but the process is relatively straightforward. we were just taken off guard as this started happening all of a sudden with no apparent changes.

i also forgot to mention that the table being inserted into in oracle has no constraints or indexes. it is very basic.

**Comment by laurenz** [comment] 2018-02-08 21:10
An `INSERT` cannot have any predicates, period. Maybe you mean

    INSERT INTO ...
    SELECT ... WHERE ...

Helping is so much easier with accurate information.

I cannot understand your replication procedure:

- Why do you store a *begin ID* in the checkpoint table?

- It looks like every row gets replicated *twice* - or should that be &ldquo;*eid* to max(id)&rdquo; in step 3?

**Comment by bsislow** [comment] 2018-02-08 22:34
correct, we are doing an INSERT INTO... SELECT WHERE ID > X and ID <=Y. sorry for the confusion.

your other point is also correct - but we store the begin ID just in case there is a disconnect and the process fails. the process is restartable.

perhaps postgres isn't understanding something that's coming over in the data stream via the foreign table?

**Comment by laurenz** [comment] 2018-02-09 15:51
Say `bid` is 10 and `eid` is 20. Then everything up to 20 has already been replicated. Now say `max(id)` is 30. Then you replicate 10 to 30 in step 3 and remember 20 and 30 in step 4.

So 10 to 20 have been replicated a second time, and 20 to 30 will be replicated a second time in the next round.

This seems wrong, right?

Do you get any error messages?

**Comment by bsislow** [comment] 2018-02-09 16:02
ok i must be explaining this wrong. please do not focus on the replication process. this has been working successfully since october 2017. in the last week, rows have gone missing from oracle when inserted via FT using oracle_fdw.

i will explain the process with an example, but again, the begin and end id is not the issue here.

also, we DO NOT have duplicate data in oracle. we have a daily check on this.

we also have a daily check in oracle and find a matching row count in oracle and postgres.

here is the "replication" process re-explained; i believe i was misspoken in my earlier post regarding the steps...

0. the bid and eid should be the same to start with. let's call both:

bid = 100
and
eid = 100

1. update checkpoint table with max value of table in pg

update checkpoint set eid = (select max(id) from sourcetable)

so here we have, for example:
bid = 100
and
eid = 150

2. insert into the foreign table/oracle table which has NO indexes to prevent ORA-08177

insert into oracle_foreign_table select a,b,c,d from sourcetable where id > (select bid from checkpoint) and id <= (select eid from checkpoint)

3. if insert is successful, we update checkpoint as follows. if it fails, we STOP and issue error email

update checkpoint set bid = eid

now we have:
bid=150
and
eid=150

does this make sense now? i think i missed how bid is updated during every run.

we also log the values from checkpoint in intermediate steps not covered above as they are just "informational." i wanted to simply cover the functional steps above.

we run this every minute. if it overlaps, it skips a run. if it runs for "too long," we issue an error email.

this inserts anywhere from 500 to 1500 rows per minute which is very low volume.

we have not made an adjustment for the logging level yet. i am going to enable DEBUG2 for a while then disable it as it may present too much logging over time.

thanks,.

**Comment by bsislow** [comment] 2018-02-09 16:06
debug2 is now enabled. please let us know what you would looking for.

we cannot post the log content here as the data cannot be public.

**Comment by laurenz** [comment] 2018-02-10 16:24
Thanks for the explanation, it is much clearer now. I was asking for details, because a mistake in the procedure might be the cause of the problem.

Can you tell me how transactions are handled? Do you call `BEGIN` and `COMMIT` explicitly (when?), or does the `INSERT ... SELECT ...` run in its own transaction?

You should be looking for rollbacks and errors in your log.

Another idea I have it to add a trigger `AFTER INSERT` on the foreign table that logs which rows were inserted in Oracle. Then you can compare the values in the logging table and the values in Oracle; that might give you a clue.

**Comment by bsislow** [comment] 2018-02-10 16:40
INSERT...SELECT... is called in it's own transaction. Here is the pseudocode:

`psql -a -U username -d dbname -p 5432 -c "insert into foreign_table select a,b,c,d from source_pg_table where id > (select bid from checkpoint) and id <= (select eid from checkpoint)"`

There are no ROLLBACKs in the last 24 hours with DEBUG2 level on but we've logged some missing rows over that course of time.

We will try the AFTER INSERT trigger this coming week. That is a good idea to reconcile rows which may be missing. We are also logging rows in Oracle that were not transported and we have a 2nd job which retries successfully. Yes, it's redundant but it works. So far, the secondary job has not dropped any rows...

**Comment by laurenz** [comment] 2018-02-10 16:43
Can you find the debug messages around the time of the missing rows and analyze them to see what oracle_fdw did?

**Comment by bsislow** [comment] 2018-02-12 17:34
we need to make a few improvements to track the missing rows. please leave this open while we add these enhancements. i will update.

**Comment by laurenz** [comment] 2018-02-13 06:02
Sure. I tend to close issues after about a month of inactivity, but I am warned.

**Comment by bsislow** [comment] 2018-02-27 15:22
This was transient. It looks like bad data was being inserted that was not compatible with PG. The issue has not recurred since 2/14.

**Comment by laurenz** [comment] 2018-02-27 15:26
Shall we close the issue?

**Closed** 2018-02-27 15:42 UTC
Labels: problem
