### ISSUE TITLE
Issue in make in cygwin in windows ?

### ISSUE THREAD

**Issue by awesomehimanshu** [laurenz/oracle_fdw#165] opened 2017-05-17 11:28 UTC
/usr/lib/gcc/x86_64-pc-cygwin/5.4.0/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lclntsh
collect2: error: ld returned 1 exit status
make: *** [/usr/lib/postgresql/pgxs/src/makefiles/../../src/Makefile.shlib:367: oracle_fdw.dll] Error 1

I have set all the path

13  echo $PATH;
   14  echo $PGHOME;
   15  export PGHOME=/cygdrive/c/PostgreSQL
   16  echo $PGHOME;
   17  export PGLIB=$PGHOME/lib
   18* echo
   19  export LD_LIBRARY_PATH=$PGLIB:/cygdrive/c/oracle/instantclient_12_2
   20  export ORACLE_HOME=/cygdrive/c/oracle/instantclient_12_2

**Comment by laurenz** [comment] 2017-05-17 12:43
Duplicate of #164.

**Closed by laurenz** 2017-05-17 12:43 UTC
Labels: duplicate
