### ISSUE TITLE
oracle_fdw.c:1001:13: error: ‘RelOptInfo’ has no member named ‘lateral_relids’

### ISSUE THREAD

**Issue by svenkirsten** [laurenz/oracle_fdw#397] opened 2020-05-13 14:42 UTC
Hi laurenz, 

I got the same error an other user hit also 1 year ago. 
I've check already my installed PostgreSQL version : 

` postgres=# SELECT version();`
                                                 `version`
`---------------------------------------------------------------------------------------------------------`
 `PostgreSQL 12.2 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit (1 row)`

`postgres=#`

and 

`[root@server57 oracle_fdw]# pg_config --version`
`PostgreSQL 9.2.24`
`[root@server57 oracle_fdw]#`

oracle_fdw version: 2.3.0

So the Server runs with 12.2 but the psql Client runs with version 9.2. 

So the compile process should run. 

... ? ....

**Comment by laurenz** [comment] 2020-05-13 20:18
This is a duplicate of #341.

The simplest solution is to uninstall all PostgreSQL 9.2 components.

If you cannot do that, you have to change the `PATH` environment variable so that v12's `pg_config` is found on the path first. Then the build will succeed.

**Comment by laurenz** [comment] 2020-05-29 05:51
Shall I close the issue or are you still having problems?

**Comment by svenkirsten** [comment] 2020-06-03 14:16
Yes - close it. I need to uninstall the PostgresSQL client components because they was too old, and reinstall it in the same version as the postgresql server.

**Closed** 2020-06-03 15:08 UTC
Labels: duplicate, installation, problem

**Comment by ravisql09** [comment] 2020-06-24 21:16
@laurenz ,Can you please help me with the following error,it seems you have already answered but I am not able to fallow the issue here.
Initially I got the error "lateral_relids". After Environment variables setup facing below problem.


root@postgr-11-15-1-251 oracle_fdw-master]# echo $PATH
PATH:/usr/bin:/usr/lib/oracle/19.6/client64/bin:/usr/lib/oracle/19.6/client64/bin
[root@postgr-11-15-1-251 oracle_fdw-master]# echo $ORACLE_HOME
/usr/lib/oracle/19.6/client64
[root@postgr-11-15-1-251 oracle_fdw-master]# echo $LD_LIBRARY_PATH
/usr/lib/oracle/19.6/client64/lib
[root@postgr-11-15-1-251 oracle_fdw-master]# make
gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fPIC -I/usr/lib/oracle/19.6/client64/sdk/include -I/usr/lib/oracle/19.6/client64/oci/include -I/usr/lib/oracle/19.6/client64/rdbms/public -I/usr/lib/oracle/19.6/client64 -I/usr/include/oracle/19.6/client -I/usr/include/oracle/19.6/client64 -I/usr/include/oracle/19.3/client -I/usr/include/oracle/19.3/client64 -I/usr/include/oracle/18.5/client -I/usr/include/oracle/18.5/client64 -I/usr/include/oracle/18.3/client -I/usr/include/oracle/18.3/client64 -I/usr/include/oracle/12.2/client -I/usr/include/oracle/12.2/client64 -I/usr/include/oracle/12.1/client -I/usr/include/oracle/12.1/client64 -I/usr/include/oracle/11.2/client -I/usr/include/oracle/11.2/client64 -I/usr/include/oracle/11.1/client -I/usr/include/oracle/11.1/client64 -I/usr/include/oracle/10.2.0.5/client -I/usr/include/oracle/10.2.0.5/client64 -I/usr/include/oracle/10.2.0.4/client -I/usr/include/oracle/10.2.0.4/client64 -I/usr/include/oracle/10.2.0.3/client -I/usr/include/oracle/10.2.0.3/client64 -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o oracle_utils.o oracle_utils.c
oracle_utils.c:22:1**7: fatal error: oci.h: No such file or directory**
 #include <oci.h>
                 ^
compilation terminated.
make: *** [oracle_utils.o] Error 1
