### ISSUE TITLE
 column "sys_timestamp" of foreign table "prdoperation_z_data_archive_log" cannot be converted to or from Oracle data type

### ISSUE THREAD

**Issue by qinghuiguo** [laurenz/oracle_fdw#361] opened 2019-12-09 10:20 UTC
Hi 

I got an ERROR like  this

    column "sys_timestamp" of foreign table "prdoperation_z_data_archive_log" cannot be converted to or from Oracle data type 

The data type of `sys_timestamp` is  "date" in oracle, and data type is "timestamp without time zone" in PostgreSQL.

In the test environment, it's OK, but in prod environment I got the error, I am confused.

My table struncure:

```
                   Foreign table "public.prdoperation_z_data_archive_log"
     Column     |            Type             | Collation | Nullable | Default | FDW options 
----------------+-----------------------------+-----------+----------+---------+-------------
 target_schema  | character varying(30)       |           |          |         | 
 target_table   | character varying(30)       |           |          |         | 
 partition_type | character varying(30)       |           |          |         | 
 partition_name | character varying(100)      |           |          |         | 
 archive_type   | character varying(30)       |           |          |         | 
 archive_time   | timestamp without time zone |           |          |         | 
 status         | character varying(20)       |           |          |         | 
 sys_timestamp  | timestamp without time zone |           |          |         | 
Server: prdmdmn_oracle
FDW options: (schema 'PRDOPERATION', "table" 'Z_DATA_ARCHIVE_LOG')
```

In oracle:

```
 Name                                                                     Null?    Type
 ------------------------------------------------------------------------ -------- -------------------------------------------------
 TARGET_SCHEMA                                                                     VARCHAR2(30)
 TARGET_TABLE                                                                      VARCHAR2(30)
 PARTITION_TYPE                                                                    VARCHAR2(30)
 PARTITION_NAME                                                                    VARCHAR2(100)
 ARCHIVE_TYPE                                                                      VARCHAR2(30)
 ARCHIVE_TIME                                                                      DATE
 STATUS                                                                            VARCHAR2(20)
 MESSAGE                                                                           VARCHAR2(500)
 SYS_TIMESTAMP                                                                     DATE
```

**Comment by qinghuiguo** [comment] 2019-12-09 12:24
Hi 
    I seem to have found the cause, but it confuses me even more.

The only difference is the order of the fields in the Oracle database，and I did an expirement.

For example:

>The foreign tables are same  in postgres

>I got the data type  error using following SQL to create table in oracle database.

create table  Z_DATA_ARCHIVE_LOG
(
  target_schema  VARCHAR2(30),
  target_table   VARCHAR2(30),
  partition_type VARCHAR2(30),
  partition_name VARCHAR2(100),
  archive_type   VARCHAR2(30),
  archive_time   DATE,
  status         VARCHAR2(20) default 'new',
>  sys_timestamp  DATE default sysdate ,
>  message        VARCHAR2(500)
);

> But it's ok  when I create table using the folowing SQL  in oracle.

create table DATA_ARCHIVE_LOG
(
  target_schema  VARCHAR2(30),
  target_table   VARCHAR2(30),
  partition_type VARCHAR2(30),
  partition_name VARCHAR2(100),
  archive_type   VARCHAR2(30),
  archive_time   DATE,
  status         VARCHAR2(20) default 'new',
>  message        VARCHAR2(500),
> sys_timestamp  DATE default sysdate 
);

**Comment by laurenz** [comment] 2019-12-09 14:48
This is a duplicate of #210.

In oracle_fdw, columns are not matched by name, but by position.
So the foreign table must be defined with the columns in the same order as in the Oracle table.

**Comment by qinghuiguo** [comment] 2019-12-10 00:18
Thank you for your patience to answer.

**Comment by laurenz** [comment] 2019-12-10 05:40
You are most welcome.

**Closed by laurenz** 2019-12-10 05:40 UTC
Labels: duplicate, problem
