### ISSUE TITLE
Cant set isolation level

### ISSUE THREAD

**Issue by hisahin** [laurenz/oracle_fdw#420] opened 2020-08-27 14:04 UTC
Hi,

When i set isolation_level, i get an error.

Can you help me?

```
postgres=# create server sahin foreign data wrapper oracle_fdw OPTIONS ( dbserver 'ibrahim', isolation_level 'read_committed');
ERROR:  invalid option "isolation_level"
HINT:  Valid options in this context are: dbserver
postgres=# alter server oracle options ( set isolation_level 'read_only');
ERROR:  option "isolation_level" not found
postgres=# alter server oracle options ( add isolation_level 'read_only');
ERROR:  invalid option "isolation_level"
HINT:  Valid options in this context are: dbserver
postgres=# select oracle_diag();
                         oracle_diag                         
-------------------------------------------------------------
 oracle_fdw 2.2.0, PostgreSQL 12.3, Oracle client 18.5.0.0.0
```

Centos 8.1.1911

**Comment by laurenz** [comment] 2020-08-27 14:29
This is a duplicate of #401.

If you insist on the `isolation_level` option, you'll have to use the latest development version rather than 2.2.0.

**Comment by laurenz** [comment] 2020-09-24 06:55
Version 2.3.0, which supports the new feature, has been released today.

**Closed by laurenz** 2020-09-24 06:55 UTC
Labels: duplicate, problem
