### ISSUE TITLE
oracle_fdw compile error

### ISSUE THREAD

**Issue by Rumyuqiang** [laurenz/oracle_fdw#384] opened 2020-03-20 09:27 UTC
Dear all,

When I execute 'make' command in directory oracle_fdw,I got errors below:

oracle_fdw.c: In function ‘oracleIterateForeignScan’:
oracle_fdw.c:1479:31: error: ‘TupleTableSlot’ has no member named ‘tts_values’
   convertTuple(fdw_state, slot->tts_values, slot->tts_isnull, false);
                               ^
oracle_fdw.c:1479:49: error: ‘TupleTableSlot’ has no member named ‘tts_isnull’
   convertTuple(fdw_state, slot->tts_values, slot->tts_isnull, false);
                                                 ^
oracle_fdw.c: In function ‘oracleExecForeignInsert’:
oracle_fdw.c:2042:31: error: ‘TupleTableSlot’ has no member named ‘tts_values’
   convertTuple(fdw_state, slot->tts_values, slot->tts_isnull, false);
                               ^
oracle_fdw.c:2042:49: error: ‘TupleTableSlot’ has no member named ‘tts_isnull’
   convertTuple(fdw_state, slot->tts_values, slot->tts_isnull, false);
                                                 ^
oracle_fdw.c: In function ‘oracleExecForeignUpdate’:
oracle_fdw.c:2092:31: error: ‘TupleTableSlot’ has no member named ‘tts_values’
   convertTuple(fdw_state, slot->tts_values, slot->tts_isnull, false);
                               ^
oracle_fdw.c:2092:49: error: ‘TupleTableSlot’ has no member named ‘tts_isnull’
   convertTuple(fdw_state, slot->tts_values, slot->tts_isnull, false);
                                                 ^
oracle_fdw.c: In function ‘oracleExecForeignDelete’:
oracle_fdw.c:2142:31: error: ‘TupleTableSlot’ has no member named ‘tts_values’
   convertTuple(fdw_state, slot->tts_values, slot->tts_isnull, false);
                               ^
oracle_fdw.c:2142:49: error: ‘TupleTableSlot’ has no member named ‘tts_isnull’
   convertTuple(fdw_state, slot->tts_values, slot->tts_isnull, false);
                                                 ^
make: *** [oracle_fdw.o] Error 1

**Comment by laurenz** [comment] 2020-03-20 10:57
That is unexpected - `TupleTableSlot` has had these members ever since commit f97aebd162987d00bd9b9f592ff54e9e90f11843 from 2005-03-16, and you cannot be running a 15 year old PostgreSQL version, since that was way before foreign data wrappers were introduced.

So please tell me which exact version of PostgreSQL and oracle_fdw you are using and how exactly you installed PostgreSQL.

**Comment by Rumyuqiang** [comment] 2020-03-23 05:29
I installed the greenplum 6.1, postgreSQL is 9.4.24.

**Comment by laurenz** [comment] 2020-03-23 12:04
Well, looks like Greenplum is different enough from PostgreSQL that you cannot use PostgreSQL extensions with it. That's not surprising, since it forked in 2005, lang before foreign data wrappers came into being.

The definition of `TupleTableSlot` in `src/include/executor/tuptable.h` must be different.

Looks like you cannot use oracle_fdw with Greenplum.

**Comment by laurenz** [comment] 2020-03-23 12:06
This is a duplicate of #354.

**Closed by laurenz** 2020-03-23 12:06 UTC
Labels: installation, problem
