### ISSUE TITLE
Foreign tables update issue

### ISSUE THREAD

**Issue by Muhammad112233** [laurenz/oracle_fdw#362] opened 2019-12-17 13:07 UTC
Hello brother, 
I'm currently leading a project on migration from oracle to postgres and the company heavily depends upon dblinks. Oracle_fdw is a great tool but here is the problem.
when i update a foreign table, we can see the DML changes in the oracle table. But when we do DML operations in oracle table, they are not reflected in the postgresql foreign table which is a serious issue.
Can you please look into this. 
Thanks

**Comment by laurenz** [comment] 2019-12-17 13:53
This is working as expected, and the PostgreSQL FDW API has no provisions for changing the definition of a foreign table automatically. In fact, it couldn't do that, since it is not notified when the remote definitions change.

An Oracle database link works different from a PostgreSQL foreign table: it just points to a foreign server, so it does not store any local information about the foreign tables.

You will have to modify the foreign tables whenever you modify the remote Oracle tables.

**Comment by srehmann** [comment] 2019-12-18 17:28
Hi laurenz
You are right that the table definition cannot be changed, but how about if we add some records in foreign oracle table, as per my understanding,  it should give me complete updated records at pg side? So its not about the schema changes but the record insertion or updation. Pls comment.

**Comment by laurenz** [comment] 2019-12-19 07:58
If the foreign table has two columns, every `SELECT` on that table will return two columns, no matter how many columns the Oracle table has. There is no way to change that, it is how foreign tables work.

**Comment by srehmann** [comment] 2019-12-19 09:21
Exactly right laurenz. But we are not talking about column addition, but record insert (tuple addition)
Pls comment.

**Comment by laurenz** [comment] 2019-12-19 10:36
Oh. Do you mean that you make data modifications in Oracle, but cannot see them in PostgreSQL?

Then you forgot to `COMMIT` the Oracle transaction.

**Comment by srehmann** [comment] 2019-12-19 11:13
Hmm.. We need to check this at our end. So, there's no issue of data sync from Oracle to PG, right?

**Comment by srehmann** [comment] 2019-12-19 11:14
Yup, we meant data modifications, that's y DML in first comment :)

**Comment by laurenz** [comment] 2019-12-19 11:24
Data are not synchronized between PostgreSQL and Oracle.
Every query in PostgreSQL runs a `SELECT` in Oracle.

**Comment by laurenz** [comment] 2019-12-19 11:27
Duplicate of #252.

**Comment by srehmann** [comment] 2019-12-19 11:57
Cool. Thx Laurenz.

**Closed** 2020-01-28 11:30 UTC
Labels: question
