### ISSUE TITLE
serialization error for multiple inputs

### ISSUE THREAD

**Issue by DFuster** [laurenz/oracle_fdw#66] opened 2016-03-11 18:49 UTC
I have a project where we use several FOREIGN tables in oracle (oracle_fdw) when we made a data entry (input) for 10 stations, results in an error message serialization, could indicate the best method or way to avoid this error?

Thanks

Dante Fuster

**Comment by laurenz** [comment] 2016-03-12 13:00
Could it be this problem described in the README?

> Serialization errors
> --------------------
> 
> In Oracle 11.2 or above, inserting the first row into a newly created
> Oracle table with oracle_fdw will lead to a serialization error.
> 
> This is because of an Oracle feature called "deferred segment creation" which
> defers allocation of storage space for a new table until the first row
> is inserted.  This causes a serialization failure with serializable
> transactions (see document 1285464.1 in Oracle's knowledge base).
> 
> This is no serious problem; you can work around it by either ignoring that
> first error or creating the table with "SEGMENT CREATION IMMEDIATE".

**Comment by DFuster** [comment] 2016-03-16 17:15
My problem is when performing operations inserts from different workstations to the foreign table, sometimes returns an error message is SERIALIZATION ERROR,

**Comment by laurenz** [comment] 2016-03-17 06:50
That is normal, in a way.

To update or delete from a foreign table, PostgreSQL first scans the remote table and then modifies some of the rows found during the scan (see the EXPLAIN output).
To make sure that scan and modification see the same data, the whole thing has to be wrapped in a SERIALIZABLE transaction.

Now if the Oracle table is modified concurrently by other sessions, it can happen that such a modification takes place between the scan and the update in oracle_fdw's serializable transaction.
This leads to a serialization error like you describe.

Does this explain what you experience?

If yes, your only bet is to

- make transactions involving oracle_fdw as short as possible
- reduce concurrency as much as possible
- write your code so that it retries transaction that failed because of a serialization error

I apologize for the inconvenience.

**Comment by DFuster** [comment] 2016-03-17 15:56
Thanks, this helps me a lot to see procedures to solve the problem
:+1:

**Comment by laurenz** [comment] 2016-03-18 06:59
While sleeping over it I realized that what I told you is not true; apologies for my bad memory.

During the scan for a data modification oracle_fdw uses SELECT &hellip; FOR UPDATE, so the scanned rows are locked and nobody can modify them between the scan and the data modification.

So it seems like there must be something else going on there.

Could you describe your problem in more detail?

- Do you use transactions that contain more than one DML statement involving oracle_fdw?
- Can you reproduce the problem or does it only happen intermittently (race condition)?
- Do you get the serialization error from PostgreSQL or from Oracle (is there an ORA-* error message)?
- Anything else that might help us to understand what is going on.

**Comment by laurenz** [comment] 2016-03-24 21:41
The only way I can imagine that you can get such an error in oracle_fdw would be if you have a PostgreSQL transaction that involves a foreign table, where the table is read first and updated later in the same transaction.

Is that what you are dealing with?
If yes, you could consider using SELECT &hellip; FOR UPDATE in PostgreSQL, that should avoid the problem.

**Comment by DFuster** [comment] 2016-03-28 01:51
I will try to implement these recommendations, as have the result I'll be
communicating,

thank you very much

Este correo electrónico se ha enviado desde un equipo libre de virus y
protegido por Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2016-03-24 16:41 GMT-05:00 Laurenz Albe <notifications@github.com>:

**Comment by DFuster** [comment] 2016-04-04 15:46
good morning, Thanks  for your atention.

I was running tests on their instructions, some problems UPDATE was
resolved but
others maintained, specifically because there is a group of operations that
consist of multiple INSERTS (through a loop) that I solve them write to a
temporary table and later  performed a COPY ....  and 2 final INSERTS avoiding
the problem of serialization error, however when running this from 4 or 5
stations almost simultaneously, sometimes displayed serialization error. there
would be a way to solve it?

regards

Dante Fuster

2016-03-27 20:51 GMT-05:00 Dante Fuster <dante.fuster@gmail.com>:

**Comment by laurenz** [comment] 2016-04-04 15:58
What you write doesn't tell me enough to be certain what causes the serialization errors in your case.
You cannot use COPY with a foreign table.
If you describe the problematic operations in more detail, I can try and guess what's going on.

If you run concurrent transactions with oracle_fdw that each contain more than one statement modifying Oracle data, serialization errors can be expected.
If an application receives a serialization error, it should retry the transaction.
Of course one would try to keep such errors to a minimum.

**Comment by DFuster** [comment] 2016-04-04 16:17
Sorry, my mistake,  i dont use COPY , i execute multiples  INPUT in
temporal tables, and later use:

insert into ruteo.foraiegn_table select *  from ruteo.temporal_table  where
condition;

and two INSERTS more, the aplication execute in 5 stations.

y try to use transactions to avoid serialization error

Thanks

Este correo electrónico se ha enviado desde un equipo libre de virus y
protegido por Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2016-04-04 10:58 GMT-05:00 Laurenz Albe <notifications@github.com>:

**Comment by laurenz** [comment] 2016-04-04 16:20
Using INSERTs like this should result in several individual INSERT statements in Oracle, so it shouldn't make any difference if you use one ore more PostgreSQL statement to insert several Oracle rows.

**Comment by laurenz** [comment] 2016-05-10 14:36
I'll close this issue, reopen it if you need more help with this.

**Closed by laurenz** 2016-05-10 14:36 UTC
Labels: problem
