### ISSUE TITLE
crash in oracle_fdw 2.1.0

### ISSUE THREAD

**Issue by Jaime2ndQuadrant** [laurenz/oracle_fdw#279] opened 2018-10-15 13:59 UTC
I have been running sqlsmith on postgres with oracle_fdw (2.1.0) and found a crash. I reduced the example as much as i could and i was able to reproduce it from 9.6 upto master (didn't try with other versions).
To reproduce it:
1. Install Oracle XE and unlock schema HR
2. compile and install postgres and oracle_fdw
3. create extension oracle_fdw;
4. CREATE SERVER oradb FOREIGN DATA WRAPPER oracle_fdw OPTIONS (dbserver '');
5. GRANT USAGE ON FOREIGN SERVER oradb TO postgres;
6. CREATE USER MAPPING FOR postgres SERVER oradb OPTIONS (user 'HR', password 'passwd');
7. IMPORT FOREIGN SCHEMA "HR" FROM SERVER oradb INTO public;
8. execute query in query_crash.txt (attached)

I also attached the stack trace of the crash. Let me know if i can help debugging this in any other way.

[gdb.txt](https://github.com/laurenz/oracle_fdw/files/2478946/gdb.txt)

[query_crash.txt](https://github.com/laurenz/oracle_fdw/files/2478953/query_crash.txt)

**Comment by laurenz** [comment] 2018-10-15 14:21
Thanks for the test and the report!

Since I don't have the HR schema around, would you mind sending me the `CREATE TABLE` statements?

**Comment by Jaime2ndQuadrant** [comment] 2018-10-15 15:32
i'm not very knowledgable about Oracle so i'm not sure how i get that, what i did was to export the whole schema with /u01/app/oracle/product/11.2.0/xe/bin/exp
It's a small schema (it comes pre-installed with express edition)
Just unzip it and restore it with imp utility.
User HR has password 'oraclexe'

let me know if this is what you need or how to get a sql script with CREATE objects and rows of those objects

[expdat.dmp.zip](https://github.com/laurenz/oracle_fdw/files/2479390/expdat.dmp.zip)

**Comment by laurenz** [comment] 2018-10-16 13:45
I have been trying to reduce the query as much as possible and have been able to come up with a similar query using our regression test table that also crashes:

    SELECT 1
    FROM typetest1 a
       LEFT JOIN typetest1 b
       ON (a.id IS NOT NULL)
    WHERE (a.c = a.vc)
        = (b.id IS NOT NULL);

The error happens in `a.c = a.vc`, but so far I have not been able to figure out what is going on.

@yamatattsu, can you see if you can figure out something?
The query does not crash if I replace the outer join with an inner join.

**Comment by laurenz** [comment] 2018-10-17 09:43
Thanks for the new information.

I'll see if I can make any progress with that.

**Comment by laurenz** [comment] 2018-10-17 13:20
I just build 10.4 and 10.5 from source, and the query crashed both of them.

**Comment by laurenz** [comment] 2018-10-17 13:33
Ah, I have a lead:

                                                                   QUERY PLAN                                                                
    -----------------------------------------------------------------------------------------------------------------------------------------
     Foreign Scan  (cost=10000.00..20000.00 rows=1000 width=4)
       Filter: ((c = (vc)::bpchar) = (id IS NULL))
       Oracle query: SELECT /*a573aba54b7dccf91e19e6dff41baef2*/ '1' FROM ("TYPETEST1" r1 LEFT JOIN "TYPETEST1" r2 ON (r1."ID" IS NOT NULL))
    (3 rows)

The problem is clearly that the Oracle query has `SELECT '1'` rather than `SELECT r2."ID", r1."C", r1."VC"`. The columns would have to be fetched for the filter to work.

**Comment by Jaime2ndQuadrant** [comment] 2018-10-17 15:36
> The problem is clearly that the Oracle query has SELECT '1' rather than SELECT r2."ID", r1."C", r1."VC". The columns would have to be fetched for the filter to work.

right, you need at least a.c and a.vc for the query to work:
`
SELECT a.c, a.vc
FROM typetest1 a
   LEFT JOIN typetest1 b
   ON (a.id IS NOT NULL)
WHERE (a.c = a.vc)
    = (b.id IS NOT NULL);
`

btw, in a maybe non-related failure i got an ERROR when trying to explain analyze that last query:
`
postgres=# explain (analyze, verbose) SELECT a.c, a.vc      
FROM typetest1 a
   LEFT JOIN typetest1 b
   ON (a.id IS NOT NULL)
WHERE (a.c = a.vc)
    = (b.id IS NOT NULL);
ERROR:  no SELECT privilege on V$SQL in the remote database
DETAIL:  ORA-00942: table or view does not exist
`

**Comment by laurenz** [comment] 2018-10-18 06:57
Jaime, that last error message is covered by the README:

> For EXPLAIN VERBOSE the user will also need SELECT privileges on V$SQL and
> V$SQL_PLAN.

**Comment by laurenz** [comment] 2018-10-18 14:53
The problem is in `oracleGetForeignPlan` and `build_join_oratable`.

In `oracleGetForeignPlan`, we build `fdw_scan_tlist`, which seems to contain exactly the three `TargetEntry`s we need.

But rather than passing `fdw_scan_tlist` to `build_join_oratable`, we pass `foreignrel->reltarget` which does not contain them.

@yamatattsu, this is a bit above my head. I'll let you have a go at it (whenever you find the time).

Maybe I broke something in 1e53ada3b978b2f300b4aa4b2b6d7971228bf6f7...

**Comment by Jaime2ndQuadrant** [comment] 2019-01-03 04:17
is there any advance on this? i can try to do something but this is not at my level i will be like a monkey trying to write a coherent phrase on a keyboard ;)

**Comment by yamatattsu** [comment] 2019-01-07 10:41
Hi All,

Oops, above investigation is wrong, probably.
Because I forgot to create fdwState->where_clause for OUTER join in foreign_join_ok().

I'll check oracleGetForeignPlan and build_join_oratable tomorrow.

Thanks,

**Comment by yamatattsu** [comment] 2019-01-08 09:21
I wonder why there is no error after Explain command execution.
Following [A] is crashed but [B] is not crashed. Hmm...

[A]

	$ psql
	# SELECT 1
	...
	server closed the connection unexpectedly
	        This probably means the server terminated abnormally
	        before or while processing the request.
	@:!> \q

[B]

	$ psql
	# explain SELECT 1
	...
	                                                               QUERY PLAN
	-----------------------------------------------------------------------------------------------------------------------------------------
	 Foreign Scan  (cost=10000.00..20000.00 rows=1000 width=4)
	   Filter: ((c = (vc)::bpchar) = (id IS NOT NULL))
	   Oracle query: SELECT /*a573aba54b7dccf91e19e6dff41baef2*/ '1' FROM ("TYPETEST1" r1 LEFT JOIN "TYPETEST1" r2 ON (r1."ID" IS NOT NULL))
	(3 rows)

	# SELECT 1
	...
	 ?column?
	----------
	(0 rows)

**Comment by yamatattsu** [comment] 2019-01-09 03:00
Hi,

I checked oraTable and fdw_scan_tlist by using debugger. I share my results to you. :)

The results are:
  * oraTable was not made from foreignrel->reltarget because reltarget has no exprs.
    See below [1] and [3].
  * fdw_scan_tlist was maybe Okay because there were three elements in the list such as
    (varno, varattno) = (1,3), (1,5) and (2,1). See below [2].

Therefore, 
  We have to check why exprs in foreignrel->reltarget are empty when the query executed.

[Query]

	SELECT 1
	FROM typetest1 a
	   LEFT JOIN typetest1 b
	   ON (a.id IS NOT NULL)
	WHERE (a.c = a.vc)
	    = (b.id IS NOT NULL);

[Breakpoints]

	b oracleGetForeignPlan
	b oracle_fdw.c:1189
	b oracle_fdw.c:3293

[Breakpoint 1]

	Breakpoint 1, oracleGetForeignPlan (root=0x1e98860, foreignrel=0x1eb1978, foreigntableid=0, best_path=0x1f8ddb0, tlist=0x1f8f5e8, scan_clauses=0x0,
	    outer_plan=0x0) at oracle_fdw.c:1099
	1099            struct OracleFdwState *fdwState = (struct OracleFdwState *)foreignrel->fdw_private;
	(gdb) p *foreignrel->reltarget
	$1 = {type = T_PathTarget, exprs = 0x0, sortgrouprefs = 0x0, cost = {startup = 0, per_tuple = 0}, width = 0}

[Breakpoint 2]

	Breakpoint 2, oracleGetForeignPlan (root=0x1e98860, foreignrel=0x1eb1978, foreigntableid=0, best_path=0x1f8ddb0, tlist=0x1f8f5e8, scan_clauses=0x0,
	    outer_plan=0x0) at oracle_fdw.c:1189
	1189                    if (outer_plan)
	(gdb) p *fdw_scan_tlist
	$2 = {type = T_List, length = 3, head = 0x1f8f780, tail = 0x1f8f968}

	(gdb) p *(Var *)((TargetEntry *)fdw_scan_tlist->head->data->ptr_value)->expr
	$3 = {xpr = {type = T_Var}, varno = 1, varattno = 3, vartype = 1042, vartypmod = 14, varcollid = 100, varlevelsup = 0, varnoold = 1, varoattno = 3,
	  location = 84}

	(gdb) p *(Var *)((TargetEntry *)fdw_scan_tlist->head->next->data->ptr_value)->expr
	$4 = {xpr = {type = T_Var}, varno = 1, varattno = 5, vartype = 1043, vartypmod = 14, varcollid = 100, varlevelsup = 0, varnoold = 1, varoattno = 5,
	  location = 90}

	(gdb) p *(Var *)((TargetEntry *)fdw_scan_tlist->head->next->next->data->ptr_value)->expr
	$5 = {xpr = {type = T_Var}, varno = 2, varattno = 1, vartype = 23, vartypmod = -1, varcollid = 0, varlevelsup = 0, varnoold = 2, varoattno = 1,
	  location = 103}

[Breakpoint 3]

	Breakpoint 3, build_join_oratable (fdwState=0x1eb1648, reltarget=0x1f8db58) at oracle_fdw.c:3293
	3293            oraTable->npgcols = oraTable->ncols;
	(gdb) p *reltarget
	$6 = {type = T_PathTarget, exprs = 0x0, sortgrouprefs = 0x0, cost = {startup = 0, per_tuple = 0}, width = 0}
	(gdb) p *oraTable
	$7 = {name = 0x1f8f9c8 "", pgname = 0x1f8f9e8 "", ncols = 0, npgcols = 0, cols = 0x1f8fa08}
	(gdb) p *oraTable->cols
	$8 = (struct oraColumn *) 0x0

**Comment by yamatattsu** [comment] 2019-01-09 05:47
Hi Laurenz and Jaime2ndQuadrant,

I realized foreignrel->reltarget which is given form PostgreSQL core is empty sometimes.
However, build_join_oratable() expects it is not empty and create oraTable. So, not suitable oraTable causes the SIGSEGV, I suppose.

To fix, I replaced the parameter with fdw_scan_tlist because fdw_scan_tlist contains all colmuns in the query. And It seems that the fix works fine since creating suitable oraTable by using fdw_scan_tlist.
Also regression test oracle_join.sql is fine. :)

I commited the patch, if possible, could you check and try the patch? 839b125e1bdc63b71220ccd675fa852c028de9ea

Regards,
Tatsuro Yamada

**Comment by Jaime2ndQuadrant** [comment] 2019-01-09 20:16
Hi @yamatattsu 

I still haven't tested your patch, but it makes sense... actually i got the same conclusion just wasn't able to code it...

will test the patch later today, thanks

**Comment by laurenz** [comment] 2019-01-10 12:20
Thank you!
That looks exactly what I had in mind.
I didn't realize there was that little to change in `build_join_oratable`!

Could you add my crasher query from above to the regression tests?

**Comment by yamatattsu** [comment] 2019-01-10 12:35
>
> Hi Laurenz!

> Could you add my crasher query from above to the regression tests?
>

Sure. I'll do that tomorrow, maybe. :)


Regards,
Tatsuro Yamada

**Comment by yamatattsu** [comment] 2019-01-15 01:43
Hi Laurenz!

I created following regression test. Is it fine with you?
If it's okay, I'll commit it with expected/oracle_join.out.

	diff --git a/sql/oracle_join.sql b/sql/oracle_join.sql
	index 4ce1484..d653ed8 100644
	--- a/sql/oracle_join.sql
	+++ b/sql/oracle_join.sql
	@@ -57,6 +57,16 @@ SELECT t1.id, t2.id FROM typetest1  t1 RIGHT JOIN typetest1  t2 ON t1.d = t2.d W
	 EXPLAIN (COSTS off)
	 SELECT t1.id, t2.id FROM typetest1  t1 FULL  JOIN typetest1  t2 ON t1.d = t2.d WHERE t1.id > 1 ORDER BY t1.id, t2.id;
	 SELECT t1.id, t2.id FROM typetest1  t1 FULL  JOIN typetest1  t2 ON t1.d = t2.d WHERE t1.id > 1 ORDER BY t1.id, t2.id;
	+---- left outer join with WHERE clause but foreignrel->reltarget is empty (Issues #279)
	+CREATE TABLE typetest1_bak AS SELECT * FROM TYPETEST1;
	+DELETE FROM typetest1;
	+INSERT INTO typetest1 VALUES (1, 'no', 'si', '0', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
	+EXPLAIN (COSTS off)
	+SELECT 1 FROM typetest1 t1 LEFT JOIN typetest1 t2 ON (t1.id IS NOT NULL) WHERE (t1.c = t1.vc) = (t2.id IS NOT NULL);
	+SELECT 1 FROM typetest1 t1 LEFT JOIN typetest1 t2 ON (t1.id IS NOT NULL) WHERE (t1.c = t1.vc) = (t2.id IS NOT NULL);
	+DELETE FROM typetest1;
	+INSERT INTO typetest1 select * from typetest1_bak;
	+DROP TABLE typetest1_bak;


Thanks,
Tatsuro Yamada

**Comment by laurenz** [comment] 2019-01-15 07:02
What about simply using my query from [here](#issuecomment-430243060)? Then we don't need an extra foreign table.

**Comment by Jaime2ndQuadrant** [comment] 2019-01-17 06:32
> Hi @yamatattsu
> 
> I still haven't tested your patch, but it makes sense... actually i got the same conclusion just wasn't able to code it...
> 
> will test the patch later today, thanks

at last i could test this (i cherry-picked this into 2.1.0) and it worked just fine, this will be backpatched to older branches with the same bug?

good work @yamatattsu and @laurenz

**Comment by laurenz** [comment] 2019-01-17 08:40
Thanks for checking.
I have pushed a regression test and a changelog entry, so we can close this one.
Thanks again to both of you!

oracle_fdw only has a single persistent branch, and the idea is that the master branch is always kept stable.
So you'd just upgrade to current git HEAD if you need the bug fix.
Releases are more or less just points of reference, whenever enough has changed and I can be bothered to build Windows binaries.

**Closed by laurenz** 2019-01-17 08:40 UTC
Labels: bug
