### ISSUE TITLE
error describing remote table: OCIStmtExecute failed to describe table

### ISSUE THREAD

**Issue by SrdanD** [laurenz/oracle_fdw#392] opened 2020-05-05 15:07 UTC
Getting this error in postgres intermittently, SQLSTATE: P0001, SQLERRM: Exception on dbfunc_sft_cr_interval_d. SQLSTATE: P0001, SQLERRM: Error calling dbfunc_upsert_sft_cr_interval error error describing remote table: OCIStmtExecute failed to describe table. We have a foreign data wrapper pulling from an oracle view.  

Not sure how to resolve this issue, I tried to use 
BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE;
as well as
BEGIN TRANSACTION ISOLATION LEVEL READ COMMMITTED; 
No successful result on both.

**Comment by laurenz** [comment] 2020-05-05 15:58
I'd need the following information:

- Output of

      SELECT oracle_diag('foreign_server_name');

- The `CREATE TABLE` from Oracle.

- The `CREATE FOREIGN TABLE` statement from PostgreSQL.

- The PostgreSQL `SELECT` statement.

Basically, unless it is obvious what the problem is, I need to be able to reproduce the problem to solve it.

**Comment by SrdanD** [comment] 2020-05-05 16:16
See attachment
[questions_oci_error.txt](https://github.com/laurenz/oracle_fdw/files/4582108/questions_oci_error.txt)

**Comment by laurenz** [comment] 2020-05-05 16:23
I see no obvious mistake.

Without the definition of the Oracle tables that are required for the view, I won't be able to reproduce the problem.

**Comment by SrdanD** [comment] 2020-05-05 16:37
See attachment of oracle tables that build the view:

[tables.zip](https://github.com/laurenz/oracle_fdw/files/4582186/tables.zip)

**Comment by laurenz** [comment] 2020-05-06 08:35
Thanks. Objects `MISSION_V` and `INTERVAL_SELECT` are missing.

**Comment by SrdanD** [comment] 2020-05-06 13:43
I altered my server with the following option and it seems to be working good now.
ALTER SERVER CR
OPTIONS (isolation_level 'read_committed');

I will reply back if i start seeing the issue again. Thanks for the quick responses.

**Comment by laurenz** [comment] 2020-05-06 14:55
Thanks for the feedback.

Looks like yet another failure mode for Oracle's crappy implementation of what they call `SERIALIZABLE`. I'm amazed that they have the guts to charge money for this software.

I'll close the issue as resolved.

**Closed by laurenz** 2020-05-06 14:55 UTC
Labels: problem
