### ISSUE TITLE
Is oracle_fdw compatible with EDB 13 on ubuntu OS?

### ISSUE THREAD

**Issue by Tharun1353** [laurenz/oracle_fdw#470] opened 2021-06-09 16:37 UTC
Is oracle_fdw compatible with EDB 13 on ubuntu OS?

**Comment by laurenz** [comment] 2021-06-10 06:48
I don't know. EDB's PostgreSQL fork is closed source, and I cannot say what they modified.
oracle_fdw touches a lot of places in PostgreSQL.
I suggest that you try to build and install oracle_fdw and see if you hit any problems.

**Comment by laurenz** [comment] 2021-06-11 07:18
I'll close this as a duplicate of #469.

**Closed by laurenz** 2021-06-11 07:18 UTC
Labels: question
