### ISSUE TITLE
Incorrect date in select statment

### ISSUE THREAD

**Issue by MikhailVolosevitch** [laurenz/oracle_fdw#284] opened 2018-12-10 15:48 UTC
Hi.
I have a table in oracle Database with datetime values

    SQL> descr per_all_people_f
     Name                                      Null?    Type
     ----------------------------------------- -------- ----------------------------
     PERSON_ID                                 NOT NULL NUMBER(10)
     EFFECTIVE_START_DATE                      NOT NULL DATE
     EFFECTIVE_END_DATE                        NOT NULL DATE

On database server environment variables:

    [oracle@ dbs]$ echo $NLS_LANG
    American_America.CL8KZ1048
    [oracle@ dbs]$ echo $NLS_DATE_FORMAT
    YYYY-MM-DD HH24:MI:SS BC

    SQL> show parameter nls_date_format

    NAME                                 TYPE        VALUE
    ------------------------------------ ----------- ------------------------------
    nls_date_format                      string      YYYY-MM-DD HH24:MI:SS BC

    SQL>  select p.effective_end_date from per_all_people_f p  where p.person_id=55029;

    EFFECTIVE_END_DATE
    ----------------------
    4712-12-31 00:00:00 AD

On PostgreSql server with Oracle Database Client

    $ echo $NLS_DATE_FORMAT
    YYYY-MM-DD HH24:MI:SS BC

    SQL> select p.effective_end_date from per_all_people_f p  where p.person_id=55029;

    EFFECTIVE_END_DATE
    ----------------------
    4712-12-31 00:00:00 AD

On the same server with psql

    => CREATE FOREIGN TABLE ttt(
    >               person_id  integer   NOT NULL,
    >        	effective_start_date date,
    >               effective_end_date date
    >            ) SERVER oebs_apps_fs OPTIONS (schema 'HR', table 'PER_ALL_PEOPLE_F');

    => select effective_end_date from ttt where  person_id=55029;
     effective_end_date
    --------------------
     2012-12-31
    (1 row)

    => SELECT oracle_diag();
                                                                      oracle_diag
    -----------------------------------------------------------------------------------------------------------------------------------------------
     oracle_fdw 2.1.0devel, PostgreSQL 11.0, Oracle client 11.2.0.1.0, ORACLE_HOME=/opt/oracle/client/11.2.0, TNS_ADMIN=$ORACLE_HOME/network/admin
    (1 row)

Why oracle_fdw returns  2012-12-31 instead 4712-12-31?

**Comment by laurenz** [comment] 2018-12-10 19:58
oracle_fdw sets `NLS_LANG`, `NLS_DATE_FORMAT` and others, so setting them has no effect.

I tried to reproduce your test case, but here it works.

On Oracle:

    SQL> CREATE TABLE per_all_people_f(
            person_id NUMBER(10) CONSTRAINT pers_pkey PRIMARY KEY,
            effective_start_date date CONSTRAINT pers_start_date_null NOT NULL,
            effective_end_date date CONSTRAINT pers_end_date_null NOT NULL
         );

    Table created.

    SQL> INSERT INTO per_all_people_f VALUES
            (1, '1970-01-01 00:00:00 AD', '4712-12-31 00:00:00 AD');

    1 row created.

    SQL> COMMIT;

    Commit complete.

    SQL> SELECT * FROM per_all_people_f;

     PERSON_ID EFFECTIVE_START_DATE   EFFECTIVE_END_DATE
    ---------- ---------------------- ----------------------
             1 1970-01-01 00:00:00 AD 4712-12-31 00:00:00 AD

In PostgreSQL:

    CREATE FOREIGN TABLE per_all_people_f(
       person_id  integer NOT NULL,
       effective_start_date date,
       effective_end_date date
    ) SERVER oracle OPTIONS (table 'PER_ALL_PEOPLE_F');

    SELECT * FROM per_all_people_f;
     person_id | effective_start_date | effective_end_date 
    -----------+----------------------+--------------------
             1 | 1970-01-01           | 4712-12-31
    (1 row)

Does your table really only have three columns?

Remember that oracle_fdw does not match columns by name, but by position, so the 7th column of the foreign table will correspond to the 7th Oracle table column regardless of the name.

**Comment by MikhailVolosevitch** [comment] 2018-12-11 04:06
Hi Laurenz
I did as in your example
 
SQL> CREATE TABLE ttt(
        person_id NUMBER(10) CONSTRAINT pers_pkey PRIMARY KEY,
        effective_start_date date CONSTRAINT pers_start_date_null NOT NULL,
        effective_end_date date CONSTRAINT pers_end_date_null NOT NULL
     );

Table created.

SQL> INSERT INTO ttt VALUES  (1, to_date('01.01.1970','dd.mm.yyyy'), to_date('31.12.4712','dd.mm.yyyy'));

1 row created.

SQL> COMMIT;

Postgresql
-----------------

CREATE FOREIGN TABLE ttt(
              person_id  integer   NOT NULL,
 	      effective_start_date date,
              effective_end_date date
           ) SERVER oebs_apps_fs OPTIONS (schema 'APPS', table 'TTT');

CREATE FOREIGN TABLE
=> select * from ttt;
 person_id | effective_start_date | effective_end_date
-----------+----------------------+--------------------
         1 | 1970-01-01           | 2012-12-31
(1 row)


Regards,
Mikhail

**Comment by laurenz** [comment] 2018-12-11 05:58
That means that I cannot reproduce the problem, and consequently not fix it.

Does the value look right with sqlplus?
If you define the `DATE` column as `text` in the foreign table, so that no conversion to a PostgreSQL `date` takes place, what does the column look like?
Does this effect happen only for this specific date or for others too?
Play with it and see what you can find out. Maybe we get a clue that way.

**Comment by MikhailVolosevitch** [comment] 2018-12-11 16:01
Hi Laurenz.
I change Database client from 11.2 to 12.2 and now it works. Please update documentation with supported Oracle Database Client versions.
Thank you.
Regards,
Mikhail.

**Comment by laurenz** [comment] 2018-12-11 19:12
Oracle client is supported from 10.1 on.
I use version 11.2 for development, and I have not had that problem, so I am not sure it is an Oracle software bug you were experiencing.

**Comment by laurenz** [comment] 2018-12-11 19:13
I guess I'll close this, since it works for you now, and I doubt that we can find out more now you have upgraded.

**Closed by laurenz** 2018-12-11 19:13 UTC
Labels: problem

**Comment by laurenz** [comment] 2020-06-11 20:23
It may be an Oracle logon trigger that messes with oracle_fdw's settings, see #402.
