### ISSUE TITLE
IMPORT FOREIGN SCHEMA maps rather exotic SDO_ETYPEs naively to 'geometry'

### ISSUE THREAD

**Issue by pinkerltm** [laurenz/oracle_fdw#301] opened 2019-02-27 14:34 UTC
I post this as I recently ran into issues migrating different GTYPEs and ETYPEs to PostGIS and had to manually tweak the DDL which was generated by IMPORT FOREIGN SCHEMA pretty well except for some minor things which made the whole migration not working right out of the box.

Examples are 3 and 4 dimensional geometries like  'LINESTRINGM(...)' or 'POINTZ(...)'

Also it would be nice if correct typemods are used, so that the created tables register correctly in geometry_columns right away.

Please mark this as an enhancement, I will try to deliver an appropriate pull request.

**Comment by laurenz** [comment] 2019-02-27 14:40
Thanks for the initiative.

Currently they are all mapped to `geometry`, which should work.
But if it is possible to get more information easily, that would be a good improvement.

Is there a guarantee that a certain `SDO_GEOMETRY` column will only contain certain kinds of geometries?

**Comment by pinkerltm** [comment] 2019-02-27 14:50
No definitely not, you will still have to clean data on the oracle side if geometry types are mixed. Thats not the scope of this enhancement.

But mapping all to `geometry` unfortunately does not seem work for 3 and 4 dimensional types without providing the correct typemod. Also there are typemods for SQL\MM geometries (COLLECTIONS, CURVES, SURFACES), perhaps there is also room for improvement.

**Comment by laurenz** [comment] 2019-02-28 11:46
If there is no way to tell that all `SDO_GEOMETRY`s on the Oracle side are guaranteed to only contain a certain type of geometry, how can you determine the correct geometry type to use in PostgreSQL?

Maybe I misunderstand something here.

Yes, geometry support in oracle_fdw is limited to the types @vmora implemented. As soon as someone does the work, we can have more...

**Comment by vmora** [comment] 2019-03-01 12:13
@pinkerltm there is definitely room for improvement :)

I believe the support that has been introduced 4 years ago covers 80% of use cases, curves and surfaces are a bit exotic, collections are useful return types but  shouldn't be used as column type IMHO. 

If those type are useful enough for someone to fund the developments (contact info@oslandia.com) or make a PR that will be a really nice enhancement.

> Is there a guarantee that a certain SDO_GEOMETRY column will only contain certain kinds of geometries?

@laurenz, @pinkerltm what is the current behavior if the geometry found in the column is not of the declared type (typemod) ? My expected behavior would be an exception in a query. If it's what actually happens (I've not the infra handy to test that), then I'd plead to keep it this way.

> how can you determine the correct geometry type to use in PostgreSQL?

Concerning the correct typemods, I'm not familiar with IMPORT FOREIGN SCHEMA but I'd think it would be nice to "guess" the appropriate geometry type for a column by looking, say, at any random record and use it's type. If it's possible to do that, than it should work 80% of the time and get you a nice exception when the guessed type is wrong. The user can always relax the typemod (returning to the generic geometry type) if that's what is really needed, this behavior could be a third option to IMPORT FOREIGN SCHEMA (I'd prefer the default to be with typemods since I think it's the best behavior).

Hence, for me :+1 for @pinkerltm to narrow down the type when importing a schema.

**Comment by laurenz** [comment] 2019-03-01 15:16
Thanks for the comment!

The way oracle_fdw's PostGIS support is currently coded, it does not verify the correctness of the data on the PostgreSQL end. That was originally the same with string encodings, and I had to introduce an explicit check in 39d97cf64c44cb295df8237a9d6073762f0455e9.

I tested, and oracle_fdw will happily return a LINESTRING in a foreign table column defined as `geometry(POINT)`.

Still, I think that it would be fine to define the PostgreSQL columns with the additional type modifiers *as long as Oracle guarantees that they are correct*, similar to `NOT NULL` Oracle columns which we import as `NOT NULL`. If we can't have such a guarantee from the Oracle side, I'd rather not have `IMPORT FOREIGN SCHEMA` decorate the data types with modifiers that may be wrong. You can always do that manually afterwards if you know what you are doing.

@pinkerltm, can you explain in detail what the trouble with three- and four-dimensional geometries is? How do the type modifiers make a difference?

**Comment by pinkerltm** [comment] 2019-03-11 15:09
@laurenz I'll stay on LINESTRING as the example, but it's pretty much always the same situation for POINTs and POLYGONs:

IMPORT FOREIGN SCHEMA struggles as said only if the geometry on the Oracle side has more than 2 Dimensions, or said in other words: if the typemod GEOMETRY or even LINESTRING is not enough.

For 2 Dimensions + Z Coordinate the correct typemod should be LINESTRINGZ
For 2 Dimensions + Measure the correct typemod should be LINESTRINGM
For 2 Dimensions + Z + M the correct typemod should be LINESTRINGZM

So the Foreign Tables which are created by IMPORT FOREIGN SCHEMA fail to retrieve data, as the geometry is interpreted in a wrong fashion. You just have to alter the typemod manually to make it work.

typemod geometry(GEOMETRY,...) won't work here, because "**the suffixes Z, M and ZM are three distinct copies of the geometry hierarchy** ..." (as specified in OGC Simple Feature Access - SQL 7.1.3.3.e. GEOMETRY_TYPE; Page 22ff). Therefore you would have to use respectively GEOMETRYZ, GEOMETRYM or GEOMETRYZM in these cases.

**Comment by pinkerltm** [comment] 2019-03-11 15:17
@vmora 

> My expected behavior would be an exception in a query. If it's what actually happens (I've not the infra handy to test that), then I'd plead to keep it this way.

Yes, thats exactly what happens, and yes I would also keep it that way so that someone is able to decide how features should get migrated and as you say should be stored correctly

> Concerning the correct typemods, I'm not familiar with IMPORT FOREIGN SCHEMA but I'd think it would be nice to "guess" the appropriate geometry type for a column by looking, say, at any random record and use it's type.

currently I GROUP BY geometrytype(...) order by count(*) desc LIMIT 1 ... except if there are MULTI... Features, then I ALWAYS use the MULTI... as it is less restrictive and Single types can be easily casted to Multi. That works good enough for us except in cases where the table in question is larger than several hundrets of thousands of rows, then I would try to get a restricted sample to group by on.

**Comment by laurenz** [comment] 2019-03-12 10:20
Thanks for the clarification!

My stance is that this feature would be very welcome if we can guarantee from the Oracle table definition that all geometries will match the type modifier.

If we cannot do that, you'd have to guess from a sample of table rows, right?
I think that would cause more problems than benefit, particularly since a simple `ALTER FOREIGN TABLE` can fix the problem.

**Comment by laurenz** [comment] 2019-08-22 07:11
Shall I keep this open?
Would your approach guarantee that the Oracle table cannot have data that do not match the type modifier?

**Comment by AlexDevLer** [comment] 2019-09-30 05:03
Hello, 
excuse me for writing here. I have some problems with insert/update/delete. It's possible to do this actions? Im creating foreign tables to server, but i don't see it inside the server database.

**Comment by laurenz** [comment] 2020-02-13 09:11
To clarify for the future:
This is a request to add support for higher-dimensional geometries.
I'll close it for now, since I won't implement that, but I am willing to help extending the GIS code if someone does the leg work.

**Closed by laurenz** 2020-02-13 09:11 UTC
Labels: enhancement, wontfix
