### ISSUE TITLE
problems using oracle wallet

### ISSUE THREAD

**Issue by chdemars** [laurenz/oracle_fdw#162] opened 2017-05-09 16:33 UTC
I'm trying to set up oracle_fdw, on a windows box, with a wallet so that passwords aren't stored in plaintext.

Basically following this manual: http://www.toadworld.com/platforms/oracle/w/wiki/11411.secure-external-password-store

I can get oracle to login automatically with sqlplus so things should work.

But when I try to query a foreign table, I get this error: ORA-12578: TNS:wallet open failed

Changing SQLNET.WALLET_OVERRIDE to FALSE in sqlnet.ora changes the error to: ORA-01017: invalid username/password; logon denied

TNS_ADMIN environment variable seems to be fine (echo'd it from a command line then ran psql) and no amount of fiddling with permissions on the wallet files has seemed to help.

Any advise on where to look next?

**Comment by chdemars** [comment] 2017-05-09 18:05
Setting TNS_ADMIN in the registry had no effect.

**Comment by laurenz** [comment] 2017-05-10 10:48
It is very likely a permission problem, at least that's what searching Oracle's knowledge base suggests.

What is your operating system?

You could trace the process (using `strace` on Linux or [process monitor](https://technet.microsoft.com/en-us/processmonitor) on Windows) to see if the files are accessed and what the problem is.

Don't forget that not only the permissions on the wallet files, but also the permissions on the containing directories must be so that the PostgreSQL server process can access the files.

**Comment by chdemars** [comment] 2017-05-10 18:21
OS = Windows 7 Enterprise, service pack 1 (not my choice, instead is a mandate from work). I'm using the EnterpriseDB distribution of postgres.

I generated the wallet and went through each directory and file leading to the wallet and executed:

> icacls [file] /grant Users:F

sqlplus work fine with the wallet.

When I query an external table in postgres, I still get the "wallet open failed" error.

Process monitor output the following:

11:13:47.2106929 AM	postgres.exe	3648	ReadFile	C:\oracle\oraprod1\wallet\cwallet.sso	SUCCESS	Offset: 0, Length: 4, Priority: Normal
11:13:47.2107264 AM	postgres.exe	3648	ReadFile	C:\oracle\oraprod1\wallet\cwallet.sso	SUCCESS	Offset: 0, Length: 3,957, Priority: Normal
11:13:47.2140541 AM	postgres.exe	3648	ReadFile	C:\oracle\oracle11g\rdbms\mesg\oraus.msb	SUCCESS	Offset: 0, Length: 256, Priority: Normal
11:13:47.2140914 AM	postgres.exe	3648	ReadFile	C:\oracle\oracle11g\rdbms\mesg\oraus.msb	SUCCESS	Offset: 512, Length: 512, Priority: Normal
11:13:47.2141157 AM	postgres.exe	3648	ReadFile	C:\oracle\oracle11g\rdbms\mesg\oraus.msb	SUCCESS	Offset: 1,536, Length: 512, Priority: Normal
11:13:47.2141374 AM	postgres.exe	3648	ReadFile	C:\oracle\oracle11g\rdbms\mesg\oraus.msb	SUCCESS	Offset: 243,712, Length: 512, Priority: Normal

Wouldn't the success result for reading the wallet files indicate that there was proper permissions? Is there a better way to grant permissions? I miss chmod.

**Comment by laurenz** [comment] 2017-05-12 09:24
Some ideas:

1. There is one Oracle bug that *could* be the cause:

   Bug 16607000:
   The cwallet.sso files created with the `-auto_login_local` option on Windows  cannot be opened transparently if they are owned by users whose names contain mixed case letters.
  Affects 11.2.0.3 and later, fixed in 11.2.0.4.5  and 11.2.0.3.30.

2. Are there any suspicious FAILED messages with process explorer right before the error message?

3. How exactly did you create the wallet?
   Did you use `orapki wallet create -auto_login` or `orapki wallet create -auto_login_local` (the latter restricts use of the wallet to the computer where it was created)?
   Is the operating system user that runs the PostgreSQL server the user that created the wallet?
   According to [the documentation][1]:
   > When auto login is enabled for a wallet, it is only available to the operating system user who created that wallet.

4. Is the same `sqlnet.ora` used in both cases?

 [1]: http://docs.oracle.com/cd/E25054_01/network.1111/e10746/asogls.htm#i998094

**Comment by laurenz** [comment] 2017-06-14 06:59
I'll close this issue for inactivity.
Feel free to reopen it if you have any new information!

**Closed by laurenz** 2017-06-14 06:59 UTC
Labels: problem
