### ISSUE TITLE
make command raise error while installing oracle_fdw

### ISSUE THREAD

**Issue by MobeenNaser** [laurenz/oracle_fdw#649] opened 2024-02-19 09:21 UTC
while I'm trying to install oracle_fdw this error raised :

Makefile:30: /usr/pgsql-15/lib/pgxs/src/makefiles/pgxs.mk: No such file or directory
make: *** No rule to make target '/usr/pgsql-15/lib/pgxs/src/makefiles/pgxs.mk'.  Stop.

**Comment by laurenz** [comment] 2024-02-19 09:46
This is a duplicate of #390 and #615.
Please install the "devel" RPM.

**Comment by MobeenNaser** [comment] 2024-02-19 09:56
i have installed all *-devel Packages but noting changed

**Comment by laurenz** [comment] 2024-02-19 10:00
Perhaps you installed the wrong one. What do you get for

```bash
rpm -q -a postgres\*
```

**Comment by MobeenNaser** [comment] 2024-02-19 10:01
postgresql12-plperl-12.18-1PGDG.rhel8.x86_64
postgresql16-plperl-16.2-1PGDG.rhel8.x86_64
postgresql12-12.18-1PGDG.rhel8.x86_64
postgresql14-server-14.11-1PGDG.rhel8.x86_64
postgresql16-libs-16.2-1PGDG.rhel8.x86_64
postgresql16-16.2-1PGDG.rhel8.x86_64
postgresql12-libs-12.18-1PGDG.rhel8.x86_64
postgresql13-server-13.14-1PGDG.rhel8.x86_64
postgresql15-libs-15.6-1PGDG.rhel8.x86_64
postgresql14-14.11-1PGDG.rhel8.x86_64
postgresql15-15.6-1PGDG.rhel8.x86_64
postgresql14-plperl-14.11-1PGDG.rhel8.x86_64
postgresql15-plperl-15.6-1PGDG.rhel8.x86_64
postgresql14-libs-14.11-1PGDG.rhel8.x86_64
postgresql12-server-12.18-1PGDG.rhel8.x86_64
postgresql13-13.14-1PGDG.rhel8.x86_64
postgresql16-server-16.2-1PGDG.rhel8.x86_64
postgresql13-libs-13.14-1PGDG.rhel8.x86_64
postgresql13-plperl-13.14-1PGDG.rhel8.x86_64
postgresql15-server-15.6-1PGDG.rhel8.x86_64

**Comment by laurenz** [comment] 2024-02-19 10:08
No, you didn't install `postgresql15-devel`.

**Comment by MobeenNaser** [comment] 2024-02-19 10:29
where can i find it

**Comment by laurenz** [comment] 2024-02-19 11:12
Where you found the other packages. How did you install PostgreSQL?

**Comment by MobeenNaser** [comment] 2024-02-19 11:54
i followed the website instructions 

# Install the repository RPM:
sudo dnf install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm

# Disable the built-in PostgreSQL module:
sudo dnf -qy module disable postgresql

# Install PostgreSQL:
sudo dnf install -y postgresql15-server

# Optionally initialize the database and enable automatic start:
sudo /usr/pgsql-15/bin/postgresql-15-setup initdb
sudo systemctl enable postgresql-15
sudo systemctl start postgresql-15

**Comment by laurenz** [comment] 2024-02-19 13:34
Well, there you have the answer:

```bash
sudo dnf install postgresql15-devel
```

Unrelated, but you should always install the "contrib" package as well.

**Comment by MobeenNaser** [comment] 2024-02-21 07:45
i have installed it and i run make command but while running make install this is the output:

make install
/usr/bin/mkdir -p '/usr/pgsql-15/lib'
/usr/bin/mkdir -p '/usr/pgsql-15/share/extension'
/usr/bin/mkdir -p '/usr/pgsql-15/share/extension'
/usr/bin/mkdir -p '/usr/pgsql-15/doc/extension'
/usr/bin/install -c -m 755  oracle_fdw.so '/usr/pgsql-15/lib/oracle_fdw.so'
/usr/bin/install: cannot create regular file '/usr/pgsql-15/lib/oracle_fdw.so': Permission denied
make: *** [/usr/pgsql-15/lib/pgxs/src/makefiles/../../src/Makefile.shlib:461: install-lib-shared] Error 1

i run make install using postgres OS user

**Comment by laurenz** [comment] 2024-02-21 08:25
Ok. Read the documentation. All that is described there.
Or read the dozens of issues people created about this.
Why do you want me to spoon-feed you every single step?

**Comment by laurenz** [comment] 2024-02-21 10:00
In particular, #22 and #440 might help you.
You have to make sure that the directory with the shared library is on the library path of PostgreSQL.

**Comment by laurenz** [comment] 2024-02-24 11:17
Sorry for my annoyance; I know you're not doing it on purpose.

I assume that you are starting PostgreSQL via systemd. Assuming that the path where `libclntsh.so.12` is is `/path/to/oracle`, you'd proceed as follows:

- edit the systemd service as user `root`:

  ```bash
  systemctl edit postgresql-15
  ```

- add the following two lines:

  ```none
  [Service]
  Environment='LD_LIBRARY_PATH=/path/to/oracle'
  ```

- save the file and restart PostgreSQL

  ```bash
  systemctl restart postgresql-15
  ```

**Comment by MobeenNaser** [comment] 2024-02-24 13:00
it's okay i will try and send you the results

**Comment by MobeenNaser** [comment] 2024-02-24 14:22
it's not working , can you please tell me how can i down load postgresql 15.6 i just can find 15.1 on website

**Comment by laurenz** [comment] 2024-02-26 09:24
You already downloaded and installed PostgreSQL 15.6, as [your output above](https://github.com/laurenz/oracle_fdw/issues/649#issuecomment-1952097655) shows. Why download it again?

You did replace `/path/to/oracle` with the actual path on your system, right?

**Comment by MobeenNaser** [comment] 2024-02-26 09:26
no it's 15.1 

postgres=# select version();
                                                 version
---------------------------------------------------------------------------------------------------------
 PostgreSQL 15.1 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-15), 64-bit
(1 row)

**Comment by laurenz** [comment] 2024-02-26 09:28
Did you lie when you posted the list of installed RPMs?

**Comment by MobeenNaser** [comment] 2024-02-26 09:28
no why should i lie ?

**Comment by laurenz** [comment] 2024-02-26 09:29
Then why does it say 15.6 there?

**Comment by MobeenNaser** [comment] 2024-02-26 09:30
i dont know

**Comment by laurenz** [comment] 2024-02-26 09:38
Sorry, I don't think I can help you.
Perhaps you can ask somebody who understands a little bit about computers to have a look at your system and assist you.

**Closed** 2024-02-26 09:52 UTC
Labels: duplicate, problem, installation
