### ISSUE TITLE
Build error against Instantclient 21.3

### ISSUE THREAD

**Issue by devrimgunduz** [laurenz/oracle_fdw#493] opened 2021-09-20 09:39 UTC
Hi @laurenz ,

I'm getting the following errors after adding 21.3 paths to Makefile. Can you please take a look?

Regards, Devrim

> gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -I/sdk/include -I/oci/include -I/rdbms/public -I -I/usr/include/oracle/19.8/client -I/usr/include/oracle/19.8/client64 -I/usr/include/oracle/19.6/client -I/usr/include/oracle/19.6/client64 -I/usr/include/oracle/19.3/client -I/usr/include/oracle/19.3/client64 -I/usr/include/oracle/18.5/client -I/usr/include/oracle/18.5/client64 -I/usr/include/oracle/18.3/client -I/usr/include/oracle/18.3/client64 -I/usr/include/oracle/12.2/client -I/usr/include/oracle/12.2/client64 -I/usr/include/oracle/12.1/client -I/usr/include/oracle/12.1/client64 -I/usr/include/oracle/11.2/client -I/usr/include/oracle/11.2/client64 -I/usr/include/oracle/11.1/client -I/usr/include/oracle/11.1/client64 -I/usr/include/oracle/10.2.0.5/client -I/usr/include/oracle/10.2.0.5/client64 -I/usr/include/oracle/10.2.0.4/client -I/usr/include/oracle/10.2.0.4/client64 -I/usr/include/oracle/10.2.0.3/client -I/usr/include/oracle/10.2.0.3/client64 -I/usr/include/oracle/21/client64 -I. -I./ -I/usr/pgsql-14/include/server -I/usr/pgsql-14/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o oracle_gis.o oracle_gis.c
> oracle_fdw.c: In function 'oracle_fdw_handler':
> oracle_fdw.c:400:38: warning: assignment to 'AddForeignUpdateTargets_function' {aka 'void (*)(struct PlannerInfo *, unsigned int,  struct RangeTblEntry *, struct RelationData *)'} from incompatible pointer type 'void (*)(Query *, RangeTblEntry *, struct RelationData *)' {aka 'void (*)(struct Query *, struct RangeTblEntry *, struct RelationData *)'} [-Wincompatible-pointer-types]
>   fdwroutine->AddForeignUpdateTargets = oracleAddForeignUpdateTargets;
>                                       ^
> oracle_fdw.c: In function 'oracleBeginForeignModify':
> oracle_fdw.c:1718:27: error: 'ModifyTableState' {aka 'struct ModifyTableState'} has no member named 'mt_plans'; did you mean 'mt_done'?
>   Plan *subplan = mtstate->mt_plans[subplan_index]->plan;
>                            ^~~~~~~~
>                            mt_done
> make[1]: *** [<builtin>: oracle_fdw.o] Error 1
> make[1]: *** Waiting for unfinished jobs....
>

**Comment by laurenz** [comment] 2021-09-20 13:40
It looks like you are using an old version of oracle_fdw to build against v14.

In particular, you seem to be missing commit 9029418745eaedac536ecf485c3c1d15c3912946.

Until I release 2.4.0, please use Git HEAD.

**Comment by devrimgunduz** [comment] 2021-09-21 19:55
Hi @laurenz 

To build RPMs, I need a tarball  (I mean, actual release). Any chance to release a new version?

Thanks!

Regards, Devrim

**Comment by laurenz** [comment] 2021-09-22 07:19
This is pretty much a duplicate of #491, and I get the message.

I want to wait until at least RC1 is out, so that I don't have to go through the pain of building Windows binaries again.
Real Soon Now.

**Comment by laurenz** [comment] 2021-09-24 07:16
Release 2.4.0 is out.

**Closed by laurenz** 2021-09-24 07:16 UTC
Labels: duplicate, problem, installation
