### ISSUE TITLE
Getting sysdate on remote oracle database

### ISSUE THREAD

**Issue by erzhan0809** [laurenz/oracle_fdw#324] opened 2019-05-26 19:47 UTC
Good day,
Thank you for the excellent extension, everything works fine on postgresql10, I had the task to get sysdate on a remote oracle server. On the remote database, I have access only in readonly mode. How can I make a query on the similarity `select sysdate from dual`?

`select oracle_diag ('oradb');`
oracle_diag
oracle_fdw 2.2.0devel, PostgreSQL 10.8, Oracle client 18.5.0.0.0, Oracle server 11.2.0.4.0

**Comment by laurenz** [comment] 2019-05-26 21:46
You cannot do that directly.

This question is a duplicate of #187. Does that workaround help you?

**Comment by erzhan0809** [comment] 2019-05-27 04:06
No, I can not create table, functions or trigger. Only readonly access. Is there any other workarounds?

**Comment by laurenz** [comment] 2019-05-27 11:36
Actually it should be quite trivial in this case:

    CREATE FOREIGN TABLE dual(sysdate timestamp(0) without time zone)
       SERVER oraserver
       OPTIONS (table '(SELECT sysdate FROM dual)');

**Comment by erzhan0809** [comment] 2019-05-28 08:11
works fine, thanks

**Closed** 2019-05-28 08:10 UTC
Labels: duplicate, problem
