### ISSUE TITLE
Create a foreign table based on a query

### ISSUE THREAD

**Issue by jgoux** [laurenz/oracle_fdw#59] opened 2016-02-24 07:29 UTC
Hello,
is there any plan to add this fonctionnality ?
I use this extension in order to aggregate data from multiple remote oracle databases. 
I don't have write access on these oracle databases, so I'm not able to create views on them to optimize the complex queries execution and fetching.
This option would allow these optimizations without having to have write access on the remote databases.

Thanks again for this useful extension! :fireworks:

**Comment by laurenz** [comment] 2016-02-24 08:04
This is a duplicate of #45.

Since this has been requested at least three times, I'll leave this request open.
I have no fundamental objection against such an enhancement.
Maybe I'll get to it at some point, or somebody else can pick it up.

I am still amazed that creating a view in Oracle proves to be such an (administrative) problem for many people.

**Comment by laurenz** [comment] 2016-03-04 13:56
I just committed 9c3b7b55fd104a785580f847cc7eb872994d526b which allows foreign tables based on arbitrary Oracle queries.
@jgoux, @tsykes, @cirix81, I'd be grateful if you'd try it out and see if it works for you and is sufficiently documented.

**Comment by tsykes** [comment] 2016-03-04 20:46
Perhaps I didn't install right but my table-based foreign tables still work. When I try to run a query against a table created with a query-based foreign table, I get this error (depending on how I wrote the query): 

ERROR: error describing remote table: OCIStmtExecute failed to describe table
SQL state: HV00M
Detail: ORA-00972: identifier is too long

or  

Error: ERROR: error describing remote table: OCIStmtPrepare failed to prepare query
  Detail: ORA-00972: identifier is too long
SQLState:  HV00M
ErrorCode: 0

I am using this Oracle driver on centos 
oracle-instantclient11.2-basic.x86_64 11.2.0.4.0-1

**Comment by laurenz** [comment] 2016-03-05 12:22
Thanks for taking a look at this.

Did you read the documentation (README)?
Is the new feature not adequately documented?

**Comment by jgoux** [comment] 2016-03-05 12:42
I'll give my feedback on monday ! :+1: 
Thanks for the fast implementation !

**Comment by jgoux** [comment] 2016-03-07 08:51
Sorry for the double post, just to notify that the option works for me ! :tada: 
I found the documentation sufficient, maybe you could just add that we need to escape all the `'` characters using `''`, as the option requires the query to be a string.

Thanks **a lot** for this feature !

**Comment by laurenz** [comment] 2016-03-07 09:01
Good, idea, I have adapted the example in the README.
The implementation was simpler than I thought.

**Comment by tsykes** [comment] 2016-03-07 15:56
It works for me too. I thought I had followed the README but I missed the parentheses around the SELECT. They probably tell you this table is a query not a table. That explains my "identifier is too long" error. Thanks for this. It's great.

**Comment by laurenz** [comment] 2016-03-08 07:38
Thanks for all the feedback, I'll close the issue.

**Closed by laurenz** 2016-03-08 07:38 UTC
Labels: duplicate, enhancement
