### ISSUE TITLE
make command is receiving an error

### ISSUE THREAD

**Issue by barisyildirim1611** [laurenz/oracle_fdw#278] opened 2018-10-15 13:44 UTC
Hello,
thank you for your great work.

I am trying to run make command, but I recevied the error below

thanks in advance

    gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fPIC -I/usr/lib/oracle/11.2/client64/sdk/include -I/usr/lib/oracle/11.2/client64/oci/include -I/usr/lib/oracle/11.2/client64/rdbms/public -I/usr/include/oracle/18.3/client -I/usr/include/oracle/18.3/client64 -I/usr/include/oracle/12.2/client -I/usr/include/oracle/12.2/client64 -I/usr/include/oracle/12.1/client -I/usr/include/oracle/12.1/client64 -I/usr/include/oracle/11.2/client -I/usr/include/oracle/11.2/client64 -I/usr/include/oracle/11.1/client -I/usr/include/oracle/11.1/client64 -I/usr/include/oracle/10.2.0.5/client -I/usr/include/oracle/10.2.0.5/client64 -I/usr/include/oracle/10.2.0.4/client -I/usr/include/oracle/10.2.0.4/client64 -I/usr/include/oracle/10.2.0.3/client -I/usr/include/oracle/10.2.0.3/client64 -I. -I./ -I/usr/pgsql-10/include/server -I/usr/pgsql-10/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o oracle_fdw.o oracle_fdw.c
    oracle_fdw.c: In function ‘foreign_join_ok’:
    oracle_fdw.c:2919:3: warning: passing argument 2 of ‘extract_actual_join_clauses’ from incompatible pointer type [enabled by default]
       extract_actual_join_clauses(extra->restrictlist, joinrel->relids, &joinclauses, &otherclauses);
       ^
    In file included from oracle_fdw.c:51:0:
    /usr/pgsql-10/include/server/optimizer/restrictinfo.h:38:13: note: expected ‘struct List **’ but argument is of type ‘Relids’
     extern void extract_actual_join_clauses(List *restrictinfo_list,
                 ^
    oracle_fdw.c:2919:3: error: too many arguments to function ‘extract_actual_join_clauses’
       extract_actual_join_clauses(extra->restrictlist, joinrel->relids, &joinclauses, &otherclauses);
       ^
    In file included from oracle_fdw.c:51:0:
    /usr/pgsql-10/include/server/optimizer/restrictinfo.h:38:13: note: declared here
     extern void extract_actual_join_clauses(List *restrictinfo_list,
                 ^
    make: *** [oracle_fdw.o] Error 1

**Comment by laurenz** [comment] 2018-10-15 13:52
This is a duplicate of #272.

Like the README says:

> Due to an API break in a PostgreSQL minor release, the following PostgreSQL
> versions cannot be used: 9.6.0 to 9.6.8 and 10.0 to 10.3

You should upgrade to a more recent bugfix level.

**Closed** 2019-01-17 08:48 UTC
Labels: duplicate, problem
