### ISSUE TITLE
Running a large/long query can make whole Linux server unresponsive

### ISSUE THREAD

**Issue by gnudiff** [laurenz/oracle_fdw#336] opened 2019-07-05 11:25 UTC
I have an Oracle server, which can pause before giving results for up to a 5 or more minutes, when some of the larger queries run directly via oracle sqlplus client from Postgres Linux host, but after the wait, the query finishes OK.

Normally it causes no problem for oracle_fdw either, but today a query caused either a complete network bottleneck or Linux server lock, because the SSH session to the Linux host became completely unresponsive for 2+ minutes. From VMWare cluster view, however, neither CPU, nor Disk, nor network usage for the PG virtual host didn't skyrocket at that point.

Can it be expected that oracle_fdw can completely lock machine when dealing with large data sets and/or pauses? Can it be somehow managed/limited, perhaps by tweaking PG server parameters?

The query explain plan stated:  
Foreign Scan on rpt_1  (cost=10000.00..20000.00 rows=1000 width=1160)

The software:

- Ubuntu 16.04.6 LTS
- PostgreSQL 9.5.17 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609, 64-bit
- Oracle_fdw 2.0.0
-  oracle-instantclient12.2-basiclite    12.2.0.1.0-2 
-  oracle-instantclient12.2-devel        12.2.0.1.0-2 
-  oracle-instantclient12.2-sqlplus      12.2.0.1.0-2

**Comment by laurenz** [comment] 2019-07-05 11:31
I have never heard of such a problem in connection with oracle_fdw.

When you say the Oracle server "pauses" before giving a result, do you mean that the query is running for 5 minutes or that a query that normally takes a short time suddenly takes much longer (which could be due to a lock)?

If the PostgreSQL machine becomes unresponsive for a longer time, but neither the "sar" log nor other monitoring data show high activity anywhere, I'd first suspect the network.

**Comment by gnudiff** [comment] 2019-07-09 08:19
I mean that the oraclient query is running around 5 minutes, out of which 99% of time is waiting for data from Oracle to start to appear.

I didn't manage to get sar running at the point when I had the problem, but I had vmware stats for the virtual machine, which does show sharp increase in activity from the approximate period the query was run, but nothing (CPU/disk/network) utilization exceeding ~50%

**Comment by laurenz** [comment] 2019-07-09 08:23
I don't get it. The (Oracle) client is 99% idle, but the PostgreSQL machine is busy?
Can you find out what the Oracle query was (`EXPLAIN` on the PostgreSQL query) and examine that?
Is the problem reproducible or intermittent?

**Comment by laurenz** [comment] 2019-08-06 07:16
Do you have more information, or should I close the issue?

**Comment by gnudiff** [comment] 2019-08-07 11:23
Sorry, I can't seem to be able to reproduce this. Will try to gather more information, if this happens again.

**Closed** 2019-08-07 11:33 UTC
Labels: problem
