### ISSUE TITLE
oracle_fdw date insert  on date attribute error DETAIL:  ORA-01843: not a valid month oracle 10g 

### ISSUE THREAD

**Issue by alirazaidi** [laurenz/oracle_fdw#506] opened 2021-12-10 14:52 UTC
While inserting data from EDB 13 to oracle 10g for date attribute oracle foreign table of  oracle_fdw  gives following error.

ERROR:  error executing query: OCIStmtExecute failed to execute remote query
DETAIL:  ORA-01843: not a valid month

DB: EDB postgres 
ORACLE client : 21c
DB: Oracle 10G 
Any suggestion.

Note* : it works fine if I use simple insert but it fails in procedure.

**Comment by laurenz** [comment] 2021-12-10 16:10
Could you give me the following:

- the `CREATE TABLE` statement on Oracle
- the `CREATE FOREIGN TABLE` statement on PostgreSQL
- the exact `INSERT` statement that causes the error

Also, I would like to know the `lc_*` parameters of your PostgreSQL database, as well as `server_encoding`.

Are there any login triggers in the Oracle database?

**Comment by alirazaidi** [comment] 2021-12-10 16:25
Hi,

Sorry I missed one point if I execute simple insert it works but when I us it in procedure it fails with error.

Please find details below.

Oracle Table.

CREATE TABLE GCENPRD.BGC_DCP_LOG
   (    BDLSITE number(5,0),
    BDLDATE DATE,
    BDLTYPE VARCHAR2(10 ),
    BDLSEQ number(16,0),
    BDLFLAG number(1,0),
    BDLDMAJ DATE
   );

EDB postgres foreign table.

CREATE FOREIGN TABLE dcpadm.BGC_DCP_LOG_fdw -- GCENPRD.BGC_DCP_LOG
   (    BDLSITE numeric(5,0),
    BDLDATE DATE,
    BDLTYPE VARCHAR(10 ),
    BDLSEQ numeric(16,0),
    BDLFLAG numeric(1,0),
    BDLDMAJ DATE
   ) SERVER oradb OPTIONS (schema 'GCENPRD', table 'BGC_DCP_LOG' );


CONTEXT: SQL statement "INSERT INTO BGC_DCP_LOG_fdw
( BDLSITE , BDLDATE , BDLTYPE , BDLSEQ , BDLFLAG , BDLDMAJ )
VALUES (P_STORE_CODE , TRUNC(now()) , 'ADJDCPA' , V_SEQ_INTMVTSTO , 0 ,now() )"


Also, I would like to know the lc_* parameters of your PostgreSQL database, as well as server_encoding.

Can you share command to get these parameters ? sorry I tried but couldn’t find.

No login trigger in oracle.



Regards,

Ali Raza


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by alirazaidi** [comment] 2021-12-14 02:34
On different environment I tested it with oracle client 19c and it worked.
Any update from your side ?

**Comment by laurenz** [comment] 2021-12-14 08:43
You can get the parameters with

```
SELECT name, setting
FROM pg_settings
WHERE name LIKE 'lc\_%';
```

I created the table, but your `INSERT` statement fails for me, because neither `P_STORE_CODE` nor `V_SEQ_INTMVTSTO` nor `TRUNC` are defined.

In order to help you with the problem, I have to be able to reproduce it.

**Comment by alirazaidi** [comment] 2021-12-15 17:37
Sorry , You can use below insert statement .

   INSERT INTO dcpadm.BGC_DCP_LOG_fdw 
   values(1,now(),'test',1,1,null);
regarding  parameteres
   SELECT name, setting
FROM pg_settings
WHERE name LIKE 'lc\_%';
lc_collate	en_US.UTF-8
lc_ctype	en_US.UTF-8
lc_messages	en_US.UTF-8
lc_monetary	en_US.UTF-8
lc_numeric	en_US.UTF-8
lc_time	en_US.UTF-8

**Comment by laurenz** [comment] 2021-12-16 08:37
I still cannot reproduce it. Perhaps something changed your session parameters. Can you do the following:

```
CREATE FOREIGN TABLE nls_session_parameters(
   parameter text,
   value text
) SERVER oradb OPTIONS (schema 'SYS', table 'NLS_SESSION_PARAMETERS');

TABLE nls_session_parameters;
```

That will show the current settings, which should be similar to this:

```none
        parameter        │                value                
═════════════════════════╪═════════════════════════════════════
 NLS_LANGUAGE            │ AMERICAN
 NLS_TERRITORY           │ AMERICA
 NLS_CURRENCY            │ $
 NLS_ISO_CURRENCY        │ AMERICA
 NLS_NUMERIC_CHARACTERS  │ .,
 NLS_CALENDAR            │ GREGORIAN
 NLS_DATE_FORMAT         │ YYYY-MM-DD HH24:MI:SS BC
 NLS_DATE_LANGUAGE       │ AMERICAN
 NLS_SORT                │ BINARY
 NLS_TIME_FORMAT         │ HH.MI.SSXFF AM
 NLS_TIMESTAMP_FORMAT    │ YYYY-MM-DD HH24:MI:SS.FF9 BC
 NLS_TIME_TZ_FORMAT      │ HH.MI.SSXFF AM TZR
 NLS_TIMESTAMP_TZ_FORMAT │ YYYY-MM-DD HH24:MI:SS.FF9TZH:TZM BC
 NLS_DUAL_CURRENCY       │ $
 NLS_COMP                │ BINARY
 NLS_LENGTH_SEMANTICS    │ BYTE
 NLS_NCHAR_CONV_EXCP     │ FALSE
```

Is that what you see?

**Comment by alirazaidi** [comment] 2021-12-20 17:31
Hi  Please find the parameters for this.

parameter
values
NLS_LANGUAGE
AMERICAN
NLS_TERRITORY
AMERICA
NLS_CURRENCY
$
NLS_ISO_CURRENCY
AMERICA
NLS_NUMERIC_CHARACTERS
.,
NLS_CALENDAR
GREGORIAN
NLS_DATE_FORMAT
YYYY-MM-DD HH24:MI:SS BC
NLS_DATE_LANGUAGE
AMERICAN
NLS_SORT
BINARY
NLS_TIME_FORMAT
HH.MI.SSXFF AM
NLS_TIMESTAMP_FORMAT
YYYY-MM-DD HH24:MI:SS.FF9 BC
NLS_TIME_TZ_FORMAT
HH.MI.SSXFF AM TZR
NLS_TIMESTAMP_TZ_FORMAT
YYYY-MM-DD HH24:MI:SS.FF9TZH:TZM BC
NLS_DUAL_CURRENCY
$
NLS_COMP
BINARY
NLS_LENGTH_SEMANTICS
CHAR
NLS_NCHAR_CONV_EXCP
FALSE

As workaround I created view at oracle side with instead of trigger that dumps inserted value into a variable  then created a foreign table at edb side  and inserted value in that within procedure and it worked.

Regards,
Ali Raza

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by laurenz** [comment] 2021-12-21 07:04
The settings look fine, just like they should.

You said, "if I execute simple insert it works but when I us it in procedure it fails with error."

Is that a procedure on the PostgreSQL side or on the Oracle side?
Can I see the source code of the procedure and how exactly you call it?

**Comment by laurenz** [comment] 2022-01-07 09:49
Any new information that can help me reproduce or understand the problem?

**Comment by alirazaidi** [comment] 2022-01-07 10:28
One thing I noticed that with single statement to insert data in external table it works find but if I add other statements its starts failing.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by laurenz** [comment] 2022-01-07 14:45
You could answer my previous questions:

> Is that a procedure on the PostgreSQL side or on the Oracle side?
> Can I see the source code of the procedure and how exactly you call it?

**Comment by laurenz** [comment] 2022-01-07 14:53
That procedure might well be the problem.
If you cannot share you, I don't know how to help.

**Comment by alirazaidi** [comment] 2022-01-07 15:09
Sorry  client code cannot share thanks for your help

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by laurenz** [comment] 2022-01-07 15:19
Then I guess we should close the issue.

**Comment by alirazaidi** [comment] 2022-01-07 15:24
Sure please close it.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Closed** 2022-01-07 15:27 UTC
Labels: problem, unsolved
