### ISSUE TITLE
PG_INIT getting called repeatedly at server start

### ISSUE THREAD

**Issue by gunavikas** [laurenz/oracle_fdw#266] opened 2018-07-23 08:16 UTC
hi all 
I am using windows system and I have installed PostgreSQL binaries and compiled oracle_fdw using  Visual Studio . when I start the server after loading the extension I see that pg_init is getting called multiple times.
I see this by placing the logs.
any ideas why it is getting called multiple times.

**Comment by laurenz** [comment] 2018-07-23 08:39
`_PG_init` is called for every session that uses oracle_fdw.

This is working as designed, and it should not be a problem.

I assume that you use a version of oracle_fdw before commit 4accfebb33c316d71da73d341dac796df813638c which moved most of the work previously done in `_PG_init` somewhere else to fix a bug.

I recommend that you use the latest code from [git HEAD](https://github.com/laurenz/oracle_fdw/archive/master.zip).

**Comment by gunavikas** [comment] 2018-07-23 08:58
hi, @laurenz    thanks for your response. I have a small doubt whether this

 behavior is similar for any other extensions . for example please look at this example extension _pg_init is even called here repeatedly.

	#ifdef PG_MODULE_MAGIC
	PG_MODULE_MAGIC;
	#endif


	PGDLLEXPORT  void _PG_init(void);
	/* Add a prototype marked PGDLLEXPORT */
	PGDLLEXPORT Datum add_one(PG_FUNCTION_ARGS);

	PG_FUNCTION_INFO_V1(add_one);
	void
	_PG_init(void)
	{
	elog(LOG, "pginit");
	}
	Datum
	add_one(PG_FUNCTION_ARGS)
	{
	int32   arg = PG_GETARG_INT32(0);

	PG_RETURN_INT32(arg + 1);
	}

**Comment by laurenz** [comment] 2018-07-23 09:07
Yes, because that's how it should be. Every database session that uses the shared library will call `_PG_init`.

Why does that bother you?

If you want to avoid it, you have to add the extension to `shared_preload_libraries` so that it is loaded and initialized during postmaster startup, but I don't see the point.

**Comment by gunavikas** [comment] 2018-07-23 09:16
yes, I  know about shared_preload_libraries and I  have actually added my extension to get loaded and initialized during postmaster startup. the problem I have is that I have some memory allocations at postmaster startup which should only be initialized once but even after doing all this _pg_init is getting called repeatedly and my execution is getting failed.

**Comment by laurenz** [comment] 2018-07-23 09:21
Is this question about oracle_fdw at all?

**Comment by laurenz** [comment] 2018-07-23 09:43
Ok, that is because there is no `fork(2)` on Windows, so PostgreSQL has to re-execute the initialization for each backend (look for the `EXEC_BACKEND` macro in the source).

See `SubPostmasterMain` in `src/backend/postmaster/postmaster.c`. This is called from the main function in `src/backend/main/main.c`:

    #ifdef EXEC_BACKEND
        if (argc > 1 && strncmp(argv[1], "--fork", 6) == 0)
             SubPostmasterMain(argc, argv);  /* does not return */
    #endif

But all this seems off-topic for an oracle_fdw issue, so I'll close this one.

**Closed** 2018-07-23 09:44 UTC
Labels: invalid, question
