### ISSUE TITLE
oracle_fdw issue ERROR:  error connecting to Oracle: OCIEnvCreate failed to create environment handle

### ISSUE THREAD

**Issue by prakashrnse** [laurenz/oracle_fdw#306] opened 2019-03-19 10:12 UTC
Hi Team,

am not able to fetch the tables using below command can u please help me on this.

export ORACLE_HOME=/opt/app/oracle/product/12.1.0/client_64/
export LD_LIBRARY_PATH=$ORACLE_HOME

AIBE01PR=# select * from public.be2_admin_nssa_user
AIBE01PR-# ;
ERROR: error connecting to Oracle: OCIEnvCreate failed to create environment handle
DETAIL:

AIBE01PR=# select oracle_diag();
oracle_diag
oracle_fdw 2.1.0, PostgreSQL 11.2, Oracle client 12.1.0.2.0
(1 row)

**Comment by laurenz** [comment] 2019-03-19 11:53
Duplicate of #305.

**Closed** 2019-03-19 11:54 UTC
Labels: duplicate, invalid
