### ISSUE TITLE
Error with "make" command

### ISSUE THREAD

**Issue by krishnakumar-19** [laurenz/oracle_fdw#394] opened 2020-05-06 11:33 UTC
Hi Laurenz,

I have been trying install oracle_fdw in a Centos 7 server where we have postgres 11 installed. I have installed Oracle 19c client and even sqlplus works well to the target Oracle database. But when I try to install oracle_fdw using make command, I get lot of issues. Currently, stuck here..

fyi:
@XXXXXXXXX:/opt/oracle_fdw-ORACLE_FDW_2_2_0>make
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fPIC -I/sdk/include -I/oci/include -I/rdbms/public -I/usr/include/oracle/19.3/client -I/usr/include/oracle/19.3/client64 -I/usr/include/oracle/18.5/client -I/usr/include/oracle/18.5/client64 -I/usr/include/oracle/18.3/client -I/usr/include/oracle/18.3/client64 -I/usr/include/oracle/12.2/client -I/usr/include/oracle/12.2/client64 -I/usr/include/oracle/12.1/client -I/usr/include/oracle/12.1/client64 -I/usr/include/oracle/11.2/client -I/usr/include/oracle/11.2/client64 -I/usr/include/oracle/11.1/client -I/usr/include/oracle/11.1/client64 -I/usr/include/oracle/10.2.0.5/client -I/usr/include/oracle/10.2.0.5/client64 -I/usr/include/oracle/10.2.0.4/client -I/usr/include/oracle/10.2.0.4/client64 -I/usr/include/oracle/10.2.0.3/client -I/usr/include/oracle/10.2.0.3/client64 -I. -I./ -I/usr/pgsql-11/include/server -I/usr/pgsql-11/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o oracle_utils.o oracle_utils.c
oracle_utils.c:22:17: fatal error: oci.h: No such file or directory
 #include <oci.h>

Appreciate any of your help on this regards.

Thanks,

KK

**Comment by laurenz** [comment] 2020-05-06 13:10
How exactly did you install the Oracle client?
Did you install the Oracle client SDK as well?
In what directory are `oci.h` and `libclntsh.so`?

**Comment by krishnakumar-19** [comment] 2020-05-06 13:32
Hi Laurenz,

Thanks for the comment.. here are the details. Let me know if anything else required.

How exactly did you install the Oracle client?
*sudo yum install <package>

Did you install the Oracle client SDK as well?
*No
fyi:
@xxxxx:/home/postgres>rpm -qa|grep oracle
oracle-instantclient19.6-sqlplus-19.6.0.0.0-1.x86_64
oracle-instantclient19.6-basic-19.6.0.0.0-1.x86_64
oracle-instantclient19.6-devel-19.6.0.0.0-1.x86_64
@xxxx:/home/postgres>


In what directory are oci.h and libclntsh.so?
* the directory is:
@xxxxxxx:/usr/lib/oracle/19.6/client64/lib>ls -l libclntsh.so
lrwxrwxrwx 1 root root 17 May  5 14:33 libclntsh.so -> libclntsh.so.19.1
@xxxxxxx:/usr/lib/oracle/19.6/client64/lib>

and the error says, 
oracle_utils.c:22:17: fatal error: oci.h: No such file or directory

**Comment by laurenz** [comment] 2020-05-06 14:58
The `*-devel` package contains the SDK, so you should be fine.

You should have a file `oci.h` in `/usr/include/oracle/19.6/client64`. Is that so?
If not: is there such a file anywhere under `/usr/include/oracle/19.6`?

**Comment by laurenz** [comment] 2020-05-06 15:03
Oh, I see. You are probably not using the latest development version, and paths for 19.6 have been added after the latest release in fb4a9c0.

Use the [latest development version](https://github.com/laurenz/oracle_fdw/archive/master.zip), then it should work.

**Comment by krishnakumar-19** [comment] 2020-05-06 15:54
Thanks Laurenz. Your suggestions fixed the make issue and I could install oracle_fdw successfully. Also I have created the extensions, server and user mapping but stuck like below..

fyi:

postgres=# create extension oracle_fdw;
CREATE EXTENSION
postgres=# create server oracle foreign data wrapper oracle_fdw options (dbserver '//10.36.207.6/FTST');
CREATE SERVER
postgres=# create user mapping for postgres server oracle options (user 'SYSTEM', password 'Tr1t3l3#');
CREATE USER MAPPING
postgres=# create foreign table datawrap_test2 (id int, name varchar(50)) server oracle options (schema 'SYSADM', table 'TEST2');
CREATE FOREIGN TABLE
postgres=# select * from datawrap_test2;
ERROR:  connection for foreign table "datawrap_test2" cannot be established
DETAIL:  ORA-12541: TNS:no listener
postgres=#

I have set tns entries and sqlplus connection goes fine..

@xxxxxxx:/opt/oracle_fdw-master>sqlplus SYSTEM/*****@//xxxxxx1522/FTST

SQL*Plus: Release 19.0.0.0.0 - Production on Wed May 6 11:52:40 2020
Version 19.6.0.0.0

Copyright (c) 1982, 2019, Oracle.  All rights reserved.


Connected to:
Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production
With the Partitioning, Automatic Storage Management, OLAP, Data Mining
and Real Application Testing options

SQL>

Any help ?

**Comment by krishnakumar-19** [comment] 2020-05-06 15:56
Thanks Laurenz. Your suggestions fixed the make issue and I could install oracle_fdw successfully. Also I have created the extensions, server and user mapping but stuck like below..

fyi:

postgres=# create extension oracle_fdw;
CREATE EXTENSION
postgres=# create server oracle foreign data wrapper oracle_fdw options (dbserver '//xxxxx/FTST');
CREATE SERVER
postgres=# create user mapping for postgres server oracle options (user 'SYSTEM', password '****');
CREATE USER MAPPING
postgres=# create foreign table datawrap_test2 (id int, name varchar(50)) server oracle options (schema 'SYSADM', table 'TEST2');
CREATE FOREIGN TABLE
postgres=# select * from datawrap_test2;
ERROR: connection for foreign table "datawrap_test2" cannot be established
DETAIL: ORA-12541: TNS:no listener
postgres=#

I have set tns entries and sqlplus connection goes fine..

@XXXXXXX:/opt/oracle_fdw-master>sqlplus SYSTEM/*****@//xxxxxx1522/FTST

SQL*Plus: Release 19.0.0.0.0 - Production on Wed May 6 11:52:40 2020
Version 19.6.0.0.0

Copyright (c) 1982, 2019, Oracle. All rights reserved.

Connected to:
Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production
With the Partitioning, Automatic Storage Management, OLAP, Data Mining
and Real Application Testing options

SQL>

Any help ?

**Comment by laurenz** [comment] 2020-05-06 19:00
Looks like a duplicate of #393.
As the documentation says:

> Make sure that all necessary Oracle environment variables are set in the environment of the PostgreSQL server process (ORACLE_HOME if you don't use Instant Client, TNS_ADMIN if you have configuration files, etc.)

Check the environment in the `/proc/12345/environ` file, where `12345` is the process ID of the postmaster process (PostgreSQL parent process).

It looks like one of the environment variables that you set to make sqlplus work is not set in the environment of PostgreSQL.

**Comment by krishnakumar-19** [comment] 2020-05-07 05:47
Thanks Laurenz. I referred the duplicate one and the related issue.. let me try to set what's missing.. for now.. I don't see 12345 parent process directory.. the postmaster is running on a different process and below are the variables set.

fyi:
@xxxxx:/proc>ls -l 12345
ls: cannot access 12345: No such file or directory
@xxxxx:/proc>ps -ef|grep -i postmaster
postgres  3941     1  0 May05 ?        00:00:01 /usr/pgsql-11/bin/postmaster -D /pgsql/data
postgres 24548 23809  0 01:40 pts/0    00:00:00 grep --color=auto -i postmaster
@xxxxx:/proc>cd 3941
@xxxxx:/proc/3941>cat environ
LANG=en_US.UTF-8PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/binNOTIFY_SOCKET=/run/systemd/notifyHOME=/home/postgresLOGNAME=postgresUSER=postgresSHELL=/bin/bashPGDATA=/pgsql/dataPG_OOM_ADJUST_FILE=/proc/self/oom_score_adjPG_OOM_ADJUST_VALUE=0PGPORT=5432@xxxxx:/proc/3941>cat environ|xargs -0 -n 1
LANG=en_US.UTF-8
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
NOTIFY_SOCKET=/run/systemd/notify
HOME=/home/postgres
LOGNAME=postgres
USER=postgres
SHELL=/bin/bash
PGDATA=/pgsql/data
PG_OOM_ADJUST_FILE=/proc/self/oom_score_adj
PG_OOM_ADJUST_VALUE=0
PGPORT=5432
@xxxxx:/proc/3941>

**Comment by laurenz** [comment] 2020-05-07 09:33
Right, you got it that you need to replace 12345 with the actual process ID.

So PostgreSQL is lacking the required environment variables.

Assuming that you are using the PGDG PostgreSQL packages and start PostgreSQL with `systemd`, you can proceed like this:

- Add a file `/etc/systemd/system/postgresql-11.service` with the following contents:

      .include /usr/lib/systemd/system/postgresql-11.service

      [Service]
      Environment='TNS_ADMIN=/...'

  You can include other environment variables as required.

- Run `systemctl daemon-reload`

- Restart PostgreSQL with `systemctl restart postgresql-11`

**Comment by krishnakumar-19** [comment] 2020-05-07 11:32
Thanks Laurenz.. but still :( .. not sure what I am missing..

fyi:

@xxxxxx:/usr/lib/systemd/system>cat postgresql-11.service|grep -i environment
Environment=TNS_ADMIN=/usr/lib/oracle/19.6/client64/lib/network/admin
# Note: avoid inserting whitespace in these Environment= lines, or you may
Environment=PGDATA=/var/lib/pgsql/11/data/
Environment=PG_OOM_ADJUST_FILE=/proc/self/oom_score_adj
Environment=PG_OOM_ADJUST_VALUE=0
@xxxxxx:/usr/lib/systemd/system>sudo systemctl daemon-reload
@xxxxxx:/usr/lib/systemd/system>sudo systemctl restart postgresql-11
@xxxxxx:/usr/lib/systemd/system>sudo systemctl status postgresql-11
● postgresql-11.service - PostgreSQL 11 database server
   Loaded: loaded (/etc/systemd/system/postgresql-11.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/postgresql-11.service.d
           └─override.conf
   Active: active (running) since Thu 2020-05-07 07:26:45 EDT; 14s ago
     Docs: https://www.postgresql.org/docs/11/static/
  Process: 9070 ExecStartPre=/usr/pgsql-11/bin/postgresql-11-check-db-dir ${PGDATA} (code=exited, status=0/SUCCESS)
 Main PID: 9076 (postmaster)
   CGroup: /system.slice/postgresql-11.service
           ├─9076 /usr/pgsql-11/bin/postmaster -D /pgsql/data
           ├─9078 postgres: logger
           ├─9080 postgres: checkpointer
           ├─9081 postgres: background writer
           ├─9082 postgres: walwriter
           ├─9083 postgres: autovacuum launcher
           ├─9084 postgres: stats collector
           └─9085 postgres: logical replication launcher

May 07 07:26:45 xxxxxx.advancemags.com systemd[1]: Starting PostgreSQL 11 database server...
May 07 07:26:45 xxxxxx.advancemags.com postmaster[9076]: 2020-05-07 07:26:45.045 EDT [9076] LOG:  listening on IPv6 address "::1", port 5432
May 07 07:26:45 xxxxxx.advancemags.com postmaster[9076]: 2020-05-07 07:26:45.045 EDT [9076] LOG:  listening on IPv4 address "127.0.0.1", port 5432
May 07 07:26:45 xxxxxx.advancemags.com postmaster[9076]: 2020-05-07 07:26:45.046 EDT [9076] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
May 07 07:26:45 xxxxxx.advancemags.com postmaster[9076]: 2020-05-07 07:26:45.049 EDT [9076] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
May 07 07:26:45 xxxxxx.advancemags.com postmaster[9076]: 2020-05-07 07:26:45.057 EDT [9076] LOG:  redirecting log output to logging collector process
May 07 07:26:45 xxxxxx.advancemags.com postmaster[9076]: 2020-05-07 07:26:45.057 EDT [9076] HINT:  Future log output will appear in directory "log".
May 07 07:26:45 xxxxxx.advancemags.com systemd[1]: Started PostgreSQL 11 database server.
@xxxxxx:/usr/lib/systemd/system>psql
psql (11.7)
Type "help" for help.

postgres=# select * from datawrap_test2;
ERROR:  connection for foreign table "datawrap_test2" cannot be established
DETAIL:  ORA-12541: TNS:no listener

**Comment by krishnakumar-19** [comment] 2020-05-07 13:12
Hi Laurenz,

I think this was the intended change.. sorry about that.. but somehow it's not fixing.. 

@xxxxx:/etc/systemd/system>cat postgresql-11.service
.include /usr/lib/systemd/system/postgresql-11.service
[Service]
Environment=PGPORT=5432
#Environment=PGDATA=/var/lib/pgsql/11/data
Environment=TNS_ADMIN=/usr/lib/oracle/19.6/client64/lib/network/admin
Environment=ORACLE_HOME=/usr/lib/oracle/19.6/client64
Environment=LD_LIBRARY_PATH=/usr/lib/oracle/19.6/client64/lib:/usr/pgsql-11/lib
Environment=SQLPLUS=/usr/lib/oracle/19.6/client64
Environment=PGDATA=/pgsql/data
@xxxxx:/etc/systemd/system>

@xxx:/etc/systemd/system>sudo systemctl daemon-reload
@xxx:/etc/systemd/system>sudo systemctl restart postgresql-11

postgres=# select * from datawrap_test2;
ERROR:  connection for foreign table "datawrap_test2" cannot be established
DETAIL:  ORA-12541: TNS:no listener

**Comment by laurenz** [comment] 2020-05-07 14:16
Looks good.

Please verify if `/proc/<pid>/environ` contains the correct settings.

The next step would be to run an SQL Net trace as described [here](https://github.com/laurenz/oracle_fdw/issues/139#issuecomment-263266267) and analyze it.

**Comment by krishnakumar-19** [comment] 2020-05-08 11:10
Thanks Laurenz. I setup the sqlnet.ora and restarted the postgresql.. these are the errors occurring..

fyi:

@xxx:/pgsql/logs>cat cli_9820.trc|grep -i error
[08-MAY-2020 06:57:41:242] nnfttran: Error querying //xxxxxx/FTST of attribute A.SMD errcode 408
[08-MAY-2020 06:57:41:243] nnfttran: Error querying //xxxx/FTST of attribute A.SMD errcode 408
[08-MAY-2020 06:57:41:243] nnfttran: Error querying //xxxx/FTST of attribute A.SMD errcode 408
[08-MAY-2020 06:57:41:246] ntt2err: soc 34 error - operation=1, ntresnt[0]=511, ntresnt[1]=111, ntresnt[2]=0
[08-MAY-2020 06:57:41:246] nserror: entry
[08-MAY-2020 06:57:41:246] nserror: nsres: id=0, op=65, ns=12541, ns2=12560; nt[0]=511, nt[1]=111, nt[2]=0; ora[0]=0, ora[1]=0, ora[2]=0
[08-MAY-2020 06:57:41:247] nsopen: error exit
[08-MAY-2020 06:57:41:247] nscall: error exit
[08-MAY-2020 06:57:41:247] nioqper:  error from nscall
[08-MAY-2020 06:57:41:247] niomapnserror: entry
[08-MAY-2020 06:57:41:247] niqme: reporting NS-12541 error as ORA-12541
[08-MAY-2020 06:57:41:247] niomapnserror: exit
@xxx:/pgsql/logs>

**Comment by laurenz** [comment] 2020-05-08 11:20
You can send me the complete log file to laurenz.albe at cybertec.at, then I can have a look.

**Comment by krishnakumar-19** [comment] 2020-05-08 12:30
I think I have sent it

**Comment by laurenz** [comment] 2020-05-08 12:39
Hmm, I haven't received it. Replace the "at" in my previous comment with "@".

**Comment by krishnakumar-19** [comment] 2020-05-08 12:47
Yeah I did and sent the attachment in email.. let me send it again and see.. thx

**Comment by laurenz** [comment] 2020-05-08 13:24
Got it. Examining the trace:

```none
$ trcasst -e1 cli_14360.trc

Trace Assistant Utility: Version 18.0.0.0.0 Production on May 8, 2020 3:20:16 PM

Copyright (c) 2001, 2018, Oracle.  All rights reserved.


    *************************************************************************
    *                        Trace Assistant                                *
    *************************************************************************

[08-MAY-2020 07:29:12:871] ntt2err: exit
[08-MAY-2020 07:29:12:871] nttcni: exit
[08-MAY-2020 07:29:12:871] nttcon: exit
[08-MAY-2020 07:29:12:871] nserror: entry
[08-MAY-2020 07:29:12:871] nserror: nsres: id=0, op=65, ns=12541, ns2=12560; nt[0]=511, nt[1]=111, nt[2]=0; ora[0]=0, ora[1]=0, ora[2]=0

///////////////////////////////////////////////////////////////
Error found. Error Stack follows:
              id:0
  Operation code:65
      NS Error 1:12541
      NS Error 2:12560
NT Generic Error:511
  Protocol Error:111
        OS Error:0
 NS & NT Errors Translation
12541, 00000 "TNS:no listener" 
 // *Cause: The connection request could not be completed because the listener 
 // is not running. 
 // *Action: Ensure that the supplied destination address matches one of 
 // the addresses used by the listener - compare the TNSNAMES.ORA entry with 
 // the appropriate LISTENER.ORA file (or TNSNAV.ORA if the connection is to 
 // go by way of an Interchange). Start the listener on the remote machine. 
/
12560, 00000 "TNS:protocol adapter error" 
 // *Cause: A generic protocol adapter error occurred. 
 // *Action: Check addresses used for proper protocol specification. Before 
 // reporting this error, look at the error stack and check for lower level 
 // transport errors.For further details, turn on tracing and reexecute the 
 // operation. Turn off tracing when the operation is complete. 
/
00511, 00000 "No listener" 
 // *Cause: The connect request could not be completed because no application 
 // is listening on the address specified, or the application is unable to 
 // service the connect request in a sufficiently timely manner. 
 // *Action: Ensure that the supplied destination address matches one of 
 // the addresses used by the listener - compare the TNSNAMES.ORA entry with 
 // appropriate LISTENER.ORA file (or TNSNAV.ORA if the connection is to go 
 // by way of an Interchange). Start the listener on the remote machine. 
/
///////////////////////////////////////////////////////////////

[08-MAY-2020 07:29:12:871] niomapnserror: entry
[08-MAY-2020 07:29:12:871] niqme: entry
[08-MAY-2020 07:29:12:871] niqme: reporting NS-12541 error as ORA-12541
[08-MAY-2020 07:29:12:871] niqme: exit
[08-MAY-2020 07:29:12:871] niomapnserror: exit



    *************************************************************************
    *                    Trace Assistant has completed                      *
    *************************************************************************
```

I have two explanations for that:

1. There is a firewall that lets sqlplus pass, but not PostgreSQL.

2. You have trouble with SELinux. Try [disabling SELinux](https://linuxize.com/post/how-to-disable-selinux-on-centos-7/) and see if that helps.

**Comment by xxxxxx** [comment] 2020-05-08 13:27
aekljdadfsklgjwrrter

**Comment by xxxxxx** [comment] 2020-05-08 13:27
arwewerwerwe

**Comment by krishnakumar-19** [comment] 2020-05-08 13:35
thanks Laurenz.. Checking on that..

**Comment by krishnakumar-19** [comment] 2020-05-11 16:57
Hi Laurenz,

Sorry for delay in response. But the good news is that, the issue seems to have resolved by few changes inside the commands we gave for creating server..

fyi:

postgres=# create schema kk;
CREATE SCHEMA
postgres=# create server KK1_FDW_SERVER_FTST foreign data wrapper oracle_fdw options (dbserver 'XXXXXX:1522/FTST');
CREATE SERVER
postgres=# create user mapping for postgres server KK1_FDW_SERVER_FTST options (user 'kk', password 'xxxx');
CREATE USER MAPPING
postgres=# import foreign schema "KK" from server KK1_FDW_SERVER_FTST into "kk";
IMPORT FOREIGN SCHEMA
postgres=#  set search_path='kk';
SET
postgres=# \d
            List of relations
 Schema | Name |     Type      |  Owner
--------+------+---------------+----------
 kk     | emp1 | foreign table | postgres
(1 row)

postgres=#

I hope the port no. in the create server command was missing earlier..

Not sure if we might face any issues further but really thank you for your kindness, patience and knowledge.

I would appreciate if you can keep this case open for another week's time.

thanks,

KK

**Closed** 2020-05-29 05:52 UTC
Labels: duplicate, installation, problem
