### ISSUE TITLE
could not load library oracle_fdw.dll: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by dudi123456789** [laurenz/oracle_fdw#315] opened 2019-04-25 03:52 UTC
ERROR:  could not load library "C:/Program Files (x86)/PostgreSQL/9.5/lib/oracle_fdw.dll": %1 is not a valid Win32 application.

********** 错误 **********

ERROR: could not load library "C:/Program Files (x86)/PostgreSQL/9.5/lib/oracle_fdw.dll": %1 is not a valid Win32 application.
SQL 状态: XX000

**Comment by dudi123456789** [comment] 2019-04-25 03:58
hello,When I installed this plug-in, I made the same mistake as above.
May I ask how to solve it? 
Thank you very much。

**Comment by laurenz** [comment] 2019-04-25 13:50
This is a duplicate of #294, #273 and #163.

You seem to be running a 32-bit PostgreSQL binary. Make sure that both `oracle_fdw.dll` and `oci.dll` from the Oracle client are 32-bit executables.

In short, all involved binaries have to be either 32-bit or 64-bit binaries.

**Closed** 2019-05-28 08:29 UTC
Labels: duplicate, problem
