### ISSUE TITLE
Oracle_FDW: Oracle to postgres bad data move

### ISSUE THREAD

**Issue by ravisql09** [laurenz/oracle_fdw#412] opened 2020-07-22 18:11 UTC
Hi,

I can able to inserted corrupted record directly in postgres.

But while fetching same record from oracle using Oracle_fdw ,I am seeing the following error.I learned from your comments on other blogs,we need to correct source data.Is there anyway we can move data as it is from oracle to postgres.

**ERROR: invalid byte sequence for encoding "UTF8": 0xe6 0x96 0xe3**

Thanks

**Comment by laurenz** [comment] 2020-07-25 03:47
This is a duplicate of #348.

No, you cannot import corrupt string data into PostgreSQL, it is not as negligent as Oracle with data corruption.

You will either have to fix the data in Oracle or not move them to PostgreSQL.

**Comment by ravisql09** [comment] 2020-07-25 07:27
Thanks for your response Laurenz!

But I tried to copy the bad record from oracle and able to insert same in postgres too (using export and import in OS without any 3rd party tools).As per #348 ,It suppose not insert this bad record in postgres right?

Please let me know,if I am missing anything here?

**Comment by ravisql09** [comment] 2020-07-26 07:23
Hi Laurenz,

Can you help me with the following?

1) Example of non Unicode string which wont allow in postgres?
2) Find same oracle like query to find in postgres all non unique characters
3)following query in oracle can work only max 2000 characters,means we need to separate string using sub-string and test,any alternative?
SELECT rowid
FROM bad_table
WHERE convert(
         convert(
            bad_column,
            'AL16UTF16'
         ),
         (SELECT value
          FROM nls_database_parameters
          WHERE parameter = 'NLS_CHARACTERSET'
         ),
         'AL16UTF16'
      ) <> bad_column;

Thanks

**Comment by laurenz** [comment] 2020-08-01 05:00
I cannot think of a query that would work for longer strings.
Unfortunately, Oracle's support for long strings (`CLOB`) is rather shaky.

Perhaps the [Database Migration Assistant for Unicode](https://docs.oracle.com/cd/E71288_01/DUMAG/ch4_basic_tasks.htm#DUMAG343) can help.

**Closed** 2020-09-01 09:45 UTC
Labels: duplicate, problem
