### ISSUE TITLE
extension oracle_fdw depends on schema public

### ISSUE THREAD

**Issue by jerome-peng** [laurenz/oracle_fdw#289] opened 2019-01-18 02:41 UTC
My English is not so good. - -

After change extension oracle_fdw schema from "public" to my schema "report":

    report=# alter extension oracle_fdw SET SCHEMA report;
    ALTER EXTENSION

then i try to drop schema "public":

    report=# drop schema public;
    ERROR:  cannot drop schema public because other objects depend on it
    DETAIL:  extension oracle_fdw depends on schema public
    server server_99 depends on foreign-data wrapper oracle_fdw
    foreign table xxx depends on server server_99

    report=> select oracle_diag();
                                    oracle_diag                                 
    ----------------------------------------------------------------------------
     oracle_fdw_read_committed 2.0.1, PostgreSQL 10.6, Oracle client 11.2.0.4.0
    (1 row)

    report=> select version();
                                                     version
    ---------------------------------------------------------------------------------------------------------
     PostgreSQL 10.6 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18), 64-bit
    (1 row)

**Comment by laurenz** [comment] 2019-01-18 09:04
That is surprising. I just tried on my system, and it works here.

What do you get for

    \dx oracle_fdw

before and after the `ALTER EXTENSION`?

Also, what do you get before and after for

    SELECT d.refclassid::regclass, d.refobjid::regnamespace
    FROM pg_depend AS d
       JOIN pg_extension AS e ON e.oid = d.objid
    WHERE e.extname = 'oracle_fdw';

After the `ALTER EXTENSION` the dependency of the extension should be on the new schema.

**Comment by jerome-peng** [comment] 2019-01-23 06:41
[jerome@pg ~]$ psql -p 55430 -U report
psql.bin (10.6)
Type "help" for help.

report=> \dx oracle_fdw
                      List of installed extensions
    Name    | Version | Schema |              Description               
------------+---------+--------+----------------------------------------
 oracle_fdw | 1.1     | report | foreign data wrapper for Oracle access
(1 row)

report=> SELECT d.refclassid::regclass, d.refobjid::regnamespace
report-> FROM pg_depend AS d
report->    JOIN pg_extension AS e ON e.oid = d.objid
report-> WHERE e.extname = 'oracle_fdw';
  refclassid  | refobjid 
--------------+----------
 pg_namespace | public
(1 row)

**Comment by laurenz** [comment] 2019-01-23 08:16
That looks bad, like some kind of data corruption.
The only schema on which an extension depends should be the extension schema.

I see that you are using some old and modified version of oracle_fdw, but that shouldn't be a problem, because this is handled by core code.

Are you using standard PostgreSQL?

The simplest way to deal with this would probably be

    DROP EXTENSION oracle_fdw CASCADE;
    CREATE EXTENSION oracle_fdw SCHEMA report;

But that will drop all objects that depend on oracle_fdw. Perhaps you can `pg_dump` the dependent objects first and then restore them.

Another idea, if that's possible for you, might be

    ALTER EXTENSION oracle_fdw SET SCHEMA public;
    ALTER SCHEMA public RENAME TO report;
    REVOKE CREATE ON SCHEMA report FROM PUBLIC;

I'd be interested to know how you got into that mess.
Can you start with a clean new database and come up with a sequence of SQL statements that reproduces the problem? That way I could identify the problem that caused this.

**Comment by jerome-peng** [comment] 2019-01-23 09:16
thanks for you!

i can't drop extension for some reason.

i also try to reappear it, but failured;

On my new case ,i can changed the schema from "public" to "report", then i can drop "public" successfuly.

**Comment by laurenz** [comment] 2019-01-23 09:30
What is the reason you cannot drop the extension?
Perhaps it works if you first run

    ALTER EXTENSION oracle_fdw SET SCHEMA public;

Perhaps your database has somehow become corrupted, and you should `pg_dump` it and restore it to a new cluster to get rid of the corruption.

**Comment by jerome-peng** [comment] 2019-01-24 00:50
My database is working well except this problem. And that was not big deal for me，i can't take risks to drop extension.

Maybe you can close this problem  because i can't reproduces it in a new database.

Thanks a lot.

**Comment by laurenz** [comment] 2019-01-24 05:13
Thanks for the feedback.
Yes, in that case we should close the issue.

But it gives me an uneasy feeling that this can happen at all.
It must be either a core PostgreSQL bug or data corruption of some description, both of which are not nice.
So if you ever get new information about this, I'd be interested to know.

You didn't happen to directly modify the system catalogs, did you?

**Closed by laurenz** 2019-01-24 05:13 UTC
Labels: problem

**Comment by jerome-peng** [comment] 2019-01-25 01:07
yes, i will give your message if i get new information about that.

i didn't modify the system catalogs.
