### ISSUE TITLE
invalid byte sequence for encoding "UTF8": 0xe3 0x4e 0x9c

### ISSUE THREAD

**Issue by bartonjd** [laurenz/oracle_fdw#51] opened 2016-01-30 00:35 UTC
I am trying to select a varchar field from my foreign data wrapper and keep getting the error:
invalid byte sequence for encoding "UTF8": 0xe3 0x4e 0x9c
CONTEXT:  converting column "spbpers_ssn" for foreign table scan of "spbpers", row 1

I managed to add an elog command to the oracle_fdw and determined that this is the value that is being returned by oracle:▒N▒/u▒▒O8▒▒ΰ▒U▒▒▒2▒▒ ▒▒_+S

My best guess is that the company that produced the software which created the table has it set for encryption at rest? When I query in sqlplus I am able to see the column values just fine but in postgres everything I have tried fails. Every other field in the table works. Any thoughts?

**Comment by laurenz** [comment] 2016-01-30 20:19
The most likely explanation is that there are garbage characters in your Oracle database.

I'd like to know what your Oracle database character set is:

    SELECT value FROM nls_database_parameters WHERE parameter = 'NLS_CHARACTERSET';

Then I'd like to know your PostgreSQL database encoding:

    SHOW server_encoding;

The funny thing is that the string you show is weird, but correctly encoded UTF-8, the strange character is Unicode code point (hex) 2592.
The sequence "0xe3 0x4e 0x9c" does not appear in it.
How does the string appear when displayed with sqlplus?
What is the value of ``NLS_LANG`` for the sqlplus session?

Since oracle_fdw tells us that the line with the problem is line one, you should be able to get the problematic value in sqlplus with

    SELECT spbpers_ssn FROM pbpers WHERE ROWNUM = 1;

It would be interesting to know the exact hex contents of that value:

    SELECT dump(spbpers_ssn, 16) FROM pbpers WHERE ROWNUM = 1;

**Comment by bartonjd** [comment] 2016-02-01 18:16
I appreciate your quick response, I unfortunately can't send the text
because it is sensitive information but I did learn today that the column
is encrypted and that is why we were getting garbage characters. I am sure
you are just as relieved as I am to know that it wasn't a problem with the
wrapper.

As a side note, when I attempt to join two oracle_fdw tables in postgres I
get  this error:
*ERROR:  Internal oracle_fdw error: encountered unknown node type 524.*

I haven't found any documentation on what this means

**Comment by laurenz** [comment] 2016-02-12 08:01
Could you tell me the query that leads to this error, along with the PostgreSQL table and foreign table definitions involved?

**Comment by laurenz** [comment] 2016-02-15 14:12
Also, which PostgreSQL version is this?

**Comment by bartonjd** [comment] 2016-02-17 17:46
So as it turned out it was merely because the field was encrypted that we
were getting the error. I can't remember if I reported on that to you or
not? It is postgres 9.45.  I will ask if I can get permission to send the
table ddl

**Comment by laurenz** [comment] 2016-02-22 11:16
I am trying to fix the error

    ERROR: Internal oracle_fdw error: encountered unknown node type 524.

that you reported.

I'd need the query that caused the error.

**Comment by bartonjd** [comment] 2016-02-22 15:48
SELECT      spriden_pidm            AS ban_pidm,

                spriden_id              AS f_number,

                spriden_last_name       AS last_name,

                spriden_first_name      AS first_names,

                spriden_mi              AS middle_names,

                spbpers_pref_first_name AS calledby_name,

                spbpers_ssn,

                CASE WHEN TRIM(spbpers_ssn) = '' THEN ''

                    WHEN spbpers_ssn IS NULL THEN ''

                     ELSE SUBSTR(spbpers_ssn,1,3) || '-' ||
SUBSTR(spbpers_ssn,4,2) || '-' || SUBSTR(spbpers_ssn,6,4)

                END AS emp_ssn,

                TO_CHAR(spbpers_birth_date, 'YYYY-MM-DD') AS birth_date,

                home_street,

                home_city,

                home_state,

                home_zipcode,

                CASE WHEN spbpers_sex = 'N' THEN 'D'

                     ELSE spbpers_sex

                END                     AS gender_code

    FROM        spriden s

    JOIN        spbpers p ON s.spriden_pidm = p.spbpers_pidm

    LEFT JOIN   (

                    SELECT  a.spraddr_pidm,

                            CASE WHEN TRIM(a.spraddr_street_line1) IS NULL
THEN ''

                                 WHEN TRIM(a.spraddr_street_line2) IS NULL
THEN TRIM(a.spraddr_street_line1)

                                 WHEN TRIM(a.spraddr_street_line3) IS NULL
THEN TRIM(a.spraddr_street_line1) || '\n' || TRIM(a.spraddr_street_line2)

                                 ELSE TRIM(a.spraddr_street_line1)   ||
'\n' || TRIM(a.spraddr_street_line2) || '\n' || TRIM(a.spraddr_street_line3)

                            END AS home_street,

                            a.spraddr_city          AS home_city,

                            a.spraddr_stat_code     AS home_state,

                            a.spraddr_zip           AS home_zipcode

                     FROM   spraddr a

                     JOIN   (

                                SELECT  spraddr_pidm,

                                        MAX(spraddr_seqno) AS max_seq

                                FROM    spraddr

                                GROUP BY spraddr_pidm

                           ) la ON (a.spraddr_pidm = la.spraddr_pidm AND
a.spraddr_seqno = la.max_seq)

                     WHERE spraddr_atyp_code = 'MA'

                ) a ON s.spriden_pidm = a.spraddr_pidm

    WHERE       spriden_id = '23423402'

      AND       spriden_entity_ind = 'P'

      AND       spriden_change_ind IS NULL
    ORDER BY    spriden_pidm, spriden_change_ind

**Comment by laurenz** [comment] 2016-02-22 15:58
Thanks!

Can you tell me the ``CREATE TABLE`` and ``CREATE FOREIGN TABLE`` statements used to create these tables?

**Comment by bartonjd** [comment] 2016-02-22 17:26
Unfortunately my employer will not allow me to disclose that as it is
somewhat sensitive :/

**Comment by laurenz** [comment] 2016-02-23 10:51
Thanks for asking.
I'll see what I can do without the information.

**Comment by laurenz** [comment] 2016-02-23 14:42
I have just committed 1779f4d90f72530fb14225d6035726fac7f4e559 which should fix the problem.
Could you check with the latest code?

**Comment by bartonjd** [comment] 2016-02-24 23:05
After trying your latest commit I am only getting the "invalid byte
sequence for encoding "UTF8": 0xe3 0x4e 0x9c" error now which is a result
of an encrypted field.

**Closed** 2016-02-26 13:22 UTC
Labels: bug

**Comment by mpatzwah** [comment] 2017-03-21 13:50
Hi Laurenz,
i have a similar Problem (Oracle 12.2 (Yes, very new :-) ) on Windows with Postgres 9.6
ps >select * from dept;
FEHLER:  ungültige Byte-Sequenz für Kodierung »UTF8«: 0xdf 0x74
ps >SHOW server_encoding;
 server_encoding
-----------------
 UTF8
(1 Zeile)

This is the Table:
    DEPTNO DNAME          LOC          
---------- -------------- -------------
        10 ACCOUNTING     NEW YORK     
        20 RESEARCH       DALLAS       
        30 SALES          CHICAGO      
        40 OPERATIONS     BOSTON       

On Oracle:
SELECT value FROM nls_database_parameters WHERE parameter = 'NLS_CHARACTERSET';
AL32UTF8

Do you have any Idea?
Thanks in advance
Marco from Munich

**Comment by bartonjd** [comment] 2017-03-21 14:02
When I encountered this issue it was actually due to my permissions.  I don't really know if that will help or not but I thought I should share my experience with this issue.

**Comment by mpatzwah** [comment] 2017-03-21 14:07
Thanks for the quick reply!
, what permission do i need ?
I have connect role and the user account is unlocked:
U:\>sqlplus scott/tiger

SQL*Plus: Release 12.2.0.1.0 Production on Di Mrz 21 15:07:07 2017
Copyright (c) 1982, 2016, Oracle.  All rights reserved.
Letzte erfolgreiche Anmeldezeit: Di Mrz 21 2017 14:57:18 +01:00
Verbunden mit:
Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production

**Comment by laurenz** [comment] 2017-03-21 14:48
Please don't hijack another issue, open your own!

0xDF74 is not valid UTF-8, so you must have some garbage in your Oracle database.
In ISO 8859-1 that byte sequence would be &ldquo;&szlig;t&rdquo;, so it might be incorrectly encoded German text from before the spelling reform.

**Comment by mpatzwah** [comment] 2017-03-21 14:49
sorry, i will open a new question

**Comment by bartonjd** [comment] 2017-03-21 17:36
On the permissions I am not sure as I wasn't administrator, but one other
thing that caused this, if the table you are attempting to connect to is a
view.
