### ISSUE TITLE
Is there any way can i select ST_GEOMETRY type (ESRI ArcSDE)  from oracle

### ISSUE THREAD

**Issue by alloclhdwcy** [laurenz/oracle_fdw#695] opened 2024-07-25 03:51 UTC
Hi laurenz,

I tried the way from [311](https://github.com/laurenz/oracle_fdw/issues/311):

CREATE FOREIGN TABLE transftest20240717 (
    FEATID text, 
    SHAPE geometry
)  SERVER oradb OPTIONS(schema 'SZSW_GIS_SDE',table '(SELECT FEATID, **SDO_GEOMETRY(SDE.ST_asText(SHAPE))** AS SHAPE FROM TEST20240717)');

But i get the following error:

ERROR:  error describing remote table: OCIStmtExecute failed to describe table
DETAIL:  ORA-00903: invalid table name

Please help how to solve this problem ant Is there any way can i select ST_GEOMETRY type (ESRI ArcSDE).

**Comment by laurenz** [comment] 2024-07-25 07:01
This is a duplicate of #678.

As documented: if you define a foreign table based on a query, you must not specify a `schema`.

**Comment by alloclhdwcy** [comment] 2024-07-25 10:37
I'm very sorry and thank you for your time!

**Comment by laurenz** [comment] 2024-07-25 12:07
No problem at all; you are welcome.

**Closed by laurenz** 2024-07-25 12:07 UTC
Labels: duplicate, problem
