### ISSUE TITLE
Calling oracle functions from postgress

### ISSUE THREAD

**Issue by pistoletov1974** [laurenz/oracle_fdw#202] opened 2017-09-20 14:31 UTC
Hi ! How i can call oracle foreign  stored procedures (functions) like a postgress function. Does it possible?

**Comment by laurenz** [comment] 2017-09-20 14:42
This looks like a duplicate of #187. Does the workaround suggested there help you?

**Closed by laurenz** 2017-09-20 14:42 UTC
Labels: duplicate, question

**Comment by pistoletov1974** [comment] 2017-09-20 14:46
Thank you! I just try this way!

**Comment by laurenz** [comment] 2017-09-20 14:56
Sorry, I closed the issue by mistake. Don't hesitate to re-open it and continue discussing the problem if you want to.

**Comment by pistoletov1974** [comment] 2017-10-06 08:35
Hi! Thank you gor yours advice. I just try to do this with table. This is my foreign table:
```
CREATE FOREIGN TABLE import.saldo (
  "CODE_7" BIGINT NOT NULL,
  "SALDO" REAL
) 
SERVER dataheap
OPTIONS (
  schema 'ADDF',
  "table" 'GET_SALDO');
```

and oracle table:
```
SQL> describe addf.get_saldo;
 Name                                      Null?    Type
 ----------------------------------------- -------- ----------------------------
 CODE_7                                    NOT NULL NUMBER(7)
 SALDO                                              NUMBER(12,2)
```


and sql and result:

```
UPDATE import.saldo SET "CODE_7" = '2000342' RETURNING "SALDO";

ОШИБКА:  no primary key column specified for foreign Oracle table
DETAIL:  For UPDATE or DELETE, at least one foreign table column must be marked as primary key column.
HINT:  Set the option "key" on the columns that belong to the primary key.
```
i am not a owner of oracle table but oracle admin said me, that oracle table have primary key. Why my request does not work?  @laurenz

**Comment by laurenz** [comment] 2017-10-06 09:03
You have to tell PostgreSQL what the primary key column is:

    ALTER FOREIGN TABLE saldo
       ALTER "CODE_7" OPTIONS (ADD key 'true');
