### ISSUE TITLE
Performance issue SDE geometry

### ISSUE THREAD

**Issue by GohanSSj2** [laurenz/oracle_fdw#300] opened 2019-02-15 15:04 UTC
hi,

I have a table in Oracle database with SDE Geometry.
To view data, i create i view to convert SDE Geometry to WKT (sde.st_asText).
I use oracle_fdw to read this view and convert geometry data to Postgis geometry.

query SELECT is very slow on foreign data table

**In Oracle:**
Table AAC -> View AAC_P (with st_asText)
**In PostgreSQL:**
Foreign data table aac_p -> aac (Postgis geometry)

In SQL Developper (connected to Oracle database):
`SELECT * FROM AAC` => 1064 rows in 0,54 seconds
`SELECT * FROM AAC_P` => 1064 rows in 1,67 seconds

In pgAdmin (connected to PostgreSQL database):
`SELECT objectid,id_interne,qualite_georef,precision_geo,date_maj FROM bassin_aesn.aac` => 1064 rows in 113ms (I can't do SELECT * because the geometry column can't be read by oracle_fdw extension)
`SELECT * FROM aac_p` => 1064 rows in **15 seconds**

I don't understand why is too long to read data.

Result `EXPLAIN VERBOSE SELECT * FROM aac_p` in PostgreSQL:
```
"Foreign Scan on bassin_aesn.aac_p  (cost=10000.00..20000.00 rows=1000 width=162)"
"  Output: date_maj, id_interne, objectid, precision_geo, qualite_georef, geom"
"  Oracle query: SELECT /*80c44330cee1f65d08fc48175b8f29c0*/ r1."DATE_MAJ", r1."ID_INTERNE", r1."OBJECTID", r1."PRECISION_GEO", r1."QUALITE_GEOREF", r1."GEOM" FROM "BASSIN_AESN"."AAC_P" r1"
"  Oracle plan: SELECT STATEMENT"
"  Oracle plan:   TABLE ACCESS FULL AAC"
```
**EDIT1 :**
network consumption is very high when i run query `SELECT * FROM aac_p` in PostgreSQL

Thanks for your help

**Comment by laurenz** [comment] 2019-02-17 18:38
With &ldquo;SDE geometry&rdquo; you mean the data format used by ArcSDE, right?
Yes, there is no support for those in oracle_fdw.
Oracle's `SDO_GEOMETRY` would be supported...

Which data type does the Oracle view `AAC_P` use for the `st_astext` result?
If it is a `CLOB` or `BLOB`, that would be one explanation for slowness, because there is an Oracle limitation that doesn't allow oracle_fdw to fetch several such rows in one client-server round trip.

Second, pgAdmin is known to be slow when displaying large result sets, so that could be another reason for the speed you are observing.

What do you get for

    EXPLAIN (ANALYZE) SELECT * FROM aac_p;

I am surprised that the network is loaded with that query; if there are `CLOB`s or `BLOB`s involved, I'd expect the network latency to be a bigger problem than the bandwidth.

If you have a recent version of Oracle that supports `VARCHAR2`s with a size of more than 4000, maybe using that data type would speed up processing.

**Comment by GohanSSj2** [comment] 2019-02-18 14:26
hi,

Yes, SDE geometry is ESRI Format (ArcGIS).
I convert SDE geometry to WKT format to read data with oracle_fdw.

> Which data type does the Oracle view `AAC_P` use for the `st_astext` result?

WKT column is CLOB. 

> What do you get for ```EXPLAIN (ANALYZE) SELECT * FROM aac_p;```

I run `EXPLAIN (ANALYZE) SELECT * FROM aac_p LIMIT 2;` because i'm not at work this week.
Result:
`"Limit  (cost=10000.00..10020.00 rows=2 width=162) (actual time=160.533..565.533 rows=2 loops=1)"
"  ->  Foreign Scan on aac_p  (cost=10000.00..20000.00 rows=1000 width=162) (actual time=160.517..565.509 rows=2 loops=1)"
"        Oracle query: SELECT /*80c44330cee1f65d08fc48175b8f29c0*/ r1."DATE_MAJ", r1."ID_INTERNE", r1."OBJECTID", r1."PRECISION_GEO", r1."QUALITE_GEOREF", r1."GEOM" FROM "BASSIN_AESN"."AAC_P" r1"
"Planning Time: 73437.082 ms"
"Execution Time: 565.813 ms"`

**Comment by laurenz** [comment] 2019-02-18 18:03
Ok, if it is a `CLOB`, that explains the slow performance.
This is a limitation of Oracle that I cannot overcome.

**Comment by laurenz** [comment] 2019-02-18 18:13
For the record: This is a duplicate of #68.

**Comment by GohanSSj2** [comment] 2019-02-25 13:25
This is the link to ESRI documentation and the return type of st_astext function : 
[](http://desktop.arcgis.com/en/arcmap/10.3/manage-data/using-sql-with-gdbs/st-astext.htm)

I continue the testing

**Comment by laurenz** [comment] 2019-02-25 15:36
Are there functions to convert it to `SDO_GEOMETRY`?
That is supported by oracle_fdw.

Other than that, I have no good ideas.

**Comment by GohanSSj2** [comment] 2019-02-25 16:33
Yes it's possible.
[ST_AsText() then SDO_Geometry()](https://gis.stackexchange.com/questions/187686/st-geometry-to-sdo-geometry)
But i don't want to use Oracle Spatial (last resort only!)

I can't convert data to `VARCHAR2`. BLOB value is too long: 
`SELECT ID_INTERNE, LENGTH(GEOM) AS L FROM BASSIN_AESN.AAC_P ORDER BY L DESC;`
Result: 
```
ID_INTERNE	L
40866_233	103100
AAC1052_233	85726
AAC0194_233	44008
AAC6013_233	42818
34265_233	42716
```
I tried to reduce the data length: 
`SELECT ID_INTERNE, LENGTH(REGEXP_REPLACE(GEOM,'(\.[[:digit:]]{8})','')) AS L FROM BASSIN_AESN.AAC_P ORDER BY L DESC;`
But that is not enough:
```
ID_INTERNE	L
40866_233	48524
AAC1052_233	40348
AAC0194_233	20716
AAC6013_233	20156
34265_233	20108
```

I continue the testing

**Comment by laurenz** [comment] 2019-02-26 10:21
`SDO_GEOMETRY` is also included in Oracle Locator, which comes at no additional cost, as far as I know.

You would only use the data type in a view to make transfer to PostgreSQL better.
But of course calling many conversion functions is also not cheap...

**Comment by GohanSSj2** [comment] 2019-02-27 10:06
ahh ok thanks. I look that with my DBA.
For me, it's now the only solution. Data are too large for `VARCHAR2`.
I'll make feedback soon.

**Comment by GohanSSj2** [comment] 2019-02-27 11:23
Final tests: 

1. With sde.ST_AsText() function in oracle view and read them with oracle_fdw
```
EXPLAIN (ANALYZE) SELECT * FROM bassin_aesn.aac_p;
```
Result
```
"Foreign Scan on aac_p1  (cost=10000.00..20000.00 rows=1000 width=162) (actual time=12.216..13744.271 rows=1064 loops=1)"
"  Oracle query: SELECT /*8b215c0b542d7a0ee198ad9de6e2d711*/ r1."DATE_MAJ", r1."ID_INTERNE", r1."OBJECTID", r1."PRECISION_GEO", r1."QUALITE_GEOREF", r1."GEOM" FROM "BASSIN_AESN"."AAC_P1" r1"
"Planning Time: 10.890 ms"
"Execution Time: 13746.508 ms"
```

2. With sdo_geometry(sde.st_astext()) in oracle view and read them with oracle_fdw
```
EXPLAIN (ANALYZE) SELECT * FROM bassin_aesn.aac_p;
```
Result
```
"Foreign Scan on aac_p  (cost=10000.00..20000.00 rows=1000 width=162) (actual time=650.734..3432.634 rows=1064 loops=1)"
"  Oracle query: SELECT /*80c44330cee1f65d08fc48175b8f29c0*/ r1."DATE_MAJ", r1."ID_INTERNE", r1."OBJECTID", r1."PRECISION_GEO", r1."QUALITE_GEOREF", r1."GEOM" FROM "BASSIN_AESN"."AAC_P" r1"
"Planning Time: 239.568 ms"
"Execution Time: 3433.095 ms"
```

3. Conclusion

It's more efficient to 
- convert SDE Geometry to WKT then convert WKT to SDO Geometry in Oracle
- read SDO geometry with oracle_fdw in PostgreSQL

than
- convert SDE Geometry to WKT in Oracle
- read WKT with oracle_fdw in PostgreSQL
- convert WKT to PostGIS in PostgreSQL

**Comment by laurenz** [comment] 2019-02-27 13:59
Thanks for the experiments and the feedback!

That confirms that the bottleneck is the Oracle limitation that no prefetch is possible with LOB and LONG columns.

**Closed** 2019-02-28 12:53 UTC
Labels: duplicate, problem

**Comment by laurenz** [comment] 2023-05-17 08:29
The performance problem with Oracle LOBs has been improved with commit d679a73d02057fd674fc78fe5f25183e5c9a172b.
You are welcome to test if the current development version works better for you.
