### ISSUE TITLE
Join PostgreSQL table with foreing table

### ISSUE THREAD

**Issue by danielesevegnani** [laurenz/oracle_fdw#30] opened 2015-04-14 14:47 UTC
Hi Laurenz,
I'm trying your powerful software and I have bad performance during the join between a PostgreSQL table A with foreing Oracle TABLE table B.
are a simple join like 
SELECT * from A inner join B on A.id = B.id limit 1;
or
SELECT * from A inner join B on A.id = B.id  where A.id in (select id from A limit 2)

but if I put the where condition on the table A it's works perfectly:
SELECT * from A inner join B on A.id = B.id  where A.id = 5;

**Comment by laurenz** [comment] 2015-04-15 07:13
That is not surprising.

To be certain, have a look at the EXPLAIN output for your queries.

In the last query, the optimizer is smart enough to infer that `B.id = 5`, so it will pass that as a condition to the foreign scan, which in turn will execute something like `SELECT * FROM "B" WHERE "ID" = 5`.

For the first two examples, the optimizer cannot deduce a condition for the foreign scan, so there is no choice but to pull the whole table from Oracle: `SELECT * FROM "B"`. That will of course lead to bad performance.

Your second example looks complicated enough to make it credible that there is no way to translate that into a simple condition for the foreign scan, but your first example looks deceptively simple. Note, however, that you cannot know in advance how many rows you have to read from `B` until you get one that matches a row in `A`.

See the section "WHERE conditions" in the README for more general advice.

**Comment by danielesevegnani** [comment] 2015-04-15 07:43
thanks a lot for your quick reply.
what I do not understand is why these two queries I thought equivalents give very different results
SELECT * from B where B.id in (1,2,3,4,5,6,7,8,9,10) quick
SELECT * from B where B.id in (SELECT A.id from A limit 10) scan all table B

What I need is to select some rows from a Postgres table and do a join with the respective rows of a  large table in Oracle.

**Comment by laurenz** [comment] 2015-04-15 09:16
The only chance you have to speed up such a query is to use join syntax, force a nested loop join and impose a LIMIT, like this:

    SET enable_hashjoin=off;
    SET enable_mergejoin=off;
    SELECT B.* FROM B JOIN A USING (id) LIMIT 10;

Then only the required number of rows should be fetched.
That's not equivalent to your query, but maybe it helps.

It is of course annoying to have to force the optimizer like that.
The problem is that it is impossible to get realistic cost estimates for the Oracle query.
Maybe I can improve this somewhat; I'll look.

**Comment by laurenz** [comment] 2015-04-15 10:00
I have just committed cb2b1d1cdca77cb3850ec285286e3fb3ecde7068, now the number of rows is reflected in the total cost estimate.
That should improve queries like the one I quoted above.
If you can, give it a try.

**Comment by danielesevegnani** [comment] 2015-04-15 12:56
Thank you very much for your commit, unfortunately the query still scan the entire oracle table B.
I also tried without success.
SELECT B.* FROM A JOIN B USING (id) WHERE (condition to filter a few lines of A)

**Comment by laurenz** [comment] 2015-04-15 13:50
Yes, that will probably not work.
I think that the only way you can get it to work is with a `LIMIT` clause as described above.

In many cases joins involving foreign data wrappers are inefficient, because all rows have to be retrieved. Try for a nested loop join with a `LIMIT` clause.

Or, even better, limit the number of rows retrieved from `B` with a `WHERE` condition that filters on `B`.

**Comment by laurenz** [comment] 2015-04-18 14:00
Another (ugly) idea:
First query `A`, then construct an SQL statement like `SELECT * FROM B WHERE id IN (...)` from the results and execute that.

**Closed** 2015-04-28 09:31 UTC
Labels: problem
