### ISSUE TITLE
degradade perfomance

### ISSUE THREAD

**Issue by andreymarkin80** [laurenz/oracle_fdw#291] opened 2019-01-31 11:53 UTC
past some time perfomance is down.
time reading sqlplus to RADCHECK_SP_VW is less a 1sec

    # time echo "select count(*) from radcheck_sp_vw;" | /opt/oracle/instantclient_12_2/sqlplus

    SQL*Plus: Release 12.2.0.1.0 Production on Thu Jan 31 13:31:11 2019

    Copyright (c) 1982, 2016, Oracle.  All rights reserved.

    Last Successful login time: Thu Jan 31 2019 13:31:09 +03:00

    Connected to:
    Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
    With the Partitioning, OLAP, Advanced Analytics and Real Application Testing options

    SQL>
      COUNT(*)
    ----------
        590728

    SQL> Disconnected from Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
    With the Partitioning, OLAP, Advanced Analytics and Real Application Testing options

    real    0m0.612s
    user    0m0.016s
    sys    0m0.008s

time reading psql to radcheck is more then 10sec

    # select count(*) from radcheck2;
     count  
    --------
     590728
    (1 row)

    Time: 89149.732 ms

    # \det+ radcheck;
                             List of foreign tables
     Schema |   Table   | Server |        FDW Options         | Description
    --------+-----------+--------+----------------------------+-------------
     public | radcheck  | oracle | ("table" 'RADCHECK_SP_VW') | 

    # select oracle_diag();
                             oracle_diag                          
     --------------------------------------------------------------
      oracle_fdw 1.5.0, PostgreSQL 9.6.3, Oracle client 12.2.0.1.0
    (1 row)

all new foreign table has low perfomance! (with new server so)

**Comment by laurenz** [comment] 2019-01-31 12:10
Yes, aggregates are not pushed down, so the whole table is pulled to PostgreSQL for the counting.

This is a duplicate of #288; maybe the workaround I gave there can help you.

**Comment by andreymarkin80** [comment] 2019-01-31 12:19
foreign table was create by command:
CREATE FOREIGN TABLE radcheck (id int, username varchar, attribute varchar, op varchar, value varchar) server oracle options (table 'RADCHECK_SP_VW');

**Comment by andreymarkin80** [comment] 2019-01-31 12:22
now I have too long refresh

refresh materialized view CONCURRENTLY radcheck2
# \d+ radcheck2;
                       Materialized view "public.radcheck2"
  Column   |       Type        | Modifiers | Storage  | Stats target | Description 
-----------+-------------------+-----------+----------+--------------+-------------
 id        | integer           |           | plain    |              | 
 username  | character varying |           | extended |              | 
 attribute | character varying |           | extended |              | 
 op        | character varying |           | extended |              | 
 value     | character varying |           | extended |              | 
Indexes:
    "racheckid" UNIQUE, btree (id)
    "radcheck_username" btree (username, attribute)
View definition:
 SELECT radcheck.id,
    radcheck.username,
    radcheck.attribute,
    radcheck.op,
    radcheck.value
   FROM radcheck;

**Comment by laurenz** [comment] 2019-01-31 12:34
About the long duration of the materialized view refresh:

How long does it take? For how many rows?
Does it take much longer than running the same query via sqlplus from the PostgreSQL machine?

Are there any `BLOB`, `CLOB`, `LONG` or `LONG RAW` columns in the Oracle table? These are known to make processing slow due to a limitation in Oracle.

**Comment by andreymarkin80** [comment] 2019-01-31 12:50
it take about 10 minutes (radcheck)  COUNT(*)
----------
    590728Oracle radcheck_sp_vw is view from CREATE TABLE "RADIUS"."RADCHECK"   (    "ID" NUMBER NOT NULL ENABLE,    "USERNAME" VARCHAR2(500 BYTE),    "ATTRIBUTE" VARCHAR2(500 BYTE),    "OP" VARCHAR2(2 BYTE),    "VALUE" VARCHAR2(500 BYTE),    "STARTTIME" VARCHAR2(50 BYTE),    "STOPTIME" VARCHAR2(50 BYTE),    "FIL_ID" NUMBER,     CONSTRAINT "RADCHECK_PKEY" PRIMARY KEY ("ID")  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)  TABLESPACE "RADIUS_DATA"  ENABLE   ) SEGMENT CREATION IMMEDIATE  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)  TABLESPACE "RADIUS_DATA" ; direct sql to oracle is OKroot@radius-1-spb:/home/andreym# time echo "select count(*) from radcheck_sp_vw;" | /opt/oracle/instantclient_12_2/sqlplusSQL*Plus: Release 12.2.0.1.0 Production on Thu Jan 31 15:49:20 2019Copyright (c) 1982, 2016, Oracle.  All rights reserved.Last Successful login time: Thu Jan 31 2019 15:47:16 +03:00Connected to:Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit ProductionWith the Partitioning, OLAP, Advanced Analytics and Real Application Testing optionsSQL>  COUNT(*)----------    590733SQL> Disconnected from Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit ProductionWith the Partitioning, OLAP, Advanced Analytics and Real Application Testing optionsreal    0m0.514suser    0m0.012ssys    0m0.004s  31.01.2019, 15:34, "Laurenz Albe" <notifications@github.com>:About the long duration of the materialized view refresh:How long does it take? For how many rows?Does it take much longer than running the same query via sqlplus from the PostgreSQL machine?Are there any BLOB, CLOB, LONG or LONG RAW columns in the Oracle table? These are known to make processing slow due to a limitation in Oracle.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by laurenz** [comment] 2019-01-31 13:04
Could you please format your posts? I cannot read them.

**Comment by laurenz** [comment] 2019-01-31 13:06
Also, it would be good if you answered my questions...

**Comment by andreymarkin80** [comment] 2019-01-31 14:01
earlier it working fine. but today perfomance is degaradated.

**Comment by andreymarkin80** [comment] 2019-01-31 14:39
Nothing change! It work fine some month.May be some cache in oracle_fdw is over...31.01.2019, 17:29, "Laurenz Albe" <notifications@github.com>:Then there is the old question: what changed since earlier?
One good test is always to tun the same Oracle query that EXPLAIN show you via sqlplus and see if the speed is very different. That can help to show if the problem might be related to oracle_fdw/PostgreSQL or not.

**Comment by laurenz** [comment] 2019-01-31 14:40
Then there is pretty little I can do...

**Closed** 2019-04-15 04:02 UTC
Labels: problem, unsolved
