### ISSUE TITLE
could not load library "/usr/edb/as16/lib/oracle_fdw.so"

### ISSUE THREAD

**Issue by TommyHo1** [laurenz/oracle_fdw#697] opened 2024-07-29 02:33 UTC
Dear Laurenz,

For the upgrade purpose (edu as v12 to edu as v16), we need to install both version in the same server.
at AS12, the oracle fdw working fine. we just installed this oracle_fdw by following steps, but it fail to create extension oracle_fdw.
the message is could not load library "/usr/edb/as16/lib/oracle_fdw.so"

since we already installed oracle client 18 when we install as12 before, 
we only do "make install" on this oracle_fdw lib

[root@gzdcedbdev03.css /]# cd /usr/lib/oracle/18.3/client64/lib
[root@gzdcedbdev03.css lib]# ls
.                      libipc1.so       libocijdbc18.so   ojdbc8.jar
..                     libmql1.so       libons.so         ottclasses.zip
glogin.sql             libnnz18.so      liboramysql18.so  xstreams.jar
libclntshcore.so.18.1  libocci.so       libsqlplusic.so
libclntsh.so           libocci.so.18.1  libsqlplus.so
libclntsh.so.18.1      libociei.so      network
[root@gzdcedbdev03.css lib]# ls -l
total 229008
drwxr-xr-x 3 root root      4096 Feb 17  2023 .
drwxr-xr-x 4 root root        28 Oct 19  2022 ..
-rwxr-xr-x 1 root root       342 Jan 24  2019 glogin.sql
-rwxr-xr-x 1 root root   8350672 Jan 24  2019 libclntshcore.so.18.1
lrwxrwxrwx 1 root root        17 Jan 24  2019 libclntsh.so -> libclntsh.so.18.1
-rwxr-xr-x 1 root root  77884224 Jan 24  2019 libclntsh.so.18.1
-rwxr-xr-x 1 root root   3537979 Jan 24  2019 libipc1.so
-rwxr-xr-x 1 root root    467468 Jan 24  2019 libmql1.so
-rwxr-xr-x 1 root root   6636088 Jan 24  2019 libnnz18.so
lrwxrwxrwx 1 root root        15 Jan 24  2019 libocci.so -> libocci.so.18.1
-rwxr-xr-x 1 root root   2229347 Jan 24  2019 libocci.so.18.1
-rwxr-xr-x 1 root root 126951384 Jan 24  2019 libociei.so
-rwxr-xr-x 1 root root    160875 Jan 24  2019 libocijdbc18.so
-rwxr-xr-x 1 root root    394835 Jan 24  2019 libons.so
-rwxr-xr-x 1 root root    118171 Jan 24  2019 liboramysql18.so
-rwxr-xr-x 1 root root   1655813 Jan 24  2019 libsqlplusic.so
-rwxr-xr-x 1 root root   1616347 Jan 24  2019 libsqlplus.so
drwxr-xr-x 3 root root        19 Oct 19  2022 network
-rw-r--r-- 1 root root   4109057 Jan 24  2019 ojdbc8.jar
-rw-r--r-- 1 root root    313026 Jan 24  2019 ottclasses.zip
-rw-r--r-- 1 root root     37519 Jan 24  2019 xstreams.jar

I found the pg_config still pointing to as12 , is that the reason?
[root@gzdcedbdev03.css lib]# pg_config --pgxs
/usr/edb/as12/lib/pgxs/src/makefiles/pgxs.mk

Regards,
Tommy

**Comment by laurenz** [comment] 2024-07-29 05:07
What is AS12? Is that EDB's proprietary fork? You say that "at AS12, the oracle fdw working fine". So, where is it not working?

It looks like you have Oracle Instant Client 18.3.
Can you tell me what else is installed on the machine?
Any other Oracle software? What version of PostgreSQL? What is your Linux distribution?

Please tell me how exactly you are installing oracle_fdw, and what the exact messages are.

How did you set the client library path for the PostgreSQL server?

**Comment by TommyHo1** [comment] 2024-07-31 21:56
Hi Laurenz,

the os is "Red Hat Enterprise Linux 8.6 (Ootpa)"
we installed below
edb-as12 
oracle-instantclient12.1-basic.x86_64                                    12.1.0.2.0-1                               @@commandline
oracle-instantclient18.3-basic.x86_64                                    18.3.0.0.0-3                               @ol7_oracle_instantclient
oracle-instantclient18.3-devel.x86_64                                    18.3.0.0.0-3                               @ol7_oracle_instantclient
oracle-instantclient18.3-sqlplus.x86_64  
oracle_fdw-ORACLE_FDW_2_3_0.tar.gz 

and edb-as16
oracle_fdw-master

PATH=/usr/edb/as12/bin:/usr/edb/as16/bin:$PATH:$HOME/.local/bin:$HOME/bin
export LD_LIBRARY_PATH=/usr/lib/oracle/18.3/client64/lib

before I install edb-as16 and oracle_fdw-master
the old as12 with oracle_fdw-ORACLE_FDW_2_3_0 was working fine
but after I install edb-as16 and oracle_fdw-master, both as12 and as 16 can not load the oracle fdw lib.

I think the problem is due to the wrong lib pointing, may I know some details for how to check it, and fix it?


Regards,
Tommy

**Comment by laurenz** [comment] 2024-08-01 07:36
Let's not rely on your guess what might be wrong, let's investigate the cause of your problem.

For that, please tell me the exact instructions you used to build and set up oracle_fdw, plus the output you got.
Also, tell me how you set the shared library path.

**Comment by laurenz** [comment] 2024-09-20 07:16
Are you still interested in this or shall I close the issue?

**Comment by edmondEDB** [comment] 2024-09-20 07:17
Thanks so much
It is closed

取得 iOS 版 Outlook<https://aka.ms/o0ukef>
________________________________
寄件者: Laurenz Albe ***@***.***>
寄件日期: Friday, September 20, 2024 3:16:33 PM
收件者: laurenz/oracle_fdw ***@***.***>
副本: edmondEDB ***@***.***>; Manual ***@***.***>
主旨: Re: [laurenz/oracle_fdw] could not load library "/usr/edb/as16/lib/oracle_fdw.so" (Issue #697)


Are you still interested in this or shall I close the issue?

**Closed** 2024-09-20 07:18 UTC
Labels: problem, installation
