### ISSUE TITLE
PG statement_timeout not work with oracle_fdw

### ISSUE THREAD

**Issue by nikolaysu** [laurenz/oracle_fdw#427] opened 2020-09-28 07:11 UTC
If the request contains external tables, and a timeout is set for the session(set statement_timeout=150000), the client disconnects with the "ERROR: canceling statement due to statement timeout" .
But, in pg_stat_activity  the query still being executed.
On the Oracle side it is also visible that the request is being executed.
For example, I ran the simplest query: insert into table_in_pg(fields,...) select * from table_foreign_oraclefdw;

**Comment by laurenz** [comment] 2020-09-28 07:22
The Oracle client messes with signal handling, so maybe that is connected with the problem.

Could you check if the Oracle query runs to completion or just takes a while to roll back?
Anyway, this looks like a bug.

**Comment by laurenz** [comment] 2020-09-28 08:17
Hmm, I tested this, and I cannot reproduce the behavior: as soon as the query times out, a cancel request is sent to the Oracle server.

There is something in your question that caught my attention: "the client disconnects". Normally the client does *not* disconnect then a query is interrupted.

**Comment by nikolaysu** [comment] 2020-09-28 08:23
Yes I put it wrong.
I am creating a request via psql and get answer - "ERROR: canceling statement due to statement timeout" (not disconnected)
1. OPen psql
2. Create foregin table
3. Create request: select count(*) from fg_table
4. Getting answer ERROR: canceling statement due to statement timeout
5. Select from pg_stat_activity  still running
6.select from oracle v$session.. still running

I am not very well in Oracle, would you tell me what specifically to look at in the current session on the Oracle side?

**Comment by nikolaysu** [comment] 2020-09-28 08:30
I logged out of psql - session ended on both sides.

**Comment by laurenz** [comment] 2020-09-28 08:38
I still cannot reproduce this.

When the query is interrupted, do you get the `psql` prompt back? Then the backend must be idle.

Ah, I think I have a suspicion. Could you check the `state` in the `pg_stat_activity` output? `query` will not show the active query, but the last query run on the database session. If the `state` is `idle`, as it should be, then the backend is done executing the query.

**Comment by nikolaysu** [comment] 2020-09-28 08:48
yes, on PG side state is idle
on the Oracle side session is running

**Comment by nikolaysu** [comment] 2020-09-28 08:55
Yes, it looks like I shouldn't have started a discussion
This is expected behavior. 

Many thanks for the help, and I apologize for the time taken.

**Comment by laurenz** [comment] 2020-09-28 08:59
Ah, great, problem solved.

No, it is good that you started that issue. Lots of people are confused by the query remaining visible in `pg_stat_activity`, and somebody else may find this discussion helpful.

I'll close the issue.

**Closed by laurenz** 2020-09-28 08:59 UTC
Labels: problem
