### ISSUE TITLE
Compile error with pgxc

### ISSUE THREAD

**Issue by jarod1sun** [laurenz/oracle_fdw#417] opened 2020-08-12 05:24 UTC
Env. pgxc ( aka postgresql cluster feature )
oracle_fdw 2.2.0
Centos 7.4

Error Info as below:
In file include  from oracle_fdw.c : 50:0:
/opt/pgxc/include/postgresql/server/optimizer/restricinfo.h:38:13 note: expected 'struct list **' but argument is of type 'Relids'
extern void extract_actual_join_clauses(List *restrictinfo_list,
                  ^
oracle_fdw.c 2956:3 error: too many arguments to function 'extract_actual_join_clauses'
      extract_actual_join_clauses(extra->restrictlist, joinrel->relids, &joinclauses, &otherclauses);

make: *** [oracle_fdw.o] error 1

**Comment by jarod1sun** [comment] 2020-08-12 05:25
Can oracle_fdw compile under pgxc?

**Comment by laurenz** [comment] 2020-08-12 07:14
The problem is not pgxc, but that you are using an old version of PostgreSQL.

The function `extract_actual_join_clauses` grew an extra argument in commit [e5d83995e9](https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=e5d83995e9f88426b325a7ea8ce0770926dc64de) in 2018-04-19, so you must be using a PostgreSQL version older than v11.

Seems like commit ef3f5a741d6d3d9b1af5c5ad09edc266d7dc3b8d added the additional argument, but forgot to add conditional compilation for older releases.

I'll go fix.

**Comment by laurenz** [comment] 2020-08-12 07:25
Actually, I forgot to notice that that PostgreSQL modification was backpatched to all supported releases, so commit ef3f5a741d6d3d9b1af5c5ad09edc266d7dc3b8d was right to change the code unconditionally.

So either you have a PostgreSQL release older than 9.3, or you didn't install patches in over two years.

Please upgrade and try again.

**Comment by jarod1sun** [comment] 2020-08-13 01:37
Thanks for your help. we will upgrade our pgxc baseline to new release, but we must evaluate our own code first.  i will feedback once our baseline upgrade and recompile fdw.

**Comment by laurenz** [comment] 2020-09-24 06:59
I'll close this, since updating PostgreSQL to the latest minor release will fix the problem.

**Closed by laurenz** 2020-09-24 06:59 UTC
Labels: installation, problem
