### ISSUE TITLE
BLOB Performance

### ISSUE THREAD

**Issue by amantadine** [laurenz/oracle_fdw#429] opened 2020-10-01 11:48 UTC
I am currently using Oracle 11g (11.2.0.4.0) via remote access (NB to which I have read-only privilege) and PostgresSQL 12.2 on Windows Server 2016. I have encountered performance issues when trying to copy over an Oracle table that contains a column of BLOBs. I apologise if this has been raised previously but I read from a different issue that performance can be poor due to a limitation in Oracle. I was wondering whether you would be able to shed some more light on this please?

There are approx 3 oracle tables that I would like to replicate in PostgresSQL. Each of the oracle tables has approx 8-30 million rows (each with a single column of BLOBs)

**Comment by laurenz** [comment] 2020-10-01 14:32
This is a duplicate of #68 and #326.

The problem is that OCI prefetching, which oracle_fdw uses for performance, does not work with LOB columns.

To overcome the problem, I'd have to change oracle_fdw so that it uses bulk fetching into arrays. I didn't get to tackle that yet.

**Closed** 2020-11-12 10:22 UTC
Labels: duplicate, problem

**Comment by laurenz** [comment] 2023-05-17 08:27
This has been improved with commit d679a73d02057fd674fc78fe5f25183e5c9a172b.
You are welcome to test if the current development version works better for you.
