### ISSUE TITLE
clang: error: unknown argument when installing on PostgreSQL 11

### ISSUE THREAD

**Issue by MarvinDBA** [laurenz/oracle_fdw#327] opened 2019-06-07 18:14 UTC
I have PostgreSQL 11 installed with yum on Red Hat 7.2.
I am trying to install oracle_fdw, but when I run the make command, I end up with error:

clang: error: unknown argument: '-flto=thin'
make: *** [oracle_fdw.bc] Error 1

I have version  3.4.2-9.el7 for clang.

It seems to be a know issue, but I don't know how to solve it.

Does someone has any indication?
Thanks by advance for any tip(s)

**Comment by laurenz** [comment] 2019-06-11 08:47
Can you show me the whole attempt to build oracle_fdw, not just the error message?

**Comment by MarvinDBA** [comment] 2019-06-11 14:38
I will come back soon to post what I have done...

**Comment by MarvinDBA** [comment] 2019-06-11 15:18
Here is what I have done:

1) Linux version:

cat /etc/redhat-release*

Red Hat Enterprise Linux Server release 7.2 (Maipo)

2) Postgres version:

postgres=# select version();
                                                 version
---------------------------------------------------------------------------------------------------------
 PostgreSQL 11.3 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36), 64-bit
(1 row)

postgres=#

3) Locaction where the Oracle client software is installed:

/home/postgres/oracle/client/instantclient_19_3

ls -ltr
total 232584
-rwxr-xr-x. 1 postgres postgres    236960 Apr 17 08:38 uidrvci
drwxr-xr-x. 3 postgres postgres        18 Apr 17 08:38 network
-rwxr-xr-x. 1 postgres postgres    115976 Apr 17 08:38 liboramysql19.so
-rwxr-xr-x. 1 postgres postgres 130515320 Apr 17 08:38 libociei.so
-rwxr-xr-x. 1 postgres postgres   6587832 Apr 17 08:38 libnnz19.so
-rwxr-xr-x. 1 postgres postgres     59296 Apr 17 08:38 genezi
-rw-r--r--. 1 postgres postgres      1632 Apr 17 08:38 BASIC_README
-r-xr-xr-x. 1 postgres postgres      5780 Apr 17 08:38 BASIC_LICENSE
-rwxr-xr-x. 1 postgres postgres     41840 Apr 17 08:38 adrci
-rw-r--r--. 1 postgres postgres     74263 Apr 17 08:38 xstreams.jar
-rw-r--r--. 1 postgres postgres   1680074 Apr 17 08:38 ucp.jar
-rw-r--r--. 1 postgres postgres   4210517 Apr 17 08:38 ojdbc8.jar
-r-xr-xr-x. 1 postgres postgres    153624 Apr 17 08:38 libocijdbc19.so
-rwxr-xr-x. 1 postgres postgres   2339896 Apr 17 08:38 libocci.so.19.1
-r-xr-xr-x. 1 postgres postgres    478432 Apr 17 08:38 libmql1.so
-r-xr-xr-x. 1 postgres postgres   3609536 Apr 17 08:38 libipc1.so
-rwxr-xr-x. 1 postgres postgres  79961792 Apr 17 08:38 libclntsh.so.19.1
-rwxr-xr-x. 1 postgres postgres   8041608 Apr 17 08:38 libclntshcore.so.19.1
-rw-rw-r--. 1 postgres postgres      1626 Apr 17 08:39 SDK_README
-r-xr-xr-x. 1 postgres postgres      5780 Apr 17 08:39 SDK_LICENSE
drwxr-xr-x. 5 postgres postgres        74 Apr 17 08:39 sdk
lrwxrwxrwx. 1 postgres postgres        15 Jun  7 13:09 libocci.so.18.1 -> libocci.so.19.1
lrwxrwxrwx. 1 postgres postgres        15 Jun  7 13:09 libocci.so.12.1 -> libocci.so.19.1
lrwxrwxrwx. 1 postgres postgres        15 Jun  7 13:09 libocci.so.11.1 -> libocci.so.19.1
lrwxrwxrwx. 1 postgres postgres        15 Jun  7 13:09 libocci.so.10.1 -> libocci.so.19.1
lrwxrwxrwx. 1 postgres postgres        15 Jun  7 13:09 libocci.so -> libocci.so.19.1
lrwxrwxrwx. 1 postgres postgres        17 Jun  7 13:09 libclntsh.so.18.1 -> libclntsh.so.19.1
lrwxrwxrwx. 1 postgres postgres        17 Jun  7 13:09 libclntsh.so.12.1 -> libclntsh.so.19.1
lrwxrwxrwx. 1 postgres postgres        17 Jun  7 13:09 libclntsh.so.11.1 -> libclntsh.so.19.1
lrwxrwxrwx. 1 postgres postgres        17 Jun  7 13:09 libclntsh.so.10.1 -> libclntsh.so.19.1
lrwxrwxrwx. 1 postgres postgres        17 Jun  7 13:09 libclntsh.so -> libclntsh.so.19.1

4) Locaction where oracle_fdw is unzeipped:

/home/postgres/oracle_fdw/oracle_fdw-2.1.0
ls -ltr
total 1800
-rw-r--r--. 1 postgres postgres    315 Sep 25  2018 TODO
drwxr-xr-x. 2 postgres postgres     94 Sep 25  2018 sql
-rw-r--r--. 1 postgres postgres  37530 Sep 25  2018 README.oracle_fdw
-rw-r--r--. 1 postgres postgres  93976 Sep 25  2018 oracle_utils.c
-rw-r--r--. 1 postgres postgres  44474 Sep 25  2018 oracle_gis.c
-rw-r--r--. 1 postgres postgres   8284 Sep 25  2018 oracle_fdw.h
-rw-r--r--. 1 postgres postgres    133 Sep 25  2018 oracle_fdw.control
-rw-r--r--. 1 postgres postgres 194018 Sep 25  2018 oracle_fdw.c
-rw-r--r--. 1 postgres postgres   1003 Sep 25  2018 oracle_fdw--1.1.sql
-rw-r--r--. 1 postgres postgres    231 Sep 25  2018 oracle_fdw--1.0--1.1.sql
drwxr-xr-x. 2 postgres postgres     95 Sep 25  2018 msvc
-rw-r--r--. 1 postgres postgres   1968 Sep 25  2018 Makefile
-rw-r--r--. 1 postgres postgres   1086 Sep 25  2018 LICENSE
drwxr-xr-x. 2 postgres postgres   4096 Sep 25  2018 expected
-rw-r--r--. 1 postgres postgres  15887 Sep 25  2018 CHANGELOG
-rw-r--r--. 1 postgres postgres   1459 Sep 25  2018 META.json
-rw-rw-r--. 1 postgres postgres 570832 Jun  7 13:12 oracle_fdw.o
-rw-rw-r--. 1 postgres postgres 173152 Jun  7 13:12 oracle_utils.o
-rw-rw-r--. 1 postgres postgres 122344 Jun  7 13:12 oracle_gis.o
-rwxrwxr-x. 1 postgres postgres 528870 Jun  7 13:12 oracle_fdw.so

5) Instalaltion variables:

echo $ORACLE_HOME
/home/postgres/oracle/client/instantclient_19_3

echo $LD_LIBRARY_PATH
/home/postgres/oracle/client/instantclient_19_3

6) Run mane and make install:

cd /home/postgres/oracle_fdw/oracle_fdw-2.1.0

-- As super user postgres:
make

/opt/rh/llvm-toolset-7/root/usr/bin/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -O2  -I/home/postgres/oracle/client/instantclient_19_3/sdk/include -I/home/postgres/oracle/client/instantclient_19_3/oci/include -I/home/postgres/oracle/client/instantclient_19_3/rdbms/public -I/usr/include/oracle/12.2/client -I/usr/include/oracle/12.2/client64 -I/usr/include/oracle/12.1/client -I/usr/include/oracle/12.1/client64 -I/usr/include/oracle/11.2/client -I/usr/include/oracle/11.2/client64 -I/usr/include/oracle/11.1/client -I/usr/include/oracle/11.1/client64 -I/usr/include/oracle/10.2.0.5/client -I/usr/include/oracle/10.2.0.5/client64 -I/usr/include/oracle/10.2.0.4/client -I/usr/include/oracle/10.2.0.4/client64 -I/usr/include/oracle/10.2.0.3/client -I/usr/include/oracle/10.2.0.3/client64 -I. -I./ -I/usr/pgsql-11/include/server -I/usr/pgsql-11/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include -flto=thin -emit-llvm -c -o oracle_fdw.bc oracle_fdw.c
clang: error: unknown argument: '-flto=thin'
make: *** [oracle_fdw.bc] Error 1


Then:

clang --version

clang version 3.4.2 (tags/RELEASE_34/dot2-final)
Target: x86_64-redhat-linux-gnu
Thread model: posix

Any idea who to go further?

**Comment by laurenz** [comment] 2019-06-12 08:00
A web search leads me to believe that your version of clang is too old to support the `flto=thin` option.

Can you use a more recent version?
If not, use gcc (since you are on Linux).

**Comment by yamatattsu** [comment] 2019-06-12 09:14
Hi MarvinDBA and Laurenz,


>A web search leads me to believe that your version of clang is too old to
support the flto=thin option.

>Can you use a more recent version?

I heard that llvm should be greater than 3.9.0.

Redhat provides llvm-toolset. You can try it if you'd like to use Clang.

See:
https://developers.redhat.com/blog/2017/11/01/getting-started-llvm-toolset/


Thanks,

Tatsuro Yamada



2019年6月12日(水) 17:00 Laurenz Albe <notifications@github.com>:

**Comment by MarvinDBA** [comment] 2019-06-15 09:57
Hi Laurenz, Yamatattsu.

Thanks for the answers.
I am a bit confused,. What is the difference between clang and llvm-toolset?
Does this mean that llvm-toolset includes the newer clang version (at least greater that 3.9.0)?

Thanks and Regards

**Comment by MarvinDBA** [comment] 2019-06-15 14:34
I am unable to install subscription-manager the way it is described in the above link.
Does someone has any exprience in installing it on redhat 7 [Red Hat Enterprise Linux Server release 7.2 (Maipo)]?
Yum say that there is no higher version available version of clang for Red Hat Enterprise Linux Server release 7.2 (Maipo).

Does someone has any other idea or exprience?

Thanks by advance.

**Comment by yamatattsu** [comment] 2019-06-16 05:51
Hi MarvinDBA,

How about EPEL or centos-release-scl repository? But I'm not sure whether
it works fine on your RHEL or not. So, it might be better to use gcc, if
you haven't strong opinions.

https://www.centos.org/forums/viewtopic.php?t=70149

Thanks,
Tatsuro Yamada


2019年6月15日(土) 23:34 MarvinDBA <notifications@github.com>:

**Comment by MarvinDBA** [comment] 2019-06-16 13:32
Hi yamatattsu,

Thanks for the answer.
I had already the link from RedHat you provided me with.
There is a subscription-manager utility involved, but I was unable to find it/install it with yum, as well as unable to find this utility and to install it...
About the CentOS link mentioned above, which rpm should I use?

As an alternative, how to use gcc instead of? 

Kind Regards

**Comment by laurenz** [comment] 2019-06-17 08:16
RHEL usually ships with ancient software versions, so it would not surprise me if the `clang` shipped with it is too old to build PostgreSQL.

With which compiler was your PostgreSQL built with? You get that information with

    pg_config -cc

This requires that the PostgreSQL `devel` package is installed (but you need that anyway).

To install `gcc` on RHEL, you need to tun

    yum install gcc

If that does not work, ask your system administrator to configure the repositories properly.

**Comment by MarvinDBA** [comment] 2019-06-21 07:37
yum list clang

Loaded plugins: langpacks, ulninfo
Installed Packages
clang.x86_64													3.4.2-9.el7                                                              @epel

yum list gcc

Loaded plugins: langpacks, ulninfo
Installed Packages
gcc.x86_64                                                     4.8.5-28.0.1.el7_5.1                                                      @ol7_latest
Available Packages
gcc.x86_64                                                     4.8.5-36.0.1.el7_6.2                                                      ol7_latest


pg_config --cc

gcc

How can I go further with this?

**Comment by laurenz** [comment] 2019-06-21 17:38
Ah, I begin to understand. You are not trying to build oracle_fdw with clang, you are building against a PostgreSQL version that is configured `--with-llvm`, so `make` is trying to generate byte code for JIT.

You can avoid building the JIT byte code by building oracle_fdw with

    with_llvm=no make -e

This seems to be a duplicate of #255.

**Comment by MarvinDBA** [comment] 2019-06-24 10:09
I am not sure I really understand.
Instead of make, I should type with_llvm=no make -e.
Is it what you mean?

**Comment by laurenz** [comment] 2019-06-24 10:17
Yes, exactly.

**Comment by MarvinDBA** [comment] 2019-06-25 10:13
Here is what get when I run make only (as posted above):

[postgres@oel764-pg10-copied-deinstall-s01 oracle_fdw-2.1.0]$ make
/opt/rh/llvm-toolset-7/root/usr/bin/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -O2  -I/home/postgres/oracle/client/instantclient_19_3/sdk/include -I/home/postgres/oracle/client/instantclient_19_3/oci/include -I/home/postgres/oracle/client/instantclient_19_3/rdbms/public -I/usr/include/oracle/12.2/client -I/usr/include/oracle/12.2/client64 -I/usr/include/oracle/12.1/client -I/usr/include/oracle/12.1/client64 -I/usr/include/oracle/11.2/client -I/usr/include/oracle/11.2/client64 -I/usr/include/oracle/11.1/client -I/usr/include/oracle/11.1/client64 -I/usr/include/oracle/10.2.0.5/client -I/usr/include/oracle/10.2.0.5/client64 -I/usr/include/oracle/10.2.0.4/client -I/usr/include/oracle/10.2.0.4/client64 -I/usr/include/oracle/10.2.0.3/client -I/usr/include/oracle/10.2.0.3/client64 -I. -I./ -I/usr/pgsql-11/include/server -I/usr/pgsql-11/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include -flto=thin -emit-llvm -c -o oracle_fdw.bc oracle_fdw.c
clang: error: unknown argument: '-flto=thin'
make: *** [oracle_fdw.bc] Error 1

and here is what I get if I run the above command:

[postgres@oel764-pg10-copied-deinstall-s01 oracle_fdw-2.1.0]$
[postgres@oel764-pg10-copied-deinstall-s01 oracle_fdw-2.1.0]$ with_llvm=no make -e
make: Nothing to be done for `all'.

Any other idea?

Kind Regards

**Comment by laurenz** [comment] 2019-06-25 10:29
Perfect! Then oracle_fdw has been built successfully, and you can install it with

    with_llvm=no make -e install

**Comment by MarvinDBA** [comment] 2019-06-27 17:34
Here is what I get when I run: sudo make install

sudo make install

---
[sudo] password for postgres:
/usr/bin/mkdir -p '/usr/lib64/pgsql'
/usr/bin/mkdir -p '/usr/share/pgsql/extension'
/usr/bin/mkdir -p '/usr/share/pgsql/extension'
/usr/bin/mkdir -p '/usr/share/doc/pgsql/extension'
/bin/sh /usr/lib64/pgsql/pgxs/src/makefiles/../../config/install-sh -c -m 755  oracle_fdw.so '/usr/lib64/pgsql/oracle_fdw.so'
/bin/sh /usr/lib64/pgsql/pgxs/src/makefiles/../../config/install-sh -c -m 644 ./oracle_fdw.control '/usr/share/pgsql/extension/'
/bin/sh /usr/lib64/pgsql/pgxs/src/makefiles/../../config/install-sh -c -m 644 ./oracle_fdw--1.1.sql ./oracle_fdw--1.0--1.1.sql  '/usr/shar                     e/pgsql/extension/'
/bin/sh /usr/lib64/pgsql/pgxs/src/makefiles/../../config/install-sh -c -m 644 ./README.oracle_fdw '/usr/share/doc/pgsql/extension/'
---

It seems ok... I can go further with the installation... do I interpret correctly?

One question more, what does mean "make: Nothing to be done for `all'."?

**Comment by MarvinDBA** [comment] 2019-06-27 17:34
Here is what I get when I run: sudo make install

sudo make install

---
[sudo] password for postgres:
/usr/bin/mkdir -p '/usr/lib64/pgsql'
/usr/bin/mkdir -p '/usr/share/pgsql/extension'
/usr/bin/mkdir -p '/usr/share/pgsql/extension'
/usr/bin/mkdir -p '/usr/share/doc/pgsql/extension'
/bin/sh /usr/lib64/pgsql/pgxs/src/makefiles/../../config/install-sh -c -m 755  oracle_fdw.so '/usr/lib64/pgsql/oracle_fdw.so'
/bin/sh /usr/lib64/pgsql/pgxs/src/makefiles/../../config/install-sh -c -m 644 ./oracle_fdw.control '/usr/share/pgsql/extension/'
/bin/sh /usr/lib64/pgsql/pgxs/src/makefiles/../../config/install-sh -c -m 644 ./oracle_fdw--1.1.sql ./oracle_fdw--1.0--1.1.sql  '/usr/shar                     e/pgsql/extension/'
/bin/sh /usr/lib64/pgsql/pgxs/src/makefiles/../../config/install-sh -c -m 644 ./README.oracle_fdw '/usr/share/doc/pgsql/extension/'
---

It seems ok... do I interpret correctly?

One question more, what does mean "make: Nothing to be done for `all'."?

**Comment by laurenz** [comment] 2019-06-27 21:43
Yes, everything is perfect.

The meaning of `make: Nothing to be done for `all'.`:

Your previous attempts that failed with the `clang` error actually built oracle_fdw just fine.
*After* building the extension the `pgxs.mk` makefile tries to build the JIT bytecode, which failed.
So if you disable that, `make` notices that everything is already done.

I think we can close this issue.

**Comment by MarvinDBA** [comment] 2019-06-28 07:43
I confirm that I could perform the rest of the configuration/installation and that I could create a database using that extension. This issue can be closed.

**Closed** 2019-06-28 08:06 UTC
Labels: duplicate, installation, problem
