### ISSUE TITLE
ANALYZE on large foreign tables fails with out-of-memory condition

### ISSUE THREAD

**Issue by acheccuc** [laurenz/oracle_fdw#82] opened 2016-04-28 11:45 UTC
Dear All,
we are currently experimenting with Oracle_FDW and foreign tables on a system (wa already have some others in production) and experiencing a problem when trying to run ANALYZE against a large Oracle table. Our system specs are:

- PostgreSQL 9.5.2 Linux x86_64
- Oracle_FDW 1.4.0

PostgreSQL is set up with the following memory parameters:

- shared_buffers = 947MB
- effective_cache_size = 2525MB
- work_mem = 4MB
- maintenance_work_mem = 64M

Although ANALYZE works properly with small tables, when we try to run it against a ~800m records one we get an out-of memory condition pretty soon:

> analyze verbose enauni.dbentry (bioseqid);
> INFO:  analyzing "enauni.dbentry"
> ERROR:  out of memory
> DETAIL:  Failed on request of size 5.
> CONTEXT:  converting column "drop_entry_status" for foreign table scan of "dbentry", row 27940522

This is the foreign table mapping on PostgreSQL:

```
                          Foreign table "enauni.dbentry"
        Column         |              Type              | Modifiers | FDW Options 
-----------------------+--------------------------------+-----------+-------------
 bioseqid              | bigint                         | not null  | 
 dbentryid             | bigint                         | not null  | 
 entry_name            | character varying(100)         |           | 
 drop_entry_status     | character varying(2)           |           | 
 primaryacc#           | character varying(15)          | not null  | 
 version#              | integer                        | not null  | 
 drop_confidential     | character varying(1)           |           | 
 dbcode                | character varying(5)           | not null  | 
 ext_date              | timestamp(0) without time zone |           | 
 ext_ver               | integer                        |           | 
 first_created         | timestamp(0) without time zone | not null  | 
 first_public          | timestamp(0) without time zone |           | 
 hold_date             | timestamp(0) without time zone |           | 
 project#              | smallint                       | not null  | 
 ffdate                | timestamp(0) without time zone |           | 
 userstamp             | character varying(30)          | not null  | 
 timestamp             | timestamp(0) without time zone | not null  | 
 entry_type            | smallint                       | not null  | 
 dataclass             | character varying(4)           | not null  | 
 qual_division         | character varying(3)           |           | 
 statusid              | integer                        | not null  | 
 last_public           | timestamp(0) without time zone |           | 
 change_date           | timestamp(0) without time zone | not null  | 
 sequence_length       | bigint                         | not null  | 
 sequence_version      | integer                        | not null  | 
 study_id              | character varying(15)          |           | 
 set_acc               | character varying(15)          |           | 
 sample_id             | character varying(15)          |           | 
 analysis_id           | character varying(15)          |           | 
 submission_account_id | character varying(15)          |           | 
 assembly_level        | integer                        |           |
```

Tracing the execution on the Linux side, we clearly see that memory is progressively reclaimed from the FS cache until it exhausted by the PostgreSQL backend. 

The PostgreSQL instance has been run with log_min_messages = 'DEBUG1' and this is what we collected from the log file:

```
< 2016-04-28 11:57:38.228 BST >INFO:  analyzing "enauni.dbentry"
< 2016-04-28 11:57:38.228 BST >DEBUG:  oracle_fdw: analyze foreign table 16464
< 2016-04-28 11:57:38.228 BST >DEBUG:  oracle_fdw: set NLS_LANG=AMERICAN_AMERICA.AL32UTF8
< 2016-04-28 11:57:38.229 BST >DEBUG:  oracle_fdw: remote query is SELECT "BIOSEQID", "DBENTRYID", "ENTRY_NAME", "DROP_ENTRY_STATUS", "PRIMARYACC#", "VERSION#", "DROP_CONFIDENTIAL", "DBCODE", "EXT_DATE", "EXT_VER", "FIRST_CREATED", "FIRS
T_PUBLIC", "HOLD_DATE", "PROJECT#", "FFDATE", "USERSTAMP", "TIMESTAMP", "ENTRY_TYPE", "DATACLASS", "QUAL_DIVISION", "STATUSID", "LAST_PUBLIC", "CHANGE_DATE", "SEQUENCE_LENGTH", "SEQUENCE_VERSION", "STUDY_ID", "SET_ACC", "SAMPLE_ID", "ANA
LYSIS_ID", "SUBMISSION_ACCOUNT_ID", "ASSEMBLY_LEVEL" FROM "DATALIB"."DBENTRY"

[.....]

< 2016-04-28 12:08:54.484 BST >DEBUG:  autovacuum: processing database "pgbench"
TopMemoryContext: 99184 total in 13 blocks; 14392 free (40 chunks); 84792 used
  TopTransactionContext: 8192 total in 1 blocks; 7968 free (0 chunks); 224 used
  Record information cache: 24576 total in 2 blocks; 15984 free (5 chunks); 8592 used
  TableSpace cache: 8192 total in 1 blocks; 3216 free (0 chunks); 4976 used
  Operator lookup cache: 24576 total in 2 blocks; 11888 free (5 chunks); 12688 used
  Type information cache: 24464 total in 2 blocks; 3744 free (0 chunks); 20720 used
  CFuncHash: 8192 total in 1 blocks; 1680 free (0 chunks); 6512 used
  MessageContext: 8192 total in 1 blocks; 4472 free (1 chunks); 3720 used
  Operator class cache: 8192 total in 1 blocks; 1680 free (0 chunks); 6512 used
  smgr relation table: 24576 total in 2 blocks; 9808 free (4 chunks); 14768 used
  TransactionAbortContext: 32768 total in 1 blocks; 32736 free (0 chunks); 32 used
  Portal hash: 8192 total in 1 blocks; 1680 free (0 chunks); 6512 used
  PortalMemory: 8192 total in 1 blocks; 7888 free (0 chunks); 304 used
    PortalHeapMemory: 1024 total in 1 blocks; 968 free (0 chunks); 56 used
      Analyze: 4605577648 total in 559 blocks; 4824 free (5 chunks); 4605572824 used
      Vacuum: 8192 total in 1 blocks; 7808 free (0 chunks); 384 used
  Relcache by OID: 24576 total in 2 blocks; 13872 free (3 chunks); 10704 used
  CacheMemoryContext: 1051288 total in 8 blocks; 256640 free (0 chunks); 794648 used
    pg_inherits_relid_seqno_index: 1024 total in 1 blocks; 64 free (0 chunks); 960 used
    pg_inherits_parent_index: 1024 total in 1 blocks; 200 free (0 chunks); 824 used
    pg_policy_polrelid_polname_index: 1024 total in 1 blocks; 64 free (0 chunks); 960 used
    pg_policy_oid_index: 1024 total in 1 blocks; 200 free (0 chunks); 824 used
    pg_toast_2618_index: 1024 total in 1 blocks; 16 free (0 chunks); 1008 used
    pg_roles: 15360 total in 4 blocks; 1392 free (0 chunks); 13968 used
    pg_toast_2619_index: 1024 total in 1 blocks; 16 free (0 chunks); 1008 used
    pg_attrdef_oid_index: 1024 total in 1 blocks; 200 free (0 chunks); 824 used
    pg_attrdef_adrelid_adnum_index: 1024 total in 1 blocks; 64 free (0 chunks); 960 used
    pg_class_tblspc_relfilenode_index: 1024 total in 1 blocks; 16 free (0 chunks); 1008 used
    pg_index_indrelid_index: 1024 total in 1 blocks; 152 free (0 chunks); 872 used
    pg_db_role_setting_databaseid_rol_index: 1024 total in 1 blocks; 64 free (0 chunks); 960 used
    pg_user_mapping_user_server_index: 1024 total in 1 blocks; 16 free (0 chunks); 1008 used
    pg_user_mapping_oid_index: 1024 total in 1 blocks; 200 free (0 chunks); 824 used
    pg_type_oid_index: 1024 total in 1 blocks; 152 free (0 chunks); 872 used
    pg_type_typname_nsp_index: 1024 total in 1 blocks; 16 free (0 chunks); 1008 used
    pg_ts_template_oid_index: 1024 total in 1 blocks; 200 free (0 chunks); 824 used
    pg_ts_template_tmplname_index: 1024 total in 1 blocks; 64 free (0 chunks); 960 used
    pg_ts_parser_oid_index: 1024 total in 1 blocks; 200 free (0 chunks); 824 used
    pg_ts_parser_prsname_index: 1024 total in 1 blocks; 64 free (0 chunks); 960 used
    pg_ts_dict_oid_index: 1024 total in 1 blocks; 200 free (0 chunks); 824 used
    pg_ts_dict_dictname_index: 1024 total in 1 blocks; 64 free (0 chunks); 960 used
    pg_ts_config_oid_index: 1024 total in 1 blocks; 200 free (0 chunks); 824 used
    pg_ts_config_cfgname_index: 1024 total in 1 blocks; 64 free (0 chunks); 960 used
    pg_ts_config_map_index: 3072 total in 2 blocks; 1784 free (2 chunks); 1288 used
    pg_transform_type_lang_index: 1024 total in 1 blocks; 64 free (0 chunks); 960 used
    pg_transform_oid_index: 1024 total in 1 blocks; 200 free (0 chunks); 824 used
    pg_statistic_relid_att_inh_index: 3072 total in 2 blocks; 1736 free (2 chunks); 1336 used
    pg_class_relname_nsp_index: 1024 total in 1 blocks; 16 free (0 chunks); 1008 used
    pg_range_rngtypid_index: 1024 total in 1 blocks; 152 free (0 chunks); 872 used
    pg_proc_oid_index: 1024 total in 1 blocks; 152 free (0 chunks); 872 used
    pg_proc_proname_args_nsp_index: 3072 total in 2 blocks; 1736 free (2 chunks); 1336 used
    pg_opfamily_oid_index: 1024 total in 1 blocks; 200 free (0 chunks); 824 used
    pg_opfamily_am_name_nsp_index: 3072 total in 2 blocks; 1784 free (2 chunks); 1288 used
    pg_operator_oid_index: 1024 total in 1 blocks; 152 free (0 chunks); 872 used
    pg_operator_oprname_l_r_n_index: 3072 total in 2 blocks; 1736 free (2 chunks); 1336 used
    pg_namespace_oid_index: 1024 total in 1 blocks; 152 free (0 chunks); 872 used
    pg_namespace_nspname_index: 1024 total in 1 blocks; 152 free (0 chunks); 872 used
    pg_language_oid_index: 1024 total in 1 blocks; 200 free (0 chunks); 824 used
    pg_language_name_index: 1024 total in 1 blocks; 200 free (0 chunks); 824 used
    pg_foreign_table_relid_index: 1024 total in 1 blocks; 152 free (0 chunks); 872 used
    pg_foreign_server_oid_index: 1024 total in 1 blocks; 152 free (0 chunks); 872 used
    pg_foreign_server_name_index: 1024 total in 1 blocks; 152 free (0 chunks); 872 used
    pg_foreign_data_wrapper_oid_index: 1024 total in 1 blocks; 152 free (0 chunks); 872 used
    pg_foreign_data_wrapper_name_index: 1024 total in 1 blocks; 200 free (0 chunks); 824 used
    pg_event_trigger_oid_index: 1024 total in 1 blocks; 200 free (0 chunks); 824 used
    pg_event_trigger_evtname_index: 1024 total in 1 blocks; 200 free (0 chunks); 824 used
    pg_enum_typid_label_index: 1024 total in 1 blocks; 64 free (0 chunks); 960 used
    pg_enum_oid_index: 1024 total in 1 blocks; 200 free (0 chunks); 824 used
    pg_default_acl_role_nsp_obj_index: 3072 total in 2 blocks; 1784 free (2 chunks); 1288 used
    pg_conversion_oid_index: 1024 total in 1 blocks; 200 free (0 chunks); 824 used
    pg_constraint_oid_index: 1024 total in 1 blocks; 200 free (0 chunks); 824 used
    pg_conversion_name_nsp_index: 1024 total in 1 blocks; 64 free (0 chunks); 960 used
    pg_conversion_default_index: 3072 total in 2 blocks; 1784 free (2 chunks); 1288 used
    pg_collation_oid_index: 1024 total in 1 blocks; 152 free (0 chunks); 872 used
    pg_collation_name_enc_nsp_index: 3072 total in 2 blocks; 1736 free (2 chunks); 1336 used
    pg_opclass_am_name_nsp_index: 3072 total in 2 blocks; 1736 free (2 chunks); 1336 used
    pg_cast_source_target_index: 1024 total in 1 blocks; 16 free (0 chunks); 1008 used
    pg_attribute_relid_attnam_index: 1024 total in 1 blocks; 16 free (0 chunks); 1008 used
    pg_amop_fam_strat_index: 3072 total in 2 blocks; 1736 free (2 chunks); 1336 used
    pg_amop_opr_fam_index: 3072 total in 2 blocks; 1736 free (2 chunks); 1336 used
    pg_aggregate_fnoid_index: 1024 total in 1 blocks; 152 free (0 chunks); 872 used
    pg_trigger_tgrelid_tgname_index: 1024 total in 1 blocks; 64 free (0 chunks); 960 used
    pg_rewrite_rel_rulename_index: 1024 total in 1 blocks; 16 free (0 chunks); 1008 used
    pg_amproc_fam_proc_index: 3072 total in 2 blocks; 1736 free (2 chunks); 1336 used
    pg_opclass_oid_index: 1024 total in 1 blocks; 152 free (0 chunks); 872 used
    pg_index_indexrelid_index: 1024 total in 1 blocks; 152 free (0 chunks); 872 used
    pg_attribute_relid_attnum_index: 1024 total in 1 blocks; 16 free (0 chunks); 1008 used
    pg_class_oid_index: 1024 total in 1 blocks; 152 free (0 chunks); 872 used
    pg_authid_oid_index: 1024 total in 1 blocks; 152 free (0 chunks); 872 used
    pg_auth_members_member_role_index: 1024 total in 1 blocks; 64 free (0 chunks); 960 used
    pg_tablespace_oid_index: 1024 total in 1 blocks; 152 free (0 chunks); 872 used
    pg_replication_origin_roname_index: 1024 total in 1 blocks; 200 free (0 chunks); 824 used
    pg_database_datname_index: 1024 total in 1 blocks; 152 free (0 chunks); 872 used
    pg_replication_origin_roiident_index: 1024 total in 1 blocks; 200 free (0 chunks); 824 used
    pg_auth_members_role_member_index: 1024 total in 1 blocks; 64 free (0 chunks); 960 used
    pg_database_oid_index: 1024 total in 1 blocks; 152 free (0 chunks); 872 used
    pg_authid_rolname_index: 1024 total in 1 blocks; 152 free (0 chunks); 872 used
  WAL record construction: 49760 total in 2 blocks; 6592 free (0 chunks); 43168 used
  PrivateRefCount: 8192 total in 1 blocks; 3744 free (0 chunks); 4448 used
  MdSmgr: 8192 total in 1 blocks; 5888 free (0 chunks); 2304 used
  ident parser context: 0 total in 0 blocks; 0 free (0 chunks); 0 used
  hba parser context: 7168 total in 3 blocks; 1264 free (1 chunks); 5904 used
  LOCALLOCK hash: 24576 total in 2 blocks; 13920 free (4 chunks); 10656 used
  Timezones: 83472 total in 2 blocks; 3744 free (0 chunks); 79728 used
  ErrorContext: 8192 total in 1 blocks; 8160 free (6 chunks); 32 used
< 2016-04-28 12:09:21.634 BST >ERROR:  out of memory
< 2016-04-28 12:09:21.634 BST >DETAIL:  Failed on request of size 5.
< 2016-04-28 12:09:21.634 BST >CONTEXT:  converting column "drop_entry_status" for foreign table scan of "dbentry", row 27940522
< 2016-04-28 12:09:21.634 BST >STATEMENT:  analyze verbose enauni.dbentry (bioseqid);
```

We thought about manually setting the statistics based on Oracle queries against _all_tab_statistics_ and _all_tab_col_statistics_ using something like:

`alter table schema.foreign_table alter column column_name set (n_distinct = N)`

This could maybe be the approach of the Oracle FDW in case of very large tables.

We have a very easily reproducible test case in house, in case you would like us to perform any test.

Thanks
Alessio

**Comment by laurenz** [comment] 2016-04-29 15:09
Yes, there must be a memory leak somewhere.
I'll see what I can find.

**Comment by acheccuc** [comment] 2016-04-30 06:14
Thanks a lot for looking into that.

I was wondering if (see my initial comment) it wouldn't be better to rely on the statistics collected on the Oracle side (i.e. _all_tab_statistics_ and _all_tab_col_statistics_) rather than streaming the entire table content and perform ANALYZE on the PostgreSQL instance.
In our use cases (tables with ~1bln records) the ANALYZE operation could last for many hours and impose a considerable load (at least on the buffer cache) on both the Oracle and PostgreSQL side.

**Comment by laurenz** [comment] 2016-04-30 07:53
Thanks for sharing your ideas.

Collecting Oracle's statistics sounds sweet, but it is difficult:

- It is not guaranteed that Oracle's statistics layout doesn't change between versions. It would be a pain to keep up with different server versions.
- Even more painful is the fact that Oracle's statistics are in different formats and have different meaning than PostgreSQL's statistics (table statistics are highly implementation specific). So I expect it would be pretty difficult, if possible at all, to translate the statistics.
- You cannot respect `default_statistics_target` that way.

When I get back to the office next week, I'll try to come up with some workarounds (sample only part of the table, maybe) to help you quickly.

I'll try to find the root cause of the memory leak and hope that it can be fixed.

**Comment by laurenz** [comment] 2016-05-02 12:18
There is one workaround I can think of:

    CREATE FOREIGN TABLE enauni.dbentry [...] OPTIONS (table '(SELECT * FROM datalib.dbentry WHERE rownum < 100000)');
    ANALYZE large;
    ALTER FOREIGN TABLE enauni.dbentry OPTIONS (ADD schema 'DATALIB', SET table 'DBENTRY');
    UPDATE pg_class SET reltuples = 800000000 WHERE oid = ...;

It is ugly, I admit that.
The problem is probably to find a sample that is statistically relevant; `WHERE rownum < 100000` is probably not good enough.

**Comment by legrandlegrand** [comment] 2016-05-03 11:03
maybe you could use the SAMPLE feature from Oracle

`SELECT * FROM TABLE_NAME SAMPLE BLOCK (1);`

will take 1% sample of the blocks  ...

**Comment by laurenz** [comment] 2016-05-03 15:27
Ah, I see where the memory leak is.
I'll try to fix it tomorrow!

**Comment by acheccuc** [comment] 2016-05-03 15:55
Thanks a lot.
I will give it a try as soon as the change is pushed.

**Comment by laurenz** [comment] 2016-05-04 09:55
I just committed c67ea9a88162f7434a02b92d12614f71772106fb which should fix the problem.
@acheccuc, you can test (and thanks for that!).
I'll still be in the office for the next couple of hours, but I'll be gone for the 4 next days, so don't worry if I don't respond immediately.

@legrandlegrand, I really like your idea with the [`SAMPLE` clause](http://docs.oracle.com/cd/E11882_01/server.112/e41084/statements_10002.htm#SQLRF55238)!
The feature seems to exist since Oracle 8.
I can see a good enhancement there:
Define a new table option `sample_percent` and append `SAMPE BLOCK (n)` to the remote Oracle query for `ANALYZE`.

**Comment by acheccuc** [comment] 2016-05-04 11:01
@laurenz I have just started a test and memory usage seems to be very stable. It will take many hours to complete, I will send you another message when it's complete.

Thanks a lot

**Comment by acheccuc** [comment] 2016-05-05 09:36
@laurenz The first test has been completely successful, I am running another one just now. Every run takes a while against the >800mln records Oracle table.

**Comment by acheccuc** [comment] 2016-05-06 10:26
@laurenz The complete test has been successful. The issue is solved on my side. Thanks a lot!
@legrandlegrand I remember that there may be some caveats creeping in with SAMPLE (please check: https://jonathanlewis.wordpress.com/2010/03/12/sample-clause/). If I am not badly wrong SAMPLE relies on primary keys to exist, which could not be the case in some circumstances. Nevertheless it's a very good idea... Thanks

**Comment by 3kkani** [comment] 2016-05-06 17:19
@all Thanks for sorting out this issue

The sample clause seems a good starting point but I would use the syntax which roughly indicates the percentage of the rows to return i.e. SAMPLE (1) for 1%. 

According to 11gr2 doc (see [http://docs.oracle.com/cd/E11882_01/server.112/e41084/statements_10002.htm#i2065953](url)) the BLOCK claue is meant to "_perform random block sampling instead of random row sampling_" and imply "_full table scans or index fast full scans_" even when "_a more efficient execution path exists_".

in the same palce the documented restrictions are:

- You cannot specify the SAMPLE clause in a subquery in a DML statement.
- You can specify the SAMPLE clause in a query on a base table, a container table of a materialized view, or a view that is key preserving. You cannot specify this clause on a view that is not key preserving.

So the PK issue should arise only when mapping and analyzing some view where keys are not preserved.

**Comment by legrandlegrand** [comment] 2016-05-07 14:06
OK for SAMPLE (x)

But I'm new with PostgreSQL and Oracle_fdw and I don't understand :
- how the planner will take into account Indexes (or partitions) existing on Oracle table ...
- what will appen if Oracle stats are wrong (performances may be wrong  even after a PostgreSQL ANALYSE )
- how to get be best access path to a view

wouldn't a **use_remote_estimate** feature more accurate to choose the best plan from Oracle (to be able to catch the quickest index or partition and stay in line with Oracle execution plan / Oracle stats )
?

**Comment by laurenz** [comment] 2016-05-09 09:30
@acheccuc, thanks for checking.

About using `SAMPLE BLOCK (n)`, I don't think that that has anything to do with primary keys. It just takes a sample of blocks rather than rows, so it can only work when the notion of a block makes sense in the context of the query. If it doesn't make sense, it will fall back to row sampling.
If it can use block sampling, it will be more efficient (but maybe less random).

I imagine documenting it as *"This feature works with Oracle tables, but won't work with all queries and views and will result in interesting error messages if it doesn't work"*.

The blog post is interesting; if true, it would make the feature less valuable. Or maybe I should just always use `SAMPLE (n)` rather than `SAMPLE BLOCK (n)`&hellip;

**Comment by laurenz** [comment] 2016-05-09 14:57
I created a branch "sample_percent" and committed a change there that introduces a parameter of that name that causes ANALYZE to use the `SAMPLE BLOCK (x)`clause.

I'd be happy if you give it a try with your large table, you can get it [as ZIP archive](https://github.com/laurenz/oracle_fdw/archive/sample_percent.zip) or you can check it out with

    git clone -b sample_percent https://github.com/laurenz/oracle_fdw.git

@legrandlegrand, if you tell me your real name I'd be happy to add it to the CHANGELOG to give you credit.

**Comment by acheccuc** [comment] 2016-05-09 15:07
I have just started a run after recompiling Oracle FDW using the sample_percent branch...
Should I have expected something in the PostgreSQL log (log_min_messages is DEBUG1)?

Thanks a lot

**Comment by laurenz** [comment] 2016-05-09 15:10
You should see a message like

    DEBUG:  oracle_fdw: remote query is SELECT "COL1", "COL2" FROM "TABLENAME" SAMPLE BLOCK (50.000000)

**Comment by acheccuc** [comment] 2016-05-09 19:06
The test I started earlier completed, I used a 5% sample size and the ANALYZE operation took 54m instead of many hours.
In attachment I have stuck a file with the comparison of the gathered stats, the upper part is related to the full analyze, while the sample estimate is at the bottom.
I will test with other sample percentages tomorrow and I will compare with the stats on the Oracle side. Sorry, but I am on the road right now...

**Comment by laurenz** [comment] 2016-05-10 09:25
Thanks a lot for the thorough investigation.
That the runtime has decreased is a first success!

I don't fully understand the contents of `stats_cmp.txt`; it doesn't seem to be straight from `pg_stats`:

- What is `common_vals` and why is there only one for the `analysis_id` column?
- What is the `dist_freq` column?
- How can it be that the sample analysis has higher counts for `n_distinct` than the full analysis for the `analysis_id` and `dbcode` columns? Did the data change?

It would be most helpful to compare the output of `SELECT * FROM pg_stats`.

In addition it would be quite interesting to compare the `reltuples` column of `pg_class` for both runs to see if the sample size is about right (which the blog post referenced above denies).

By the way, what is your Oracle server version?

**Comment by acheccuc** [comment] 2016-05-10 09:33
Sorry, I should have added the query I used to dump the stats:
`SELECT tablename, schemaname, attname As colname, n_distinct, array_to_string(most_common_vals, E'\n') AS common_vals, array_to_string(most_common_freqs, E'\n') As dist_freq FROM pg_stats where schemaname='enauni' and tablename='dbentry_sample' ORDER BY schemaname, tablename, attname limit 10;`

I am currently running a new run with sample size of 10% of the blocks. I will send you the report as soon as it's complete.

The Oracle version is 11.1.0.7 in this case.

**Comment by laurenz** [comment] 2016-05-10 14:14
Thanks for the explanation.
I still don't understand why the sample analysis has higher counts for `n_distinct` than the full analysis.

**Comment by laurenz** [comment] 2016-05-18 08:12
Di you have any results?
I'm particularly interested to know if the `reltuples` column in `pg_class` is close to reality after ANALYZE with `sample_size` set.

**Comment by acheccuc** [comment] 2016-05-18 10:02
Sorry I have been caught by a lot of very urgent tasks. Will send a report later today… Apologies for the large delay.

**Comment by acheccuc** [comment] 2016-05-19 09:27
Here is the result of my test. I had 4 runs with sample sizes of 100%, 25%, 10% and 5%. I have attached two files with columns stats gathered on the PostgreSQL and Oracle sides.
On the reltuples side, the estimation is very good even with a small sample:

Oracle dba_tab_statistics.num_rows: 817878667
PostgreSQL 100%: 815173952
PostgreSQL 25%:   814422656
PostgreSQL 10%:   816355712
PostgreSQL 5%:     816198656

[dbentry_oracle_stats.zip](https://github.com/laurenz/oracle_fdw/files/272241/dbentry_oracle_stats.zip)
[dbentry_stats.zip](https://github.com/laurenz/oracle_fdw/files/272240/dbentry_stats.zip)

**Comment by laurenz** [comment] 2016-05-20 08:10
Thanks for the detailed report, that looks good enough.
I have merged the branch, and the feature will be in the next release.
It is a pleasure to work with people like you guys!

**Closed by laurenz** 2016-05-20 08:10 UTC
Labels: bug
