### ISSUE TITLE
Cannot delete more than one row

### ISSUE THREAD

**Issue by alexign** [laurenz/oracle_fdw#33] opened 2015-06-03 12:31 UTC
Hello!
I got the table :
CREATE FOREIGN TABLE dop_p_ft2( user_sys varchar (60) OPTIONS (key 'true'), id_dd bigint) SERVER oradb OPTIONS (schema 'INFOSTREAM_D', table 'DOP_P');

After 
delete from dop_p_ft2  ive got :
ERROR:  DELETE on Oracle table removed 7 rows instead of one in iteration 1
HINT:  This probably means that you did not set the "key" option on all primary key columns.

In source code i found in oracle_fdw.c:

if (rows != 1)
		ereport(ERROR,
				(errcode(ERRCODE_FDW_UNABLE_TO_CREATE_EXECUTION),
				errmsg("DELETE on Oracle table removed %d rows instead of one in iteration %lu", rows, fdw_state->rowcount),
				errhint("This probably means that you did not set the \"key\" option on all primary key columns.")));

That means that i cant delete more than one row in time when unsing oracle_fdw?
Thank you in advance!

**Comment by laurenz** [comment] 2015-06-05 08:12
You can delete more than one row, the problem is a different one.

Foreign data wrappers perform deletion in two steps: First the foreign table is scanned for rows to delete, then (maybe after some additional filtering on the PostgreSQL side) some of these rows are deleted one by one.
That is why oracle_fdw needs to know the primary key of the table, to identify a single row.

In your case, the column ``user_sys`` that you marked as primary key (option ``key``) cannot be the primary key in the corresponding Oracle table, because the statement ``DELETE FROM infostream_d.dop_p WHERE user_sys = '...'`` deleted more than one row.
I cannot allow that because it could mean that rows get deleted that should not be deleted.

Imagine the following scenario:

    INSERT INTO dop_p_ft2 VALUES ('one', 1);
    INSERT INTO dop_p_ft2 VALUES ('one', 2);
    DELETE FROM dop_p_ft2 WHERE id_dd = 2;

The DELETE statement would first scan the table for ``id_dd = 2``, find one row, retrieve its ``user_sys`` an then delete the row with ``user_sys = 'one'``, which would mistakenly delete both rows.

Solution: use the option ``key`` to identify the real primary key columns.
What is the table definition of the Oracle table?

**Comment by alexign** [comment] 2015-06-05 09:10
Ok got it! I found that on oracle side table didnt have prim key on 
user_sys column!
Thank you!


On 05.06.2015 11:12, Laurenz Albe wrote:
>
> You can delete more than one row, the problem is a different one.
>
> Foreign data wrappers perform deletion in two steps: First the foreign 
> table is scanned for rows to delete, then (maybe after some additional 
> filtering on the PostgreSQL side) some of these rows are deleted one 
> by one.
> That is why oracle_fdw needs to know the primary key of the table, to 
> identify a single row.
>
> In your case, the column |user_sys| that you marked as primary key 
> (option |key|) cannot be the primary key in the corresponding Oracle 
> table, because the statement |DELETE FROM infostream_d.dop_p WHERE 
> user_sys = '...'| deleted more than one row.
> I cannot allow that because it could mean that rows get deleted that 
> should not be deleted.
>
> Imagine the following scenario:
>
> |INSERT INTO dop_p_ft2 VALUES ('one', 1);
> INSERT INTO dop_p_ft2 VALUES ('one', 2);
> DELETE FROM dop_p_ft2 WHERE id_dd = 2;
> |
>
> The DELETE statement would first scan the table for |id_dd = 2|, find 
> one row, retrieve its |user_sys| an then delete the row with |user_sys 
> = 'one'|, which would mistakenly delete both rows.
>
> Solution: use the option |key| to identify the real primary key columns.
> What is the table definition of the Oracle table?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/laurenz/oracle_fdw/issues/33#issuecomment-109199471>.
>

-- 
Alex Ignatov
Postgres Professional: http://www.postgrespro.com
The Russian Postgres Company



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Closed** 2015-06-05 09:21 UTC
