### ISSUE TITLE
FDW date conversion issue from oracle

### ISSUE THREAD

**Issue by adnanhamdussalam** [laurenz/oracle_fdw#201] opened 2017-09-14 07:32 UTC
Hi ,

I am trying to create a foreign table but facing below error:

ERROR: column "actual_inc_start_time" of foreign table "probsummarym1" cannot be converted to or from Oracle data type
SQL state: HV004 

Regards,

Adnan

**Comment by laurenz** [comment] 2017-09-15 11:20
Can you show the Oracle and PostgreSQL table definitions?

**Comment by adnanhamdussalam** [comment] 2017-09-18 06:39
Hi ,

Thank you for update. 

The data type in oracle is "date" of column "actual_inc_start_time" and in postgreSql we are creating the foreign table with data type "date".
But when I use data type " varchar " on postgresql while creating the table it starts extracting the data.

Regards,

Adnan

**Comment by laurenz** [comment] 2017-09-18 06:44
I see. I would still like toi see the `CREATE TABLE` statement from Oracle and the `CREATE FOREIGN TABLE` statement from PostgreSQL. there is probably a mismatch somewhere, and I might be able to see what the problem is.

**Comment by adnanhamdussalam** [comment] 2017-09-18 07:27
Hi,

The foreign table created successful but while executing the select query gives the below error:
ERROR: column "actual_inc_start_time" of foreign table "probsummarym1" cannot be converted to or from Oracle data type 
SQL state: HV004

 
[tab_def_oracle_POSTGRESQL.txt](https://github.com/laurenz/oracle_fdw/files/1309939/tab_def_oracle_POSTGRESQL.txt)

**Comment by laurenz** [comment] 2017-09-18 07:57
The problem is that in oracle_fdw, columns are *not* mapped by name, but by position.

So no matter how you name the columns, the first column in the foreign table will correspond to the first column in the Oracle table, and so on.

In your case, the PostgreSQL column `actual_inc_start_time` (type `timestamp without time zone`)  corresponds to the Oracle column `priority_code` (type `VARCHAR2(40)`), hence the error.

You will have to define a foreign table with columns for *all* oracle columns up to the last Oracle column you are interested in. Fortunately oracle_fdw will only fetch the columns that you need for your `SELECT` statement, so that shouldn't be a problem.

**Comment by adnanhamdussalam** [comment] 2017-09-18 08:12
Hi ,

Thank you for the update. I will check, test it and then update you accordingly.
Once again laurenz thanks a lot for your prompt support.

Regrads,

Adnan

**Comment by laurenz** [comment] 2017-10-05 13:48
I'll close this issue &ndash; please reopen it if this is still a problem.

**Closed by laurenz** 2017-10-05 13:49 UTC
Labels: problem
