### ISSUE TITLE
clob with length > 21800 in oracle does not come over to text

### ISSUE THREAD

**Issue by vlisterik** [laurenz/oracle_fdw#614] opened 2023-10-09 15:19 UTC
Hi Laurenz,
Thanks for oracle_fdw!

First let me tell what version we use:

```
SELECT oracle_diag('oracle_xxx');
                                                       oracle_diag
-------------------------------------------------------------------------------------------------------------------------
 oracle_fdw 2.6.0devel, PostgreSQL 15.2 (Ubuntu 15.2-1.pgdg22.04+1), Oracle client 21.10.0.0.0, Oracle server 19.0.0.0.0
```

In oracle we have a table with a clob:
```
desc LVBX_OWN.TBAG_BERICHT
Name                    Null?      Type
BERI_ID                 NOT NULL   NUMBER
BERI_CONTENT                       CLOB
```

In postgres we create the foreign table:
```
drop foreign table bag_schema.tbag_bericht_vlist_ft;
create foreign table bag_schema.tbag_bericht_vlist_ft (beri_id bigint, len_ora bigint, beri_content text, beri_content_part text, beri_content_part60000 text ) 
SERVER oracle_xxx OPTIONS
(prefetch '1000', "table" '(select beri_id,length(beri_content) as len_ora,beri_content,substr(beri_content,1,21800) as beri_content_part, substr(beri_content,1,60000) as beri_content_part60000 from LVBX_OWN.TBAG_BERICHT )');
select beri_id, len_ora,length(beri_content) as len_ber,length(beri_content_part) as len_part,length(beri_content_part60000) as len_part6000,beri_content,beri_content_part60000   from bag_schema.tbag_bericht_vlist_ft where beri_id=1000000052443 ;
     beri_id    | len_ora | len_ber | len_part | len_part6000 | beri_content | beri_content_part60000
---------------+---------+---------+----------+--------------+--------------+------------------------
 1000000052443 |   29271 |       0 |    21800 |            0 |              |

```
For the rows where the length of the clob in oracle is below 21800 everything goes fine.
Is it larger than 21850 then the clob does not arrive in postgres and it reports a length of 0.
When I use a substring which is executed on the oracle side it works for that part.

Please let me know if it helps to give you more information.
With kind regards, Erik.

**Comment by laurenz** [comment] 2023-10-09 16:13
I cannot reproduce that on my system:

```
                                       oracle_diag                                        
══════════════════════════════════════════════════════════════════════════════════════════
 oracle_fdw 2.6.0, PostgreSQL 17devel, Oracle client 18.4.0.0.0, Oracle server 18.0.0.0.0
```

Can you show me the output of `EXPLAIN` for the query? What happens if you let that query run on Oracle?

**Comment by laurenz** [comment] 2023-10-09 18:58
I realize that you are using an older version of oracle_fdw, and there have been changes in the handling of LOBs lately. Do you observe that problem with 2.6.0 too?

**Comment by laurenz** [comment] 2023-10-10 06:48
Can you show me the output of `EXPLAIN` for the query?

What happens if you let that query run on Oracle?

What is your Oracle database character set and your PostgreSQL server encoding?

Perhaps you can somehow transmit the contents of one of these CLOBs to me. That might enable me to reproduce what you see.

**Comment by kad-visser3** [comment] 2023-10-10 07:14
CREATE FOREIGN TABLE IF NOT EXISTS prdbag_schema.tbag_bericht_tst(
    beri_id numeric OPTIONS (key 'true') NOT NULL,
    beri_berichtid character varying(40) NULL COLLATE pg_catalog."default",
    beri_type character varying(4) NULL COLLATE pg_catalog."default",
    beri_ontvangen timestamp(0) without time zone NOT NULL,
    beri_applicatie character varying(20) NULL COLLATE pg_catalog."default",
    beri_tijdstip timestamp(3) without time zone NULL,
    beri_entiteittype character varying(3) NULL COLLATE pg_catalog."default",
    beri_verwerkt timestamp(0) without time zone NULL,
    beri_gemeentecode character varying(4) NULL COLLATE pg_catalog."default",
    beri_foutcode character varying(7) NULL COLLATE pg_catalog."default",
    beri_foutomschrijving character varying(300) NULL COLLATE pg_catalog."default",
    beri_objectids character varying(50) NULL COLLATE pg_catalog."default",
    beri_content text NULL COLLATE pg_catalog."default",
    beri_klantnummer character varying(10) NULL COLLATE pg_catalog."default",
    beri_klantnaam character varying(100) NULL COLLATE pg_catalog."default"
)
    SERVER oracle_prd
    OPTIONS (schema 'LVBP_OWN', table 'TBAG_BERICHT');

--ALTER FOREIGN TABLE tbag_bericht_tst OPTIONS (ADD max_long '1000000'); --this option did not help

select  from prdbag_schema.tbag_bericht_tst where beri_id = 1000000003777;

<html>
<body>


Node Type | Foreign Scan
-- | --
Operation | Select
Parallel Aware | false
Async Capable | false
Relation Name | tbag_bericht_tst
Alias | tbag_bericht_tst
Oracle query | SELECT /*103c393a6681dc3*/ r1.&quot;BERI_ID&quot; FROM &quot;LVBP_OWN&quot;.&quot;TBAG_BERICHT&quot; r1 WHERE (r1.&quot;BERI_ID&quot; = 1000000003777)
loops | 1


</body>
</html>

**Comment by kad-visser3** [comment] 2023-10-10 07:16
In oracle the field beri_content is 52k in size. oracle_fdq shows zero.

**Comment by laurenz** [comment] 2023-10-10 07:27
What does this other foreign table have to do with the problem at hand? I am confused.

Why don't you answer my questions?

**Comment by kad-visser3** [comment] 2023-10-10 07:32
It is the same foreign table from a coworker. It is simpel import table with CLOB tot TEXT and above 20K all results are zero length. Just INSERT postgres SELECT oracel foreign table.

**Comment by laurenz** [comment] 2023-10-10 07:38
Sorry, but I cannot help you without relevant information.

**Comment by kad-visser3** [comment] 2023-10-10 07:49
I do not understand what you mean by send EXPLAIN for query. Which query? I can send the message but I will try that in mail. This contains possible sensitive company data.

**Comment by laurenz** [comment] 2023-10-10 07:55
Thanks, that is the information I wanted. It all looks as expected, and you are not using any weird encodings.

Sending me an example of the CLOB is only helpful if the contents make a difference for the problem. If you observe the same behavior everywhere, regardless of what is in the CLOB, it probably doesn't make a difference.

My last straw is the oracle_fdw version: can you try with the latest code?

**Comment by kad-visser3** [comment] 2023-10-10 08:01
We are not able to install the latest version. I have asked the company that delivers us the unix machine with postgres database to install the newest oracle_fdw. I do not know when that completes.

**Comment by laurenz** [comment] 2023-10-10 08:20
I see. Perhaps you can install PostgreSQL and oracle_fdw on a test machine?

To see if the upgrade of oracle_fdw is promising, I could try with the version that you are using. 2.6.0devel is somewhere in the middle between 2.5.0 and 2.6.0. Do you know which was the latest commit, or when exactly oracle_fdw was pulled from the repository?

I would also have expected a client problem, but `length()` is calculated on the PostgreSQL server, and if that already shows 0, it is not a client problem.

I am at a loss to reproduce the problem.

**Comment by vlisterik** [comment] 2023-10-10 08:54
Hi Laurenz, Thanks  for al your quick responses.
Does the following answer the question about the version:
    ```
version=fb9d57fe47591937ce9eb81e31cb3ea9bc7d494a
    git checkout ${version}
    https://github.com/laurenz/oracle_fdw/tree/fb9d57fe47591937ce9eb81e31cb3ea9bc7d494a
```
The foreign table does a select at oracle including the length there and passes that, but when we determine the length at postgres it is 0. For clobs <21800 there is no problem. Although that might be clear already....

**Comment by laurenz** [comment] 2023-10-10 09:14
Yes, that answers the question of the version admirably.

That version is missing the important fix ddce4116b0f006c7d6148a7ac439b5f376511484, but that shouldn't affect your query, nor should any of the other bugs fixed since. Anyway, I tried, but it works for me with that version and PostgreSQL v16.

So there is little point in you trying with the latest release; the problem is elsewhere. Unfortunately I don't know where.

**Comment by laurenz** [comment] 2023-10-10 14:32
In understand the problem. I tried your latest example, and my result is

```none
    beri_id    │ len_ora │ len_ber │ len_part │ len_part6000 
═══════════════╪═════════╪═════════╪══════════╪══════════════
 9000011390561 │  983010 │  983010 │    21800 │        60000
 9000011390562 │   21800 │   21800 │    21800 │        21800
```

**Comment by vlisterik** [comment] 2023-10-16 14:07
We have done some more testing and re-testing on different environments.

We run into this issue with:
1) oracle_fdw 2.6.0devel, PostgreSQL 15.2 (Ubuntu 15.2-1.pgdg22.04+1), Oracle client 21.10.0.0.0, Oracle server 19.0.0.0.0
2) oracle_fdw 2.6.0, PostgreSQL 15.2 (Ubuntu 15.2-1.pgdg22.04+1), Oracle client 21.10.0.0.0, Oracle server 19.0.0.0.0
(in all cases ORACLE_HOME=/usr/lib/oracle/instantclient_21_10)
but it works fine with:
3) oracle_fdw 2.5.0devel, PostgreSQL 15.2 (Ubuntu 15.2-1.pgdg22.04+1), Oracle client 21.10.0.0.0, Oracle server 19.0.0.0.0
4) oracle_fdw 2.4.0devel, PostgreSQL 13.8 (Ubuntu 13.8-1.pgdg20.04+1), Oracle client 21.1.0.0.0, Oracle server 19.0.0.0.0

For now we will continue with 3)

**Comment by laurenz** [comment] 2023-10-16 14:45
Thanks for the information.

That's of course not a future-proof solution, since you cannot use a current oracle_fdw that way. But I understand that you see no better option. Since I cannot reproduce the problem, I cannot fix it.

Shall I close the issue as "unsolved" for now? Perhaps some day somebody will report a similar problem, and I can reproduce what you see.

**Comment by vlisterik** [comment] 2023-10-17 09:45
Thanks for your help, it's ok to close this issue.

**Comment by vlisterik** [comment] 2023-10-17 09:47
Yes it's ok to close it as unsolved. I did not see that option. Can you please do so?
Thanks for your support!

**Comment by laurenz** [comment] 2023-10-17 13:12
Thanks for the feedback, and it irks me that I cannot reproduce that problem and track it down.
Let's hope that somebody else (or you) can narrow down the problem at some point in the future.

**Closed by laurenz** 2023-10-17 13:12 UTC
Labels: problem

**Comment by laurenz** [comment] 2024-02-06 13:12
Issue #614 is probably the same problem as this one.
