### ISSUE TITLE
import foreign schema case folding - lower

### ISSUE THREAD

**Issue by sahapasci** [laurenz/oracle_fdw#329] opened 2019-06-23 19:59 UTC
As I understood, fold_case function uses `DEFAULT_COLLATION_OID` which returns current database collation. In my case, database collation is tr_TR.utf-8. Because of that, when a oracle table with char `I (U+0049)` is lowered the character became `ı (U+0131)` but it should become `i (U+0069)`. So I changed the constant used in function into `C_COLLATION_OID`. 
IMHO, C_COLLATION_OID is more appropriate when using lower case for table names.

**Comment by laurenz** [comment] 2019-06-24 09:12
I understand your concern, but this is a problem that is impossible to solve in a way that makes everybody happy.

For example, If you have a table called `KADIN` in your Turkish Oracle database, you'd probably want that table to be called <code>kad&#x131;n</code> in PostgreSQL, right? On the other hand, if you use English table names in your Turkish database (which is usually a good idea), you would *not* want `INFORMATION` to become <code>&#x131;nformat&#x131;on</code>.

Admittedly, there are probably more Turkish databases with a table `INFORMATION` than there are databases with a table `KADIN`, so you might be right when it comes to `I`.

But what if you have a column <code>K&Uuml;&Ccedil;&Uuml;K_INFORMATION</code> In Oracle? Should that become <code>k&Uuml;&Ccedil;&Uuml;k_information</code> or <code>k&uuml;&ccedil;&uuml;k_&#x131;nformat&#x131;on</code>? The `"C"` collation will produce the first result, while `"tr_TR.utf8"` will produce the second.

I just thought that &ldquo;do it according to the database's default locale&rdquo; would be the least surprising option. What do you think?

Anyway, the problem is easy to fix: You can always change the offending names after using `IMPORT FOREIGN SCHEMA`.

**Comment by sahapasci** [comment] 2019-06-24 14:16
Thank you for the detailed explanation. I am already convinced that current value is best for most. Now, I think, I can develop that part as an option for `IMPORT FOREIGN SCHEMA`.

**Comment by laurenz** [comment] 2019-06-24 14:39
Do you want to keep the issue open?

**Comment by sahapasci** [comment] 2019-06-24 20:50
Yes please

**Comment by laurenz** [comment] 2019-07-03 10:22
We can close this issue, right?

**Comment by sahapasci** [comment] 2019-07-03 10:23
Sure thanks :)

**Closed** 2019-07-03 10:24 UTC
Labels: enhancement
