### ISSUE TITLE
how to solve could not load library "/usr/pgsql-11/lib/oracle_fdw.so": /usr/pgsql-11/lib/oracle_fdw.so: undefined symbol: errcontext

### ISSUE THREAD

**Issue by odijh** [laurenz/oracle_fdw#312] opened 2019-04-20 01:24 UTC
i'm new in linux, and i'm trying to create dblink from postgres 11 to oracle, on my server  installed postgres 9.2 and postgres 11, i got some message

`psql (9.2.24, server 11.2)
WARNING: psql version 9.2, server version 11.0.
         Some psql features might not work.
`
i guess while i install oracle_fdw-2.1.0 it is installed on postgres 9.2 but i'm in postgres 11 while i trying to install oracle_fdw extension..
how can i solve this problem?
thanks

**Comment by laurenz** [comment] 2019-04-20 12:00
This warning is no problem in this context.

Just install oracle_fdw in the PostgreSQL software directory of your choice (9.2 or v11) and then run `CREATE EXTENSION`. The version of `psql` used doesn't matter.

**Comment by odijh** [comment] 2019-04-25 02:07
but i can't CREATE EXTENSION with error like

ERROR: could not load library "usr/pgsql-11/lib/oracle_fdw.iso": libclntsh.so.18.1: cannot open shared object file: No such file or directory
how can i solve it?
thanks

**Comment by japinli** [comment] 2019-04-25 06:46
@odijh Did you add the path of `libclntsh.so.18.1` in your library search path?

**Comment by laurenz** [comment] 2019-04-25 13:43
This is a duplicate of #64 and #167. Relevant other issues: #161 and #160 (Windows).

Essentially, you either have to set `LD_LIBRARY_PATH` in the PostgreSQL server's environment or use `ld.so.conf` and `ldconfig` to add the directory containing `libclntsh.so.18.1` to the library path.

Attention with the second method &mdash; only yesterday doing this for an Oracle server installation on Fedora Linux caused boot to fail.

**Comment by odijh** [comment] 2019-04-26 00:44
@japinli i set the path libclntsh.so.18.1 in pgsql 9.2, how can i set the path to pgsl 11?
@laurenz  i also set the LD_LIBRARY_PATH to pgsql 11 by using export LD_LIBRARY_PATH=/usr/lib/oracle/18.5/client64/lib, but its not working

**Comment by laurenz** [comment] 2019-04-26 07:09
That won't help unless you start PostgreSQL from the shell where you set the environment variable.

It depends on how PostgreSQL is started.

If you tell me what Linux distribution this is, how you installed PostgreSQL and how the startup process works, I can try to help you.

**Comment by odijh** [comment] 2019-04-29 01:41
@laurenz i tried to uninstall postgresql 9.2 and install postgresql 11 and then changed path pg_config to pgsql11, and its works..
thanks @laurenz @japinli

**Comment by laurenz** [comment] 2019-04-29 07:05
Thanks for the feedback. The it was probably a problem with mixing up the installations somewhere. oracle_fdw will run on both v11 and 9.2.

**Closed by laurenz** 2019-04-29 07:05 UTC
Labels: duplicate, problem
