### ISSUE TITLE
Localization issues with DATE

### ISSUE THREAD

**Issue by tjheiska** [laurenz/oracle_fdw#545] opened 2022-08-26 08:11 UTC
Hi,

We have to work with Oracle server having default NLS_DATE_LANGUAGE=ESTONIAN and NLS_DATE_FORMAT=DD.MM.RRRR. All the data we need to import are in views. Other views work fine with dates, but for some reason one view throws 
`ERROR:  error executing query: OCIStmtExecute failed to execute remote query
DETAIL:  ORA-01861: literal does not match format string`

There's a workaround for this when manually using psql:
`SELECT oracle_execute('mysrv','ALTER SESSION SET NLS_DATE_LANGUAGE = ''ESTONIAN''');
SELECT oracle_execute('mysrv','ALTER SESSION SET NLS_DATE_FORMAT = ''DD.MM.RRRR''');
set datestyle to German;`

After that it works fine. The problem is that we cannot do the same with java since the datestyle cannot be anything else than ISO when using JDBC-driver. The column type is simply `timestamp(0) without time zone` which is same in the other views we are using.

We don't really have any possibility to change anything in the server side, so any ideas how to fix or get around this would be really appreciated.

oracle_diag gives: `oracle_fdw 2.4.0, PostgreSQL 11.12 (Debian 11.12-1.pgdg90+1), Oracle client 21.3.0.0.0, Oracle server 11.2.0.4.0`

**Comment by laurenz** [comment] 2022-08-26 15:09
The only way to fix that is to change the view definitions. Sorry.
A view that only works with certain settings of `NLS_DATE_FORMAT` is broken.
It should be very simple to add explicit `to_char()` and `to_date()` calls instead of relying on implicit conversion.
oracle_fdw could of course use `to_char` with the appropriate format when reading data, but writing `date`s would be difficult.

**Comment by laurenz** [comment] 2022-08-26 15:12
This is a duplicate of #527 and #462.

**Comment by tjheiska** [comment] 2022-08-30 05:59
Thanks. I'll try to bother the database owner then, if they could somehow adapt to our problem. Separate periodically launched cronjob that refreshes a materialized view would be a workaround that we could make for our project, but is quite a hack =D

**Comment by laurenz** [comment] 2022-08-30 11:50
Thanks for the feedback. I'll close this issue.

**Closed by laurenz** 2022-08-30 11:50 UTC
Labels: duplicate, problem
