### ISSUE TITLE
Issue with Wider Tables

### ISSUE THREAD

**Issue by patibandlakoshal** [laurenz/oracle_fdw#168] opened 2017-05-24 11:46 UTC
We are using postgres 9.5 on RHEL 6. First thing Oracle_FDW working amazingly well in 99% of the scenarios. I love import schema. So easy to work with.  Oracle_FDW is also working amazing well with bigger tables. We created 5 copies of 60 Million Record table in (1/2 hour) (5 copies got kicket off simultaneously). Size of these 5 copies were about 40 Gigs. Whereas where we have wider table with about 479 columns containing 20 gigs of data is talking about 11 hours. We tried different preftech options but still no luck.  We tried splitting 11 million into 5 parallel session still no luck. 
Good thing is it is not failing. This is simple CTAS. no constraints, no triggers

**Comment by laurenz** [comment] 2017-05-24 13:17
479 columns?! Wow.

What Oracle data types are used? Some data types may impair performance.
[The documentation][1] says:

> **Note:**
> Prefetching is not in effect if `LONG`, `LOB` or Opaque Type columns (such as `XMLType`) are part of the query.

How much memory is used on the PostgreSQL side? Maybe the machine is paging (memory pressure, I/O on swap).

 [1]: http://docs.oracle.com/cd/E11882_01/appdev.112/e10646/oci04sql.htm#LNOCI16355

**Comment by patibandlakoshal** [comment] 2017-05-24 17:41
Here is the list of Data Types being used.
14    CHAR
6    CLOB
6    NUMBER
453    VARCHAR2

clover ETL Tool was able to load the data in 5 hours and FDW is taking 11 hours. Something I am not configuring properly I believer.
Is there some setting I can use.

 Thanks Koshal

On Wednesday, May 24, 2017, 9:17:57 AM EDT, Laurenz Albe <notifications@github.com> wrote:
479 columns?! Wow.

What Oracle data types are used? Some data types may impair performance.
The documentation says:


Note:
Prefetching is not in effect if LONG, LOB or Opaque Type columns (such as XMLType) are part of the query.


How much memory is used on the PostgreSQL side? Maybe the machine is paging (memory pressure, I/O on swap).

**Comment by patibandlakoshal** [comment] 2017-05-25 20:52
Interesting this is when we schedule a job in Clover the wider table that has (11 Million rows) got completed in 5 hours vs 11 hours  using oracle_fdw and narrow Table which 20 columns and 60 Million rows got completed in 1/2 hour using FDW and took almost 12 hours in Clover.

I honestly think I am missing some setting in Oracle_FDW. We look at memory and IO on Postgres Database everything looks good as per Infra Team.

I ran this job almost 10 times all the times it got completed without an error.  I tried different prefetch but it was not helpful.

**Comment by laurenz** [comment] 2017-05-26 07:54
As I told you in my first reply, prefetch won't work because there are `CLOB` columns.
That is probably why it takes so long.

I find that there is LOB prefetching in Oracle.
Could you apply this patch: [lob_prefetch_patch.txt](https://github.com/laurenz/oracle_fdw/files/1031172/lob_prefetch_patch.txt)
Then check if the performance improves for you.

If I understand the documentation correctly, this will prefetch the whole `CLOB` (are they large?), but it will not allow row prefetching.

**Comment by patibandlakoshal** [comment] 2017-05-26 14:14
Thanks a lot! How do i apply this patch. 
 Thanks Koshal

On Friday, May 26, 2017, 3:54:22 AM EDT, Laurenz Albe <notifications@github.com> wrote:
As I told you in my first reply, prefetch won't work because there are CLOB columns.
That is probably why it takes so long.

I find that there is LOB prefetching in Oracle.
Could you apply this patch: lob_prefetch_patch.txt
Then check if the performance improves for you.

If I understand the documentation correctly, this will prefetch the whole CLOB (are they large?), but it will not allow row prefetching.

**Comment by laurenz** [comment] 2017-05-26 15:00
> How do i apply this patch.

How do you build oracle_fdw?

**Comment by patibandlakoshal** [comment] 2017-05-26 15:59
Using makemake install. Where do i need to put this file?
 Thanks Koshal

On Friday, May 26, 2017, 11:00:25 AM EDT, Laurenz Albe <notifications@github.com> wrote:

How do i apply this patch.


How do you build oracle_fdw?

**Comment by laurenz** [comment] 2017-05-29 06:38
Place it in the directory with all the *.c files. Then run

    patch -p1 </path/to/lob_prefetch_patch.txt

This should generate an output like this:

    patching file oracle_utils.c

Then run `make` and `make install` again.

**Comment by patibandlakoshal** [comment] 2017-05-31 03:12
Ran it couple of times. On the Oracle side it is inactive. I do not see any active connections. Earlier (before applying the patch) on the Oracle side when I  query V$session_longops  it used to  show approximately how long it would take (12 hours).  With the patch now I am not seeing any thing on the Oracle side. After 18 hours the session is still active in postgres and I dont see any  active  corresponding session in Oracle.
Here are the steps i used.  Tried both on both Postgresql 9.5 and  9.6.

apply path;make;make install;Dropped and recreated the extension cascade;
created server/user mappings.imported schema;
Tried to create table CTAS

 Thanks Koshal

On Monday, May 29, 2017, 2:38:30 AM EDT, Laurenz Albe <notifications@github.com> wrote:
Place it in the directory with all the *.c files. Then run
patch -p1 </path/to/lob_prefetch_patch.txt

This should generate an output like this:
patching file oracle_utils.c

Then run make and make install again.

**Comment by laurenz** [comment] 2017-05-31 07:49
Is that good or bad?
Did the patch change the duration `SELECT * FROM foreign_table`?

**Comment by patibandlakoshal** [comment] 2017-05-31 11:26
It is bad😀.  It is not completing insert.

**Comment by patibandlakoshal** [comment] 2017-05-31 11:27
With patch having issue with narrow table as well.

**Comment by laurenz** [comment] 2017-06-02 08:07
Then I won't add a feature like this to the code.

I can't help you with the speed then &ndash; as I said, it is probably caused by Oracle's inability to prefetch when LOB columns are present.

**Comment by laurenz** [comment] 2017-07-17 07:28
I'm closing that issue - if you still have a question related to this, please don't hesitate to reopen it.

**Closed by laurenz** 2017-07-17 07:28 UTC
Labels: problem
